#![allow(warnings)]
/// This file is auto-generated! It is generated from schema from https://github.com/xivdev/EXDSchema.
use physis::{resource::{Resource, read_excel_sheet_header, read_excel_sheet}, exd::{EXD, ColumnData, ExcelRowKind, ExcelSingleRow}, exh::{EXH, ExcelColumnDefinition}, common::Language};
pub struct CharaMakeStructElement<'a> {
Menu: &'a ColumnData,
SubMenuMask: &'a ColumnData,
Customize: &'a ColumnData,
SubMenuParam: &'a ColumnData,
InitVal: &'a ColumnData,
SubMenuType: &'a ColumnData,
SubMenuNum: &'a ColumnData,
LookAt: &'a ColumnData,
SubMenuGraphic: &'a ColumnData,
}
pub struct FacialFeatureOptionElement<'a> {
Option1: &'a ColumnData,
Option2: &'a ColumnData,
Option3: &'a ColumnData,
Option4: &'a ColumnData,
Option5: &'a ColumnData,
Option6: &'a ColumnData,
Option7: &'a ColumnData,
}
pub struct EquipmentElement<'a> {
Helmet: &'a ColumnData,
Top: &'a ColumnData,
Gloves: &'a ColumnData,
Legs: &'a ColumnData,
Shoes: &'a ColumnData,
Weapon: &'a ColumnData,
SubWeapon: &'a ColumnData,
}
pub struct CharaMakeTypeSheet {
pages: Vec<EXD>,
exh: EXH,
row_count: u32,
}
impl CharaMakeTypeSheet {
pub fn read_from<T: Resource>(resource: &mut T, language: Language) -> Option<Self> {
let exh = read_excel_sheet_header(resource, "CharaMakeType")?;
let mut pages = Vec::new();
for (i, _) in exh.pages.iter().enumerate() {
pages.push(read_excel_sheet(resource, "CharaMakeType", &exh, language, i)?);
}let row_count = exh.header.row_count;
Some(Self {
exh,
pages,
row_count,
})
}
fn read_row(&self, row: &ExcelSingleRow) -> Option<CharaMakeTypeRow> {
let column_defs = &self.exh.column_definitions;
let mut zipped: Vec<_> = row.columns.clone().into_iter().zip(column_defs).collect();
zipped.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
let (columns, _): (Vec<ColumnData>, Vec<ExcelColumnDefinition> ) = zipped.into_iter().unzip();
Some(CharaMakeTypeRow { columns })
}
/// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
pub fn get_row(&self, row_id: u32) -> Option<CharaMakeTypeRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => row,
ExcelRowKind::SubRows(rows) => &rows.first()?.1,
};
return self.read_row(row);
}
None
}
/// Fetches the specified subrow from the sheet.
pub fn get_subrow(&self, row_id: u32, subrow_id: u16) -> Option<CharaMakeTypeRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => return None,
ExcelRowKind::SubRows(subrows) => &subrows.iter().filter(|(id, _)| *id == subrow_id).next()?.1,
};
return self.read_row(row);
}
None
}
/// Returns the number of rows in this sheet.
pub fn row_count(&self) -> u32 {
self.row_count
}
}
pub struct CharaMakeTypeRow {
columns: Vec<ColumnData>,
}
impl CharaMakeTypeRow {
pub fn CharaMakeStruct<'a>(&'a self) -> [CharaMakeStructElement<'a>; 28] {
[CharaMakeStructElement {Menu: &self.columns[0],
SubMenuMask: &self.columns[1],
Customize: &self.columns[2],
SubMenuParam: &self.columns[3],
InitVal: &self.columns[4],
SubMenuType: &self.columns[5],
SubMenuNum: &self.columns[6],
LookAt: &self.columns[7],
SubMenuGraphic: &self.columns[8],
},
CharaMakeStructElement {Menu: &self.columns[9],
SubMenuMask: &self.columns[10],
Customize: &self.columns[11],
SubMenuParam: &self.columns[12],
InitVal: &self.columns[13],
SubMenuType: &self.columns[14],
SubMenuNum: &self.columns[15],
LookAt: &self.columns[16],
SubMenuGraphic: &self.columns[17],
},
CharaMakeStructElement {Menu: &self.columns[18],
SubMenuMask: &self.columns[19],
Customize: &self.columns[20],
SubMenuParam: &self.columns[21],
InitVal: &self.columns[22],
SubMenuType: &self.columns[23],
SubMenuNum: &self.columns[24],
LookAt: &self.columns[25],
SubMenuGraphic: &self.columns[26],
},
CharaMakeStructElement {Menu: &self.columns[27],
SubMenuMask: &self.columns[28],
Customize: &self.columns[29],
SubMenuParam: &self.columns[30],
InitVal: &self.columns[31],
SubMenuType: &self.columns[32],
SubMenuNum: &self.columns[33],
LookAt: &self.columns[34],
SubMenuGraphic: &self.columns[35],
},
CharaMakeStructElement {Menu: &self.columns[36],
SubMenuMask: &self.columns[37],
Customize: &self.columns[38],
SubMenuParam: &self.columns[39],
InitVal: &self.columns[40],
SubMenuType: &self.columns[41],
SubMenuNum: &self.columns[42],
LookAt: &self.columns[43],
SubMenuGraphic: &self.columns[44],
},
CharaMakeStructElement {Menu: &self.columns[45],
SubMenuMask: &self.columns[46],
Customize: &self.columns[47],
SubMenuParam: &self.columns[48],
InitVal: &self.columns[49],
SubMenuType: &self.columns[50],
SubMenuNum: &self.columns[51],
LookAt: &self.columns[52],
SubMenuGraphic: &self.columns[53],
},
CharaMakeStructElement {Menu: &self.columns[54],
SubMenuMask: &self.columns[55],
Customize: &self.columns[56],
SubMenuParam: &self.columns[57],
InitVal: &self.columns[58],
SubMenuType: &self.columns[59],
SubMenuNum: &self.columns[60],
LookAt: &self.columns[61],
SubMenuGraphic: &self.columns[62],
},
CharaMakeStructElement {Menu: &self.columns[63],
SubMenuMask: &self.columns[64],
Customize: &self.columns[65],
SubMenuParam: &self.columns[66],
InitVal: &self.columns[67],
SubMenuType: &self.columns[68],
SubMenuNum: &self.columns[69],
LookAt: &self.columns[70],
SubMenuGraphic: &self.columns[71],
},
CharaMakeStructElement {Menu: &self.columns[72],
SubMenuMask: &self.columns[73],
Customize: &self.columns[74],
SubMenuParam: &self.columns[75],
InitVal: &self.columns[76],
SubMenuType: &self.columns[77],
SubMenuNum: &self.columns[78],
LookAt: &self.columns[79],
SubMenuGraphic: &self.columns[80],
},
CharaMakeStructElement {Menu: &self.columns[81],
SubMenuMask: &self.columns[82],
Customize: &self.columns[83],
SubMenuParam: &self.columns[84],
InitVal: &self.columns[85],
SubMenuType: &self.columns[86],
SubMenuNum: &self.columns[87],
LookAt: &self.columns[88],
SubMenuGraphic: &self.columns[89],
},
CharaMakeStructElement {Menu: &self.columns[90],
SubMenuMask: &self.columns[91],
Customize: &self.columns[92],
SubMenuParam: &self.columns[93],
InitVal: &self.columns[94],
SubMenuType: &self.columns[95],
SubMenuNum: &self.columns[96],
LookAt: &self.columns[97],
SubMenuGraphic: &self.columns[98],
},
CharaMakeStructElement {Menu: &self.columns[99],
SubMenuMask: &self.columns[100],
Customize: &self.columns[101],
SubMenuParam: &self.columns[102],
InitVal: &self.columns[103],
SubMenuType: &self.columns[104],
SubMenuNum: &self.columns[105],
LookAt: &self.columns[106],
SubMenuGraphic: &self.columns[107],
},
CharaMakeStructElement {Menu: &self.columns[108],
SubMenuMask: &self.columns[109],
Customize: &self.columns[110],
SubMenuParam: &self.columns[111],
InitVal: &self.columns[112],
SubMenuType: &self.columns[113],
SubMenuNum: &self.columns[114],
LookAt: &self.columns[115],
SubMenuGraphic: &self.columns[116],
},
CharaMakeStructElement {Menu: &self.columns[117],
SubMenuMask: &self.columns[118],
Customize: &self.columns[119],
SubMenuParam: &self.columns[120],
InitVal: &self.columns[121],
SubMenuType: &self.columns[122],
SubMenuNum: &self.columns[123],
LookAt: &self.columns[124],
SubMenuGraphic: &self.columns[125],
},
CharaMakeStructElement {Menu: &self.columns[126],
SubMenuMask: &self.columns[127],
Customize: &self.columns[128],
SubMenuParam: &self.columns[129],
InitVal: &self.columns[130],
SubMenuType: &self.columns[131],
SubMenuNum: &self.columns[132],
LookAt: &self.columns[133],
SubMenuGraphic: &self.columns[134],
},
CharaMakeStructElement {Menu: &self.columns[135],
SubMenuMask: &self.columns[136],
Customize: &self.columns[137],
SubMenuParam: &self.columns[138],
InitVal: &self.columns[139],
SubMenuType: &self.columns[140],
SubMenuNum: &self.columns[141],
LookAt: &self.columns[142],
SubMenuGraphic: &self.columns[143],
},
CharaMakeStructElement {Menu: &self.columns[144],
SubMenuMask: &self.columns[145],
Customize: &self.columns[146],
SubMenuParam: &self.columns[147],
InitVal: &self.columns[148],
SubMenuType: &self.columns[149],
SubMenuNum: &self.columns[150],
LookAt: &self.columns[151],
SubMenuGraphic: &self.columns[152],
},
CharaMakeStructElement {Menu: &self.columns[153],
SubMenuMask: &self.columns[154],
Customize: &self.columns[155],
SubMenuParam: &self.columns[156],
InitVal: &self.columns[157],
SubMenuType: &self.columns[158],
SubMenuNum: &self.columns[159],
LookAt: &self.columns[160],
SubMenuGraphic: &self.columns[161],
},
CharaMakeStructElement {Menu: &self.columns[162],
SubMenuMask: &self.columns[163],
Customize: &self.columns[164],
SubMenuParam: &self.columns[165],
InitVal: &self.columns[166],
SubMenuType: &self.columns[167],
SubMenuNum: &self.columns[168],
LookAt: &self.columns[169],
SubMenuGraphic: &self.columns[170],
},
CharaMakeStructElement {Menu: &self.columns[171],
SubMenuMask: &self.columns[172],
Customize: &self.columns[173],
SubMenuParam: &self.columns[174],
InitVal: &self.columns[175],
SubMenuType: &self.columns[176],
SubMenuNum: &self.columns[177],
LookAt: &self.columns[178],
SubMenuGraphic: &self.columns[179],
},
CharaMakeStructElement {Menu: &self.columns[180],
SubMenuMask: &self.columns[181],
Customize: &self.columns[182],
SubMenuParam: &self.columns[183],
InitVal: &self.columns[184],
SubMenuType: &self.columns[185],
SubMenuNum: &self.columns[186],
LookAt: &self.columns[187],
SubMenuGraphic: &self.columns[188],
},
CharaMakeStructElement {Menu: &self.columns[189],
SubMenuMask: &self.columns[190],
Customize: &self.columns[191],
SubMenuParam: &self.columns[192],
InitVal: &self.columns[193],
SubMenuType: &self.columns[194],
SubMenuNum: &self.columns[195],
LookAt: &self.columns[196],
SubMenuGraphic: &self.columns[197],
},
CharaMakeStructElement {Menu: &self.columns[198],
SubMenuMask: &self.columns[199],
Customize: &self.columns[200],
SubMenuParam: &self.columns[201],
InitVal: &self.columns[202],
SubMenuType: &self.columns[203],
SubMenuNum: &self.columns[204],
LookAt: &self.columns[205],
SubMenuGraphic: &self.columns[206],
},
CharaMakeStructElement {Menu: &self.columns[207],
SubMenuMask: &self.columns[208],
Customize: &self.columns[209],
SubMenuParam: &self.columns[210],
InitVal: &self.columns[211],
SubMenuType: &self.columns[212],
SubMenuNum: &self.columns[213],
LookAt: &self.columns[214],
SubMenuGraphic: &self.columns[215],
},
CharaMakeStructElement {Menu: &self.columns[216],
SubMenuMask: &self.columns[217],
Customize: &self.columns[218],
SubMenuParam: &self.columns[219],
InitVal: &self.columns[220],
SubMenuType: &self.columns[221],
SubMenuNum: &self.columns[222],
LookAt: &self.columns[223],
SubMenuGraphic: &self.columns[224],
},
CharaMakeStructElement {Menu: &self.columns[225],
SubMenuMask: &self.columns[226],
Customize: &self.columns[227],
SubMenuParam: &self.columns[228],
InitVal: &self.columns[229],
SubMenuType: &self.columns[230],
SubMenuNum: &self.columns[231],
LookAt: &self.columns[232],
SubMenuGraphic: &self.columns[233],
},
CharaMakeStructElement {Menu: &self.columns[234],
SubMenuMask: &self.columns[235],
Customize: &self.columns[236],
SubMenuParam: &self.columns[237],
InitVal: &self.columns[238],
SubMenuType: &self.columns[239],
SubMenuNum: &self.columns[240],
LookAt: &self.columns[241],
SubMenuGraphic: &self.columns[242],
},
CharaMakeStructElement {Menu: &self.columns[243],
SubMenuMask: &self.columns[244],
Customize: &self.columns[245],
SubMenuParam: &self.columns[246],
InitVal: &self.columns[247],
SubMenuType: &self.columns[248],
SubMenuNum: &self.columns[249],
LookAt: &self.columns[250],
SubMenuGraphic: &self.columns[251],
},
]
}
pub fn VoiceStruct(&self) -> [&ColumnData; 12] {
[&self.columns[252],&self.columns[253],&self.columns[254],&self.columns[255],&self.columns[256],&self.columns[257],&self.columns[258],&self.columns[259],&self.columns[260],&self.columns[261],&self.columns[262],&self.columns[263],]
}
pub fn FacialFeatureOption<'a>(&'a self) -> [FacialFeatureOptionElement<'a>; 8] {
[FacialFeatureOptionElement {Option1: &self.columns[264],
Option2: &self.columns[265],
Option3: &self.columns[266],
Option4: &self.columns[267],
Option5: &self.columns[268],
Option6: &self.columns[269],
Option7: &self.columns[270],
},
FacialFeatureOptionElement {Option1: &self.columns[271],
Option2: &self.columns[272],
Option3: &self.columns[273],
Option4: &self.columns[274],
Option5: &self.columns[275],
Option6: &self.columns[276],
Option7: &self.columns[277],
},
FacialFeatureOptionElement {Option1: &self.columns[278],
Option2: &self.columns[279],
Option3: &self.columns[280],
Option4: &self.columns[281],
Option5: &self.columns[282],
Option6: &self.columns[283],
Option7: &self.columns[284],
},
FacialFeatureOptionElement {Option1: &self.columns[285],
Option2: &self.columns[286],
Option3: &self.columns[287],
Option4: &self.columns[288],
Option5: &self.columns[289],
Option6: &self.columns[290],
Option7: &self.columns[291],
},
FacialFeatureOptionElement {Option1: &self.columns[292],
Option2: &self.columns[293],
Option3: &self.columns[294],
Option4: &self.columns[295],
Option5: &self.columns[296],
Option6: &self.columns[297],
Option7: &self.columns[298],
},
FacialFeatureOptionElement {Option1: &self.columns[299],
Option2: &self.columns[300],
Option3: &self.columns[301],
Option4: &self.columns[302],
Option5: &self.columns[303],
Option6: &self.columns[304],
Option7: &self.columns[305],
},
FacialFeatureOptionElement {Option1: &self.columns[306],
Option2: &self.columns[307],
Option3: &self.columns[308],
Option4: &self.columns[309],
Option5: &self.columns[310],
Option6: &self.columns[311],
Option7: &self.columns[312],
},
FacialFeatureOptionElement {Option1: &self.columns[313],
Option2: &self.columns[314],
Option3: &self.columns[315],
Option4: &self.columns[316],
Option5: &self.columns[317],
Option6: &self.columns[318],
Option7: &self.columns[319],
},
]
}
pub fn Equipment<'a>(&'a self) -> [EquipmentElement<'a>; 3] {
[EquipmentElement {Helmet: &self.columns[320],
Top: &self.columns[321],
Gloves: &self.columns[322],
Legs: &self.columns[323],
Shoes: &self.columns[324],
Weapon: &self.columns[325],
SubWeapon: &self.columns[326],
},
EquipmentElement {Helmet: &self.columns[327],
Top: &self.columns[328],
Gloves: &self.columns[329],
Legs: &self.columns[330],
Shoes: &self.columns[331],
Weapon: &self.columns[332],
SubWeapon: &self.columns[333],
},
EquipmentElement {Helmet: &self.columns[334],
Top: &self.columns[335],
Gloves: &self.columns[336],
Legs: &self.columns[337],
Shoes: &self.columns[338],
Weapon: &self.columns[339],
SubWeapon: &self.columns[340],
},
]
}
pub fn Race(&self) -> &ColumnData {
&self.columns[341]
}
pub fn Tribe(&self) -> &ColumnData {
&self.columns[342]
}
pub fn Gender(&self) -> &ColumnData {
&self.columns[343]
}
}
