//! This file is auto-generated, do not edit it manually! This is generated based on the schema from https://github.com/xivdev/EXDSchema.
#![allow(warnings)]
use crate::{StructuredSheet, StructuredSheetIterator};
use physis::{
    Error, resource::{Resource, ResourceResolver},
    exd::EXD, exh::{EXH, ExcelColumnDefinition},
    excel::{Sheet, Field, Row},
    Language,
};
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CharaMakeStructElement {
    pub Menu: u32,
    pub SubMenuMask: u32,
    pub Customize: u32,
    pub SubMenuParam: [u32; 100],
    pub Unknown0: [u32; 6],
    pub InitVal: u8,
    pub SubMenuType: u8,
    pub SubMenuNum: u8,
    pub LookAt: u8,
    pub SubMenuGraphic: [u8; 10],
}
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FacialFeatureOptionElement {
    pub Option1: i32,
    pub Option2: i32,
    pub Option3: i32,
    pub Option4: i32,
    pub Option5: i32,
    pub Option6: i32,
    pub Option7: i32,
}
#[derive(Debug, Clone)]
pub struct HairMakeTypeSheet {
    sheet: Sheet,
}
impl HairMakeTypeSheet {
    /// Read the sheet from a `ResourceResolver`.
    pub fn read_from(
        resolver: &mut ResourceResolver,
        language: Language,
    ) -> Result<Self, Error> {
        let exh = resolver.read_excel_sheet_header("HairMakeType")?;
        let sheet = resolver.read_excel_sheet(&exh, "HairMakeType", language)?;
        Ok(Self { sheet })
    }
    /// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
    pub fn row(&self, row_id: u32) -> Option<HairMakeTypeRow> {
        let row = &self.sheet.row(row_id)?;
        self.read_row(row)
    }
    /// Fetches the specified subrow from the sheet.
    pub fn subrow(&self, row_id: u32, subrow_id: u16) -> Option<HairMakeTypeRow> {
        let row = &self.sheet.subrow(row_id, subrow_id)?;
        self.read_row(row)
    }
    /// Returns the number of rows in this sheet.
    pub fn row_count(&self) -> u32 {
        self.sheet.exh.header.row_count
    }
}
impl<'a> StructuredSheet<'a> for HairMakeTypeSheet {
    type Row = HairMakeTypeRow<'a>;
    fn read_row(&self, row: &'a Row) -> Option<Self::Row> {
        Some(Self::Row { row })
    }
}
impl<'a> IntoIterator for &'a HairMakeTypeSheet {
    type Item = (u32, Vec<(u16, HairMakeTypeRow<'a>)>);
    type IntoIter = StructuredSheetIterator<'a, HairMakeTypeSheet>;
    fn into_iter(self) -> StructuredSheetIterator<'a, HairMakeTypeSheet> {
        StructuredSheetIterator {
            sheet: self,
            iterator: (&self.sheet).into_iter(),
        }
    }
}
#[derive(Debug, Clone)]
pub struct HairMakeTypeRow<'a> {
    row: &'a Row,
}
impl<'a> HairMakeTypeRow<'a> {
    pub fn CharaMakeStruct(&'a self) -> [CharaMakeStructElement; 9] {
        [
            CharaMakeStructElement {
                Menu: self.row.columns[3].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[48].into_u32().copied().unwrap(),
                Customize: self.row.columns[57].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[66].into_u32().copied().unwrap(),
                    self.row.columns[75].into_u32().copied().unwrap(),
                    self.row.columns[84].into_u32().copied().unwrap(),
                    self.row.columns[93].into_u32().copied().unwrap(),
                    self.row.columns[102].into_u32().copied().unwrap(),
                    self.row.columns[111].into_u32().copied().unwrap(),
                    self.row.columns[120].into_u32().copied().unwrap(),
                    self.row.columns[129].into_u32().copied().unwrap(),
                    self.row.columns[138].into_u32().copied().unwrap(),
                    self.row.columns[147].into_u32().copied().unwrap(),
                    self.row.columns[156].into_u32().copied().unwrap(),
                    self.row.columns[165].into_u32().copied().unwrap(),
                    self.row.columns[174].into_u32().copied().unwrap(),
                    self.row.columns[183].into_u32().copied().unwrap(),
                    self.row.columns[192].into_u32().copied().unwrap(),
                    self.row.columns[201].into_u32().copied().unwrap(),
                    self.row.columns[210].into_u32().copied().unwrap(),
                    self.row.columns[219].into_u32().copied().unwrap(),
                    self.row.columns[228].into_u32().copied().unwrap(),
                    self.row.columns[237].into_u32().copied().unwrap(),
                    self.row.columns[246].into_u32().copied().unwrap(),
                    self.row.columns[255].into_u32().copied().unwrap(),
                    self.row.columns[264].into_u32().copied().unwrap(),
                    self.row.columns[273].into_u32().copied().unwrap(),
                    self.row.columns[282].into_u32().copied().unwrap(),
                    self.row.columns[291].into_u32().copied().unwrap(),
                    self.row.columns[300].into_u32().copied().unwrap(),
                    self.row.columns[309].into_u32().copied().unwrap(),
                    self.row.columns[318].into_u32().copied().unwrap(),
                    self.row.columns[327].into_u32().copied().unwrap(),
                    self.row.columns[336].into_u32().copied().unwrap(),
                    self.row.columns[345].into_u32().copied().unwrap(),
                    self.row.columns[354].into_u32().copied().unwrap(),
                    self.row.columns[363].into_u32().copied().unwrap(),
                    self.row.columns[372].into_u32().copied().unwrap(),
                    self.row.columns[381].into_u32().copied().unwrap(),
                    self.row.columns[390].into_u32().copied().unwrap(),
                    self.row.columns[399].into_u32().copied().unwrap(),
                    self.row.columns[408].into_u32().copied().unwrap(),
                    self.row.columns[417].into_u32().copied().unwrap(),
                    self.row.columns[426].into_u32().copied().unwrap(),
                    self.row.columns[435].into_u32().copied().unwrap(),
                    self.row.columns[444].into_u32().copied().unwrap(),
                    self.row.columns[453].into_u32().copied().unwrap(),
                    self.row.columns[462].into_u32().copied().unwrap(),
                    self.row.columns[471].into_u32().copied().unwrap(),
                    self.row.columns[480].into_u32().copied().unwrap(),
                    self.row.columns[489].into_u32().copied().unwrap(),
                    self.row.columns[498].into_u32().copied().unwrap(),
                    self.row.columns[507].into_u32().copied().unwrap(),
                    self.row.columns[516].into_u32().copied().unwrap(),
                    self.row.columns[525].into_u32().copied().unwrap(),
                    self.row.columns[534].into_u32().copied().unwrap(),
                    self.row.columns[543].into_u32().copied().unwrap(),
                    self.row.columns[552].into_u32().copied().unwrap(),
                    self.row.columns[561].into_u32().copied().unwrap(),
                    self.row.columns[570].into_u32().copied().unwrap(),
                    self.row.columns[579].into_u32().copied().unwrap(),
                    self.row.columns[588].into_u32().copied().unwrap(),
                    self.row.columns[597].into_u32().copied().unwrap(),
                    self.row.columns[606].into_u32().copied().unwrap(),
                    self.row.columns[615].into_u32().copied().unwrap(),
                    self.row.columns[624].into_u32().copied().unwrap(),
                    self.row.columns[633].into_u32().copied().unwrap(),
                    self.row.columns[642].into_u32().copied().unwrap(),
                    self.row.columns[651].into_u32().copied().unwrap(),
                    self.row.columns[660].into_u32().copied().unwrap(),
                    self.row.columns[669].into_u32().copied().unwrap(),
                    self.row.columns[678].into_u32().copied().unwrap(),
                    self.row.columns[687].into_u32().copied().unwrap(),
                    self.row.columns[696].into_u32().copied().unwrap(),
                    self.row.columns[705].into_u32().copied().unwrap(),
                    self.row.columns[714].into_u32().copied().unwrap(),
                    self.row.columns[723].into_u32().copied().unwrap(),
                    self.row.columns[732].into_u32().copied().unwrap(),
                    self.row.columns[741].into_u32().copied().unwrap(),
                    self.row.columns[750].into_u32().copied().unwrap(),
                    self.row.columns[759].into_u32().copied().unwrap(),
                    self.row.columns[768].into_u32().copied().unwrap(),
                    self.row.columns[777].into_u32().copied().unwrap(),
                    self.row.columns[786].into_u32().copied().unwrap(),
                    self.row.columns[795].into_u32().copied().unwrap(),
                    self.row.columns[804].into_u32().copied().unwrap(),
                    self.row.columns[813].into_u32().copied().unwrap(),
                    self.row.columns[822].into_u32().copied().unwrap(),
                    self.row.columns[831].into_u32().copied().unwrap(),
                    self.row.columns[840].into_u32().copied().unwrap(),
                    self.row.columns[849].into_u32().copied().unwrap(),
                    self.row.columns[858].into_u32().copied().unwrap(),
                    self.row.columns[867].into_u32().copied().unwrap(),
                    self.row.columns[876].into_u32().copied().unwrap(),
                    self.row.columns[885].into_u32().copied().unwrap(),
                    self.row.columns[894].into_u32().copied().unwrap(),
                    self.row.columns[903].into_u32().copied().unwrap(),
                    self.row.columns[912].into_u32().copied().unwrap(),
                    self.row.columns[921].into_u32().copied().unwrap(),
                    self.row.columns[930].into_u32().copied().unwrap(),
                    self.row.columns[939].into_u32().copied().unwrap(),
                    self.row.columns[948].into_u32().copied().unwrap(),
                    self.row.columns[957].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[966].into_u32().copied().unwrap(),
                    self.row.columns[975].into_u32().copied().unwrap(),
                    self.row.columns[984].into_u32().copied().unwrap(),
                    self.row.columns[993].into_u32().copied().unwrap(),
                    self.row.columns[1002].into_u32().copied().unwrap(),
                    self.row.columns[1011].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[12].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[21].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[30].into_u8().copied().unwrap(),
                LookAt: self.row.columns[39].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1020].into_u8().copied().unwrap(),
                    self.row.columns[1029].into_u8().copied().unwrap(),
                    self.row.columns[1038].into_u8().copied().unwrap(),
                    self.row.columns[1047].into_u8().copied().unwrap(),
                    self.row.columns[1056].into_u8().copied().unwrap(),
                    self.row.columns[1065].into_u8().copied().unwrap(),
                    self.row.columns[1074].into_u8().copied().unwrap(),
                    self.row.columns[1083].into_u8().copied().unwrap(),
                    self.row.columns[1092].into_u8().copied().unwrap(),
                    self.row.columns[1101].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[4].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[49].into_u32().copied().unwrap(),
                Customize: self.row.columns[58].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[67].into_u32().copied().unwrap(),
                    self.row.columns[76].into_u32().copied().unwrap(),
                    self.row.columns[85].into_u32().copied().unwrap(),
                    self.row.columns[94].into_u32().copied().unwrap(),
                    self.row.columns[103].into_u32().copied().unwrap(),
                    self.row.columns[112].into_u32().copied().unwrap(),
                    self.row.columns[121].into_u32().copied().unwrap(),
                    self.row.columns[130].into_u32().copied().unwrap(),
                    self.row.columns[139].into_u32().copied().unwrap(),
                    self.row.columns[148].into_u32().copied().unwrap(),
                    self.row.columns[157].into_u32().copied().unwrap(),
                    self.row.columns[166].into_u32().copied().unwrap(),
                    self.row.columns[175].into_u32().copied().unwrap(),
                    self.row.columns[184].into_u32().copied().unwrap(),
                    self.row.columns[193].into_u32().copied().unwrap(),
                    self.row.columns[202].into_u32().copied().unwrap(),
                    self.row.columns[211].into_u32().copied().unwrap(),
                    self.row.columns[220].into_u32().copied().unwrap(),
                    self.row.columns[229].into_u32().copied().unwrap(),
                    self.row.columns[238].into_u32().copied().unwrap(),
                    self.row.columns[247].into_u32().copied().unwrap(),
                    self.row.columns[256].into_u32().copied().unwrap(),
                    self.row.columns[265].into_u32().copied().unwrap(),
                    self.row.columns[274].into_u32().copied().unwrap(),
                    self.row.columns[283].into_u32().copied().unwrap(),
                    self.row.columns[292].into_u32().copied().unwrap(),
                    self.row.columns[301].into_u32().copied().unwrap(),
                    self.row.columns[310].into_u32().copied().unwrap(),
                    self.row.columns[319].into_u32().copied().unwrap(),
                    self.row.columns[328].into_u32().copied().unwrap(),
                    self.row.columns[337].into_u32().copied().unwrap(),
                    self.row.columns[346].into_u32().copied().unwrap(),
                    self.row.columns[355].into_u32().copied().unwrap(),
                    self.row.columns[364].into_u32().copied().unwrap(),
                    self.row.columns[373].into_u32().copied().unwrap(),
                    self.row.columns[382].into_u32().copied().unwrap(),
                    self.row.columns[391].into_u32().copied().unwrap(),
                    self.row.columns[400].into_u32().copied().unwrap(),
                    self.row.columns[409].into_u32().copied().unwrap(),
                    self.row.columns[418].into_u32().copied().unwrap(),
                    self.row.columns[427].into_u32().copied().unwrap(),
                    self.row.columns[436].into_u32().copied().unwrap(),
                    self.row.columns[445].into_u32().copied().unwrap(),
                    self.row.columns[454].into_u32().copied().unwrap(),
                    self.row.columns[463].into_u32().copied().unwrap(),
                    self.row.columns[472].into_u32().copied().unwrap(),
                    self.row.columns[481].into_u32().copied().unwrap(),
                    self.row.columns[490].into_u32().copied().unwrap(),
                    self.row.columns[499].into_u32().copied().unwrap(),
                    self.row.columns[508].into_u32().copied().unwrap(),
                    self.row.columns[517].into_u32().copied().unwrap(),
                    self.row.columns[526].into_u32().copied().unwrap(),
                    self.row.columns[535].into_u32().copied().unwrap(),
                    self.row.columns[544].into_u32().copied().unwrap(),
                    self.row.columns[553].into_u32().copied().unwrap(),
                    self.row.columns[562].into_u32().copied().unwrap(),
                    self.row.columns[571].into_u32().copied().unwrap(),
                    self.row.columns[580].into_u32().copied().unwrap(),
                    self.row.columns[589].into_u32().copied().unwrap(),
                    self.row.columns[598].into_u32().copied().unwrap(),
                    self.row.columns[607].into_u32().copied().unwrap(),
                    self.row.columns[616].into_u32().copied().unwrap(),
                    self.row.columns[625].into_u32().copied().unwrap(),
                    self.row.columns[634].into_u32().copied().unwrap(),
                    self.row.columns[643].into_u32().copied().unwrap(),
                    self.row.columns[652].into_u32().copied().unwrap(),
                    self.row.columns[661].into_u32().copied().unwrap(),
                    self.row.columns[670].into_u32().copied().unwrap(),
                    self.row.columns[679].into_u32().copied().unwrap(),
                    self.row.columns[688].into_u32().copied().unwrap(),
                    self.row.columns[697].into_u32().copied().unwrap(),
                    self.row.columns[706].into_u32().copied().unwrap(),
                    self.row.columns[715].into_u32().copied().unwrap(),
                    self.row.columns[724].into_u32().copied().unwrap(),
                    self.row.columns[733].into_u32().copied().unwrap(),
                    self.row.columns[742].into_u32().copied().unwrap(),
                    self.row.columns[751].into_u32().copied().unwrap(),
                    self.row.columns[760].into_u32().copied().unwrap(),
                    self.row.columns[769].into_u32().copied().unwrap(),
                    self.row.columns[778].into_u32().copied().unwrap(),
                    self.row.columns[787].into_u32().copied().unwrap(),
                    self.row.columns[796].into_u32().copied().unwrap(),
                    self.row.columns[805].into_u32().copied().unwrap(),
                    self.row.columns[814].into_u32().copied().unwrap(),
                    self.row.columns[823].into_u32().copied().unwrap(),
                    self.row.columns[832].into_u32().copied().unwrap(),
                    self.row.columns[841].into_u32().copied().unwrap(),
                    self.row.columns[850].into_u32().copied().unwrap(),
                    self.row.columns[859].into_u32().copied().unwrap(),
                    self.row.columns[868].into_u32().copied().unwrap(),
                    self.row.columns[877].into_u32().copied().unwrap(),
                    self.row.columns[886].into_u32().copied().unwrap(),
                    self.row.columns[895].into_u32().copied().unwrap(),
                    self.row.columns[904].into_u32().copied().unwrap(),
                    self.row.columns[913].into_u32().copied().unwrap(),
                    self.row.columns[922].into_u32().copied().unwrap(),
                    self.row.columns[931].into_u32().copied().unwrap(),
                    self.row.columns[940].into_u32().copied().unwrap(),
                    self.row.columns[949].into_u32().copied().unwrap(),
                    self.row.columns[958].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[967].into_u32().copied().unwrap(),
                    self.row.columns[976].into_u32().copied().unwrap(),
                    self.row.columns[985].into_u32().copied().unwrap(),
                    self.row.columns[994].into_u32().copied().unwrap(),
                    self.row.columns[1003].into_u32().copied().unwrap(),
                    self.row.columns[1012].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[13].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[22].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[31].into_u8().copied().unwrap(),
                LookAt: self.row.columns[40].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1021].into_u8().copied().unwrap(),
                    self.row.columns[1030].into_u8().copied().unwrap(),
                    self.row.columns[1039].into_u8().copied().unwrap(),
                    self.row.columns[1048].into_u8().copied().unwrap(),
                    self.row.columns[1057].into_u8().copied().unwrap(),
                    self.row.columns[1066].into_u8().copied().unwrap(),
                    self.row.columns[1075].into_u8().copied().unwrap(),
                    self.row.columns[1084].into_u8().copied().unwrap(),
                    self.row.columns[1093].into_u8().copied().unwrap(),
                    self.row.columns[1102].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[5].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[50].into_u32().copied().unwrap(),
                Customize: self.row.columns[59].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[68].into_u32().copied().unwrap(),
                    self.row.columns[77].into_u32().copied().unwrap(),
                    self.row.columns[86].into_u32().copied().unwrap(),
                    self.row.columns[95].into_u32().copied().unwrap(),
                    self.row.columns[104].into_u32().copied().unwrap(),
                    self.row.columns[113].into_u32().copied().unwrap(),
                    self.row.columns[122].into_u32().copied().unwrap(),
                    self.row.columns[131].into_u32().copied().unwrap(),
                    self.row.columns[140].into_u32().copied().unwrap(),
                    self.row.columns[149].into_u32().copied().unwrap(),
                    self.row.columns[158].into_u32().copied().unwrap(),
                    self.row.columns[167].into_u32().copied().unwrap(),
                    self.row.columns[176].into_u32().copied().unwrap(),
                    self.row.columns[185].into_u32().copied().unwrap(),
                    self.row.columns[194].into_u32().copied().unwrap(),
                    self.row.columns[203].into_u32().copied().unwrap(),
                    self.row.columns[212].into_u32().copied().unwrap(),
                    self.row.columns[221].into_u32().copied().unwrap(),
                    self.row.columns[230].into_u32().copied().unwrap(),
                    self.row.columns[239].into_u32().copied().unwrap(),
                    self.row.columns[248].into_u32().copied().unwrap(),
                    self.row.columns[257].into_u32().copied().unwrap(),
                    self.row.columns[266].into_u32().copied().unwrap(),
                    self.row.columns[275].into_u32().copied().unwrap(),
                    self.row.columns[284].into_u32().copied().unwrap(),
                    self.row.columns[293].into_u32().copied().unwrap(),
                    self.row.columns[302].into_u32().copied().unwrap(),
                    self.row.columns[311].into_u32().copied().unwrap(),
                    self.row.columns[320].into_u32().copied().unwrap(),
                    self.row.columns[329].into_u32().copied().unwrap(),
                    self.row.columns[338].into_u32().copied().unwrap(),
                    self.row.columns[347].into_u32().copied().unwrap(),
                    self.row.columns[356].into_u32().copied().unwrap(),
                    self.row.columns[365].into_u32().copied().unwrap(),
                    self.row.columns[374].into_u32().copied().unwrap(),
                    self.row.columns[383].into_u32().copied().unwrap(),
                    self.row.columns[392].into_u32().copied().unwrap(),
                    self.row.columns[401].into_u32().copied().unwrap(),
                    self.row.columns[410].into_u32().copied().unwrap(),
                    self.row.columns[419].into_u32().copied().unwrap(),
                    self.row.columns[428].into_u32().copied().unwrap(),
                    self.row.columns[437].into_u32().copied().unwrap(),
                    self.row.columns[446].into_u32().copied().unwrap(),
                    self.row.columns[455].into_u32().copied().unwrap(),
                    self.row.columns[464].into_u32().copied().unwrap(),
                    self.row.columns[473].into_u32().copied().unwrap(),
                    self.row.columns[482].into_u32().copied().unwrap(),
                    self.row.columns[491].into_u32().copied().unwrap(),
                    self.row.columns[500].into_u32().copied().unwrap(),
                    self.row.columns[509].into_u32().copied().unwrap(),
                    self.row.columns[518].into_u32().copied().unwrap(),
                    self.row.columns[527].into_u32().copied().unwrap(),
                    self.row.columns[536].into_u32().copied().unwrap(),
                    self.row.columns[545].into_u32().copied().unwrap(),
                    self.row.columns[554].into_u32().copied().unwrap(),
                    self.row.columns[563].into_u32().copied().unwrap(),
                    self.row.columns[572].into_u32().copied().unwrap(),
                    self.row.columns[581].into_u32().copied().unwrap(),
                    self.row.columns[590].into_u32().copied().unwrap(),
                    self.row.columns[599].into_u32().copied().unwrap(),
                    self.row.columns[608].into_u32().copied().unwrap(),
                    self.row.columns[617].into_u32().copied().unwrap(),
                    self.row.columns[626].into_u32().copied().unwrap(),
                    self.row.columns[635].into_u32().copied().unwrap(),
                    self.row.columns[644].into_u32().copied().unwrap(),
                    self.row.columns[653].into_u32().copied().unwrap(),
                    self.row.columns[662].into_u32().copied().unwrap(),
                    self.row.columns[671].into_u32().copied().unwrap(),
                    self.row.columns[680].into_u32().copied().unwrap(),
                    self.row.columns[689].into_u32().copied().unwrap(),
                    self.row.columns[698].into_u32().copied().unwrap(),
                    self.row.columns[707].into_u32().copied().unwrap(),
                    self.row.columns[716].into_u32().copied().unwrap(),
                    self.row.columns[725].into_u32().copied().unwrap(),
                    self.row.columns[734].into_u32().copied().unwrap(),
                    self.row.columns[743].into_u32().copied().unwrap(),
                    self.row.columns[752].into_u32().copied().unwrap(),
                    self.row.columns[761].into_u32().copied().unwrap(),
                    self.row.columns[770].into_u32().copied().unwrap(),
                    self.row.columns[779].into_u32().copied().unwrap(),
                    self.row.columns[788].into_u32().copied().unwrap(),
                    self.row.columns[797].into_u32().copied().unwrap(),
                    self.row.columns[806].into_u32().copied().unwrap(),
                    self.row.columns[815].into_u32().copied().unwrap(),
                    self.row.columns[824].into_u32().copied().unwrap(),
                    self.row.columns[833].into_u32().copied().unwrap(),
                    self.row.columns[842].into_u32().copied().unwrap(),
                    self.row.columns[851].into_u32().copied().unwrap(),
                    self.row.columns[860].into_u32().copied().unwrap(),
                    self.row.columns[869].into_u32().copied().unwrap(),
                    self.row.columns[878].into_u32().copied().unwrap(),
                    self.row.columns[887].into_u32().copied().unwrap(),
                    self.row.columns[896].into_u32().copied().unwrap(),
                    self.row.columns[905].into_u32().copied().unwrap(),
                    self.row.columns[914].into_u32().copied().unwrap(),
                    self.row.columns[923].into_u32().copied().unwrap(),
                    self.row.columns[932].into_u32().copied().unwrap(),
                    self.row.columns[941].into_u32().copied().unwrap(),
                    self.row.columns[950].into_u32().copied().unwrap(),
                    self.row.columns[959].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[968].into_u32().copied().unwrap(),
                    self.row.columns[977].into_u32().copied().unwrap(),
                    self.row.columns[986].into_u32().copied().unwrap(),
                    self.row.columns[995].into_u32().copied().unwrap(),
                    self.row.columns[1004].into_u32().copied().unwrap(),
                    self.row.columns[1013].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[14].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[23].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[32].into_u8().copied().unwrap(),
                LookAt: self.row.columns[41].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1022].into_u8().copied().unwrap(),
                    self.row.columns[1031].into_u8().copied().unwrap(),
                    self.row.columns[1040].into_u8().copied().unwrap(),
                    self.row.columns[1049].into_u8().copied().unwrap(),
                    self.row.columns[1058].into_u8().copied().unwrap(),
                    self.row.columns[1067].into_u8().copied().unwrap(),
                    self.row.columns[1076].into_u8().copied().unwrap(),
                    self.row.columns[1085].into_u8().copied().unwrap(),
                    self.row.columns[1094].into_u8().copied().unwrap(),
                    self.row.columns[1103].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[6].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[51].into_u32().copied().unwrap(),
                Customize: self.row.columns[60].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[69].into_u32().copied().unwrap(),
                    self.row.columns[78].into_u32().copied().unwrap(),
                    self.row.columns[87].into_u32().copied().unwrap(),
                    self.row.columns[96].into_u32().copied().unwrap(),
                    self.row.columns[105].into_u32().copied().unwrap(),
                    self.row.columns[114].into_u32().copied().unwrap(),
                    self.row.columns[123].into_u32().copied().unwrap(),
                    self.row.columns[132].into_u32().copied().unwrap(),
                    self.row.columns[141].into_u32().copied().unwrap(),
                    self.row.columns[150].into_u32().copied().unwrap(),
                    self.row.columns[159].into_u32().copied().unwrap(),
                    self.row.columns[168].into_u32().copied().unwrap(),
                    self.row.columns[177].into_u32().copied().unwrap(),
                    self.row.columns[186].into_u32().copied().unwrap(),
                    self.row.columns[195].into_u32().copied().unwrap(),
                    self.row.columns[204].into_u32().copied().unwrap(),
                    self.row.columns[213].into_u32().copied().unwrap(),
                    self.row.columns[222].into_u32().copied().unwrap(),
                    self.row.columns[231].into_u32().copied().unwrap(),
                    self.row.columns[240].into_u32().copied().unwrap(),
                    self.row.columns[249].into_u32().copied().unwrap(),
                    self.row.columns[258].into_u32().copied().unwrap(),
                    self.row.columns[267].into_u32().copied().unwrap(),
                    self.row.columns[276].into_u32().copied().unwrap(),
                    self.row.columns[285].into_u32().copied().unwrap(),
                    self.row.columns[294].into_u32().copied().unwrap(),
                    self.row.columns[303].into_u32().copied().unwrap(),
                    self.row.columns[312].into_u32().copied().unwrap(),
                    self.row.columns[321].into_u32().copied().unwrap(),
                    self.row.columns[330].into_u32().copied().unwrap(),
                    self.row.columns[339].into_u32().copied().unwrap(),
                    self.row.columns[348].into_u32().copied().unwrap(),
                    self.row.columns[357].into_u32().copied().unwrap(),
                    self.row.columns[366].into_u32().copied().unwrap(),
                    self.row.columns[375].into_u32().copied().unwrap(),
                    self.row.columns[384].into_u32().copied().unwrap(),
                    self.row.columns[393].into_u32().copied().unwrap(),
                    self.row.columns[402].into_u32().copied().unwrap(),
                    self.row.columns[411].into_u32().copied().unwrap(),
                    self.row.columns[420].into_u32().copied().unwrap(),
                    self.row.columns[429].into_u32().copied().unwrap(),
                    self.row.columns[438].into_u32().copied().unwrap(),
                    self.row.columns[447].into_u32().copied().unwrap(),
                    self.row.columns[456].into_u32().copied().unwrap(),
                    self.row.columns[465].into_u32().copied().unwrap(),
                    self.row.columns[474].into_u32().copied().unwrap(),
                    self.row.columns[483].into_u32().copied().unwrap(),
                    self.row.columns[492].into_u32().copied().unwrap(),
                    self.row.columns[501].into_u32().copied().unwrap(),
                    self.row.columns[510].into_u32().copied().unwrap(),
                    self.row.columns[519].into_u32().copied().unwrap(),
                    self.row.columns[528].into_u32().copied().unwrap(),
                    self.row.columns[537].into_u32().copied().unwrap(),
                    self.row.columns[546].into_u32().copied().unwrap(),
                    self.row.columns[555].into_u32().copied().unwrap(),
                    self.row.columns[564].into_u32().copied().unwrap(),
                    self.row.columns[573].into_u32().copied().unwrap(),
                    self.row.columns[582].into_u32().copied().unwrap(),
                    self.row.columns[591].into_u32().copied().unwrap(),
                    self.row.columns[600].into_u32().copied().unwrap(),
                    self.row.columns[609].into_u32().copied().unwrap(),
                    self.row.columns[618].into_u32().copied().unwrap(),
                    self.row.columns[627].into_u32().copied().unwrap(),
                    self.row.columns[636].into_u32().copied().unwrap(),
                    self.row.columns[645].into_u32().copied().unwrap(),
                    self.row.columns[654].into_u32().copied().unwrap(),
                    self.row.columns[663].into_u32().copied().unwrap(),
                    self.row.columns[672].into_u32().copied().unwrap(),
                    self.row.columns[681].into_u32().copied().unwrap(),
                    self.row.columns[690].into_u32().copied().unwrap(),
                    self.row.columns[699].into_u32().copied().unwrap(),
                    self.row.columns[708].into_u32().copied().unwrap(),
                    self.row.columns[717].into_u32().copied().unwrap(),
                    self.row.columns[726].into_u32().copied().unwrap(),
                    self.row.columns[735].into_u32().copied().unwrap(),
                    self.row.columns[744].into_u32().copied().unwrap(),
                    self.row.columns[753].into_u32().copied().unwrap(),
                    self.row.columns[762].into_u32().copied().unwrap(),
                    self.row.columns[771].into_u32().copied().unwrap(),
                    self.row.columns[780].into_u32().copied().unwrap(),
                    self.row.columns[789].into_u32().copied().unwrap(),
                    self.row.columns[798].into_u32().copied().unwrap(),
                    self.row.columns[807].into_u32().copied().unwrap(),
                    self.row.columns[816].into_u32().copied().unwrap(),
                    self.row.columns[825].into_u32().copied().unwrap(),
                    self.row.columns[834].into_u32().copied().unwrap(),
                    self.row.columns[843].into_u32().copied().unwrap(),
                    self.row.columns[852].into_u32().copied().unwrap(),
                    self.row.columns[861].into_u32().copied().unwrap(),
                    self.row.columns[870].into_u32().copied().unwrap(),
                    self.row.columns[879].into_u32().copied().unwrap(),
                    self.row.columns[888].into_u32().copied().unwrap(),
                    self.row.columns[897].into_u32().copied().unwrap(),
                    self.row.columns[906].into_u32().copied().unwrap(),
                    self.row.columns[915].into_u32().copied().unwrap(),
                    self.row.columns[924].into_u32().copied().unwrap(),
                    self.row.columns[933].into_u32().copied().unwrap(),
                    self.row.columns[942].into_u32().copied().unwrap(),
                    self.row.columns[951].into_u32().copied().unwrap(),
                    self.row.columns[960].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[969].into_u32().copied().unwrap(),
                    self.row.columns[978].into_u32().copied().unwrap(),
                    self.row.columns[987].into_u32().copied().unwrap(),
                    self.row.columns[996].into_u32().copied().unwrap(),
                    self.row.columns[1005].into_u32().copied().unwrap(),
                    self.row.columns[1014].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[15].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[24].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[33].into_u8().copied().unwrap(),
                LookAt: self.row.columns[42].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1023].into_u8().copied().unwrap(),
                    self.row.columns[1032].into_u8().copied().unwrap(),
                    self.row.columns[1041].into_u8().copied().unwrap(),
                    self.row.columns[1050].into_u8().copied().unwrap(),
                    self.row.columns[1059].into_u8().copied().unwrap(),
                    self.row.columns[1068].into_u8().copied().unwrap(),
                    self.row.columns[1077].into_u8().copied().unwrap(),
                    self.row.columns[1086].into_u8().copied().unwrap(),
                    self.row.columns[1095].into_u8().copied().unwrap(),
                    self.row.columns[1104].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[7].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[52].into_u32().copied().unwrap(),
                Customize: self.row.columns[61].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[70].into_u32().copied().unwrap(),
                    self.row.columns[79].into_u32().copied().unwrap(),
                    self.row.columns[88].into_u32().copied().unwrap(),
                    self.row.columns[97].into_u32().copied().unwrap(),
                    self.row.columns[106].into_u32().copied().unwrap(),
                    self.row.columns[115].into_u32().copied().unwrap(),
                    self.row.columns[124].into_u32().copied().unwrap(),
                    self.row.columns[133].into_u32().copied().unwrap(),
                    self.row.columns[142].into_u32().copied().unwrap(),
                    self.row.columns[151].into_u32().copied().unwrap(),
                    self.row.columns[160].into_u32().copied().unwrap(),
                    self.row.columns[169].into_u32().copied().unwrap(),
                    self.row.columns[178].into_u32().copied().unwrap(),
                    self.row.columns[187].into_u32().copied().unwrap(),
                    self.row.columns[196].into_u32().copied().unwrap(),
                    self.row.columns[205].into_u32().copied().unwrap(),
                    self.row.columns[214].into_u32().copied().unwrap(),
                    self.row.columns[223].into_u32().copied().unwrap(),
                    self.row.columns[232].into_u32().copied().unwrap(),
                    self.row.columns[241].into_u32().copied().unwrap(),
                    self.row.columns[250].into_u32().copied().unwrap(),
                    self.row.columns[259].into_u32().copied().unwrap(),
                    self.row.columns[268].into_u32().copied().unwrap(),
                    self.row.columns[277].into_u32().copied().unwrap(),
                    self.row.columns[286].into_u32().copied().unwrap(),
                    self.row.columns[295].into_u32().copied().unwrap(),
                    self.row.columns[304].into_u32().copied().unwrap(),
                    self.row.columns[313].into_u32().copied().unwrap(),
                    self.row.columns[322].into_u32().copied().unwrap(),
                    self.row.columns[331].into_u32().copied().unwrap(),
                    self.row.columns[340].into_u32().copied().unwrap(),
                    self.row.columns[349].into_u32().copied().unwrap(),
                    self.row.columns[358].into_u32().copied().unwrap(),
                    self.row.columns[367].into_u32().copied().unwrap(),
                    self.row.columns[376].into_u32().copied().unwrap(),
                    self.row.columns[385].into_u32().copied().unwrap(),
                    self.row.columns[394].into_u32().copied().unwrap(),
                    self.row.columns[403].into_u32().copied().unwrap(),
                    self.row.columns[412].into_u32().copied().unwrap(),
                    self.row.columns[421].into_u32().copied().unwrap(),
                    self.row.columns[430].into_u32().copied().unwrap(),
                    self.row.columns[439].into_u32().copied().unwrap(),
                    self.row.columns[448].into_u32().copied().unwrap(),
                    self.row.columns[457].into_u32().copied().unwrap(),
                    self.row.columns[466].into_u32().copied().unwrap(),
                    self.row.columns[475].into_u32().copied().unwrap(),
                    self.row.columns[484].into_u32().copied().unwrap(),
                    self.row.columns[493].into_u32().copied().unwrap(),
                    self.row.columns[502].into_u32().copied().unwrap(),
                    self.row.columns[511].into_u32().copied().unwrap(),
                    self.row.columns[520].into_u32().copied().unwrap(),
                    self.row.columns[529].into_u32().copied().unwrap(),
                    self.row.columns[538].into_u32().copied().unwrap(),
                    self.row.columns[547].into_u32().copied().unwrap(),
                    self.row.columns[556].into_u32().copied().unwrap(),
                    self.row.columns[565].into_u32().copied().unwrap(),
                    self.row.columns[574].into_u32().copied().unwrap(),
                    self.row.columns[583].into_u32().copied().unwrap(),
                    self.row.columns[592].into_u32().copied().unwrap(),
                    self.row.columns[601].into_u32().copied().unwrap(),
                    self.row.columns[610].into_u32().copied().unwrap(),
                    self.row.columns[619].into_u32().copied().unwrap(),
                    self.row.columns[628].into_u32().copied().unwrap(),
                    self.row.columns[637].into_u32().copied().unwrap(),
                    self.row.columns[646].into_u32().copied().unwrap(),
                    self.row.columns[655].into_u32().copied().unwrap(),
                    self.row.columns[664].into_u32().copied().unwrap(),
                    self.row.columns[673].into_u32().copied().unwrap(),
                    self.row.columns[682].into_u32().copied().unwrap(),
                    self.row.columns[691].into_u32().copied().unwrap(),
                    self.row.columns[700].into_u32().copied().unwrap(),
                    self.row.columns[709].into_u32().copied().unwrap(),
                    self.row.columns[718].into_u32().copied().unwrap(),
                    self.row.columns[727].into_u32().copied().unwrap(),
                    self.row.columns[736].into_u32().copied().unwrap(),
                    self.row.columns[745].into_u32().copied().unwrap(),
                    self.row.columns[754].into_u32().copied().unwrap(),
                    self.row.columns[763].into_u32().copied().unwrap(),
                    self.row.columns[772].into_u32().copied().unwrap(),
                    self.row.columns[781].into_u32().copied().unwrap(),
                    self.row.columns[790].into_u32().copied().unwrap(),
                    self.row.columns[799].into_u32().copied().unwrap(),
                    self.row.columns[808].into_u32().copied().unwrap(),
                    self.row.columns[817].into_u32().copied().unwrap(),
                    self.row.columns[826].into_u32().copied().unwrap(),
                    self.row.columns[835].into_u32().copied().unwrap(),
                    self.row.columns[844].into_u32().copied().unwrap(),
                    self.row.columns[853].into_u32().copied().unwrap(),
                    self.row.columns[862].into_u32().copied().unwrap(),
                    self.row.columns[871].into_u32().copied().unwrap(),
                    self.row.columns[880].into_u32().copied().unwrap(),
                    self.row.columns[889].into_u32().copied().unwrap(),
                    self.row.columns[898].into_u32().copied().unwrap(),
                    self.row.columns[907].into_u32().copied().unwrap(),
                    self.row.columns[916].into_u32().copied().unwrap(),
                    self.row.columns[925].into_u32().copied().unwrap(),
                    self.row.columns[934].into_u32().copied().unwrap(),
                    self.row.columns[943].into_u32().copied().unwrap(),
                    self.row.columns[952].into_u32().copied().unwrap(),
                    self.row.columns[961].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[970].into_u32().copied().unwrap(),
                    self.row.columns[979].into_u32().copied().unwrap(),
                    self.row.columns[988].into_u32().copied().unwrap(),
                    self.row.columns[997].into_u32().copied().unwrap(),
                    self.row.columns[1006].into_u32().copied().unwrap(),
                    self.row.columns[1015].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[16].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[25].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[34].into_u8().copied().unwrap(),
                LookAt: self.row.columns[43].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1024].into_u8().copied().unwrap(),
                    self.row.columns[1033].into_u8().copied().unwrap(),
                    self.row.columns[1042].into_u8().copied().unwrap(),
                    self.row.columns[1051].into_u8().copied().unwrap(),
                    self.row.columns[1060].into_u8().copied().unwrap(),
                    self.row.columns[1069].into_u8().copied().unwrap(),
                    self.row.columns[1078].into_u8().copied().unwrap(),
                    self.row.columns[1087].into_u8().copied().unwrap(),
                    self.row.columns[1096].into_u8().copied().unwrap(),
                    self.row.columns[1105].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[8].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[53].into_u32().copied().unwrap(),
                Customize: self.row.columns[62].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[71].into_u32().copied().unwrap(),
                    self.row.columns[80].into_u32().copied().unwrap(),
                    self.row.columns[89].into_u32().copied().unwrap(),
                    self.row.columns[98].into_u32().copied().unwrap(),
                    self.row.columns[107].into_u32().copied().unwrap(),
                    self.row.columns[116].into_u32().copied().unwrap(),
                    self.row.columns[125].into_u32().copied().unwrap(),
                    self.row.columns[134].into_u32().copied().unwrap(),
                    self.row.columns[143].into_u32().copied().unwrap(),
                    self.row.columns[152].into_u32().copied().unwrap(),
                    self.row.columns[161].into_u32().copied().unwrap(),
                    self.row.columns[170].into_u32().copied().unwrap(),
                    self.row.columns[179].into_u32().copied().unwrap(),
                    self.row.columns[188].into_u32().copied().unwrap(),
                    self.row.columns[197].into_u32().copied().unwrap(),
                    self.row.columns[206].into_u32().copied().unwrap(),
                    self.row.columns[215].into_u32().copied().unwrap(),
                    self.row.columns[224].into_u32().copied().unwrap(),
                    self.row.columns[233].into_u32().copied().unwrap(),
                    self.row.columns[242].into_u32().copied().unwrap(),
                    self.row.columns[251].into_u32().copied().unwrap(),
                    self.row.columns[260].into_u32().copied().unwrap(),
                    self.row.columns[269].into_u32().copied().unwrap(),
                    self.row.columns[278].into_u32().copied().unwrap(),
                    self.row.columns[287].into_u32().copied().unwrap(),
                    self.row.columns[296].into_u32().copied().unwrap(),
                    self.row.columns[305].into_u32().copied().unwrap(),
                    self.row.columns[314].into_u32().copied().unwrap(),
                    self.row.columns[323].into_u32().copied().unwrap(),
                    self.row.columns[332].into_u32().copied().unwrap(),
                    self.row.columns[341].into_u32().copied().unwrap(),
                    self.row.columns[350].into_u32().copied().unwrap(),
                    self.row.columns[359].into_u32().copied().unwrap(),
                    self.row.columns[368].into_u32().copied().unwrap(),
                    self.row.columns[377].into_u32().copied().unwrap(),
                    self.row.columns[386].into_u32().copied().unwrap(),
                    self.row.columns[395].into_u32().copied().unwrap(),
                    self.row.columns[404].into_u32().copied().unwrap(),
                    self.row.columns[413].into_u32().copied().unwrap(),
                    self.row.columns[422].into_u32().copied().unwrap(),
                    self.row.columns[431].into_u32().copied().unwrap(),
                    self.row.columns[440].into_u32().copied().unwrap(),
                    self.row.columns[449].into_u32().copied().unwrap(),
                    self.row.columns[458].into_u32().copied().unwrap(),
                    self.row.columns[467].into_u32().copied().unwrap(),
                    self.row.columns[476].into_u32().copied().unwrap(),
                    self.row.columns[485].into_u32().copied().unwrap(),
                    self.row.columns[494].into_u32().copied().unwrap(),
                    self.row.columns[503].into_u32().copied().unwrap(),
                    self.row.columns[512].into_u32().copied().unwrap(),
                    self.row.columns[521].into_u32().copied().unwrap(),
                    self.row.columns[530].into_u32().copied().unwrap(),
                    self.row.columns[539].into_u32().copied().unwrap(),
                    self.row.columns[548].into_u32().copied().unwrap(),
                    self.row.columns[557].into_u32().copied().unwrap(),
                    self.row.columns[566].into_u32().copied().unwrap(),
                    self.row.columns[575].into_u32().copied().unwrap(),
                    self.row.columns[584].into_u32().copied().unwrap(),
                    self.row.columns[593].into_u32().copied().unwrap(),
                    self.row.columns[602].into_u32().copied().unwrap(),
                    self.row.columns[611].into_u32().copied().unwrap(),
                    self.row.columns[620].into_u32().copied().unwrap(),
                    self.row.columns[629].into_u32().copied().unwrap(),
                    self.row.columns[638].into_u32().copied().unwrap(),
                    self.row.columns[647].into_u32().copied().unwrap(),
                    self.row.columns[656].into_u32().copied().unwrap(),
                    self.row.columns[665].into_u32().copied().unwrap(),
                    self.row.columns[674].into_u32().copied().unwrap(),
                    self.row.columns[683].into_u32().copied().unwrap(),
                    self.row.columns[692].into_u32().copied().unwrap(),
                    self.row.columns[701].into_u32().copied().unwrap(),
                    self.row.columns[710].into_u32().copied().unwrap(),
                    self.row.columns[719].into_u32().copied().unwrap(),
                    self.row.columns[728].into_u32().copied().unwrap(),
                    self.row.columns[737].into_u32().copied().unwrap(),
                    self.row.columns[746].into_u32().copied().unwrap(),
                    self.row.columns[755].into_u32().copied().unwrap(),
                    self.row.columns[764].into_u32().copied().unwrap(),
                    self.row.columns[773].into_u32().copied().unwrap(),
                    self.row.columns[782].into_u32().copied().unwrap(),
                    self.row.columns[791].into_u32().copied().unwrap(),
                    self.row.columns[800].into_u32().copied().unwrap(),
                    self.row.columns[809].into_u32().copied().unwrap(),
                    self.row.columns[818].into_u32().copied().unwrap(),
                    self.row.columns[827].into_u32().copied().unwrap(),
                    self.row.columns[836].into_u32().copied().unwrap(),
                    self.row.columns[845].into_u32().copied().unwrap(),
                    self.row.columns[854].into_u32().copied().unwrap(),
                    self.row.columns[863].into_u32().copied().unwrap(),
                    self.row.columns[872].into_u32().copied().unwrap(),
                    self.row.columns[881].into_u32().copied().unwrap(),
                    self.row.columns[890].into_u32().copied().unwrap(),
                    self.row.columns[899].into_u32().copied().unwrap(),
                    self.row.columns[908].into_u32().copied().unwrap(),
                    self.row.columns[917].into_u32().copied().unwrap(),
                    self.row.columns[926].into_u32().copied().unwrap(),
                    self.row.columns[935].into_u32().copied().unwrap(),
                    self.row.columns[944].into_u32().copied().unwrap(),
                    self.row.columns[953].into_u32().copied().unwrap(),
                    self.row.columns[962].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[971].into_u32().copied().unwrap(),
                    self.row.columns[980].into_u32().copied().unwrap(),
                    self.row.columns[989].into_u32().copied().unwrap(),
                    self.row.columns[998].into_u32().copied().unwrap(),
                    self.row.columns[1007].into_u32().copied().unwrap(),
                    self.row.columns[1016].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[17].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[26].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[35].into_u8().copied().unwrap(),
                LookAt: self.row.columns[44].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1025].into_u8().copied().unwrap(),
                    self.row.columns[1034].into_u8().copied().unwrap(),
                    self.row.columns[1043].into_u8().copied().unwrap(),
                    self.row.columns[1052].into_u8().copied().unwrap(),
                    self.row.columns[1061].into_u8().copied().unwrap(),
                    self.row.columns[1070].into_u8().copied().unwrap(),
                    self.row.columns[1079].into_u8().copied().unwrap(),
                    self.row.columns[1088].into_u8().copied().unwrap(),
                    self.row.columns[1097].into_u8().copied().unwrap(),
                    self.row.columns[1106].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[9].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[54].into_u32().copied().unwrap(),
                Customize: self.row.columns[63].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[72].into_u32().copied().unwrap(),
                    self.row.columns[81].into_u32().copied().unwrap(),
                    self.row.columns[90].into_u32().copied().unwrap(),
                    self.row.columns[99].into_u32().copied().unwrap(),
                    self.row.columns[108].into_u32().copied().unwrap(),
                    self.row.columns[117].into_u32().copied().unwrap(),
                    self.row.columns[126].into_u32().copied().unwrap(),
                    self.row.columns[135].into_u32().copied().unwrap(),
                    self.row.columns[144].into_u32().copied().unwrap(),
                    self.row.columns[153].into_u32().copied().unwrap(),
                    self.row.columns[162].into_u32().copied().unwrap(),
                    self.row.columns[171].into_u32().copied().unwrap(),
                    self.row.columns[180].into_u32().copied().unwrap(),
                    self.row.columns[189].into_u32().copied().unwrap(),
                    self.row.columns[198].into_u32().copied().unwrap(),
                    self.row.columns[207].into_u32().copied().unwrap(),
                    self.row.columns[216].into_u32().copied().unwrap(),
                    self.row.columns[225].into_u32().copied().unwrap(),
                    self.row.columns[234].into_u32().copied().unwrap(),
                    self.row.columns[243].into_u32().copied().unwrap(),
                    self.row.columns[252].into_u32().copied().unwrap(),
                    self.row.columns[261].into_u32().copied().unwrap(),
                    self.row.columns[270].into_u32().copied().unwrap(),
                    self.row.columns[279].into_u32().copied().unwrap(),
                    self.row.columns[288].into_u32().copied().unwrap(),
                    self.row.columns[297].into_u32().copied().unwrap(),
                    self.row.columns[306].into_u32().copied().unwrap(),
                    self.row.columns[315].into_u32().copied().unwrap(),
                    self.row.columns[324].into_u32().copied().unwrap(),
                    self.row.columns[333].into_u32().copied().unwrap(),
                    self.row.columns[342].into_u32().copied().unwrap(),
                    self.row.columns[351].into_u32().copied().unwrap(),
                    self.row.columns[360].into_u32().copied().unwrap(),
                    self.row.columns[369].into_u32().copied().unwrap(),
                    self.row.columns[378].into_u32().copied().unwrap(),
                    self.row.columns[387].into_u32().copied().unwrap(),
                    self.row.columns[396].into_u32().copied().unwrap(),
                    self.row.columns[405].into_u32().copied().unwrap(),
                    self.row.columns[414].into_u32().copied().unwrap(),
                    self.row.columns[423].into_u32().copied().unwrap(),
                    self.row.columns[432].into_u32().copied().unwrap(),
                    self.row.columns[441].into_u32().copied().unwrap(),
                    self.row.columns[450].into_u32().copied().unwrap(),
                    self.row.columns[459].into_u32().copied().unwrap(),
                    self.row.columns[468].into_u32().copied().unwrap(),
                    self.row.columns[477].into_u32().copied().unwrap(),
                    self.row.columns[486].into_u32().copied().unwrap(),
                    self.row.columns[495].into_u32().copied().unwrap(),
                    self.row.columns[504].into_u32().copied().unwrap(),
                    self.row.columns[513].into_u32().copied().unwrap(),
                    self.row.columns[522].into_u32().copied().unwrap(),
                    self.row.columns[531].into_u32().copied().unwrap(),
                    self.row.columns[540].into_u32().copied().unwrap(),
                    self.row.columns[549].into_u32().copied().unwrap(),
                    self.row.columns[558].into_u32().copied().unwrap(),
                    self.row.columns[567].into_u32().copied().unwrap(),
                    self.row.columns[576].into_u32().copied().unwrap(),
                    self.row.columns[585].into_u32().copied().unwrap(),
                    self.row.columns[594].into_u32().copied().unwrap(),
                    self.row.columns[603].into_u32().copied().unwrap(),
                    self.row.columns[612].into_u32().copied().unwrap(),
                    self.row.columns[621].into_u32().copied().unwrap(),
                    self.row.columns[630].into_u32().copied().unwrap(),
                    self.row.columns[639].into_u32().copied().unwrap(),
                    self.row.columns[648].into_u32().copied().unwrap(),
                    self.row.columns[657].into_u32().copied().unwrap(),
                    self.row.columns[666].into_u32().copied().unwrap(),
                    self.row.columns[675].into_u32().copied().unwrap(),
                    self.row.columns[684].into_u32().copied().unwrap(),
                    self.row.columns[693].into_u32().copied().unwrap(),
                    self.row.columns[702].into_u32().copied().unwrap(),
                    self.row.columns[711].into_u32().copied().unwrap(),
                    self.row.columns[720].into_u32().copied().unwrap(),
                    self.row.columns[729].into_u32().copied().unwrap(),
                    self.row.columns[738].into_u32().copied().unwrap(),
                    self.row.columns[747].into_u32().copied().unwrap(),
                    self.row.columns[756].into_u32().copied().unwrap(),
                    self.row.columns[765].into_u32().copied().unwrap(),
                    self.row.columns[774].into_u32().copied().unwrap(),
                    self.row.columns[783].into_u32().copied().unwrap(),
                    self.row.columns[792].into_u32().copied().unwrap(),
                    self.row.columns[801].into_u32().copied().unwrap(),
                    self.row.columns[810].into_u32().copied().unwrap(),
                    self.row.columns[819].into_u32().copied().unwrap(),
                    self.row.columns[828].into_u32().copied().unwrap(),
                    self.row.columns[837].into_u32().copied().unwrap(),
                    self.row.columns[846].into_u32().copied().unwrap(),
                    self.row.columns[855].into_u32().copied().unwrap(),
                    self.row.columns[864].into_u32().copied().unwrap(),
                    self.row.columns[873].into_u32().copied().unwrap(),
                    self.row.columns[882].into_u32().copied().unwrap(),
                    self.row.columns[891].into_u32().copied().unwrap(),
                    self.row.columns[900].into_u32().copied().unwrap(),
                    self.row.columns[909].into_u32().copied().unwrap(),
                    self.row.columns[918].into_u32().copied().unwrap(),
                    self.row.columns[927].into_u32().copied().unwrap(),
                    self.row.columns[936].into_u32().copied().unwrap(),
                    self.row.columns[945].into_u32().copied().unwrap(),
                    self.row.columns[954].into_u32().copied().unwrap(),
                    self.row.columns[963].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[972].into_u32().copied().unwrap(),
                    self.row.columns[981].into_u32().copied().unwrap(),
                    self.row.columns[990].into_u32().copied().unwrap(),
                    self.row.columns[999].into_u32().copied().unwrap(),
                    self.row.columns[1008].into_u32().copied().unwrap(),
                    self.row.columns[1017].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[18].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[27].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[36].into_u8().copied().unwrap(),
                LookAt: self.row.columns[45].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1026].into_u8().copied().unwrap(),
                    self.row.columns[1035].into_u8().copied().unwrap(),
                    self.row.columns[1044].into_u8().copied().unwrap(),
                    self.row.columns[1053].into_u8().copied().unwrap(),
                    self.row.columns[1062].into_u8().copied().unwrap(),
                    self.row.columns[1071].into_u8().copied().unwrap(),
                    self.row.columns[1080].into_u8().copied().unwrap(),
                    self.row.columns[1089].into_u8().copied().unwrap(),
                    self.row.columns[1098].into_u8().copied().unwrap(),
                    self.row.columns[1107].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[10].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[55].into_u32().copied().unwrap(),
                Customize: self.row.columns[64].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[73].into_u32().copied().unwrap(),
                    self.row.columns[82].into_u32().copied().unwrap(),
                    self.row.columns[91].into_u32().copied().unwrap(),
                    self.row.columns[100].into_u32().copied().unwrap(),
                    self.row.columns[109].into_u32().copied().unwrap(),
                    self.row.columns[118].into_u32().copied().unwrap(),
                    self.row.columns[127].into_u32().copied().unwrap(),
                    self.row.columns[136].into_u32().copied().unwrap(),
                    self.row.columns[145].into_u32().copied().unwrap(),
                    self.row.columns[154].into_u32().copied().unwrap(),
                    self.row.columns[163].into_u32().copied().unwrap(),
                    self.row.columns[172].into_u32().copied().unwrap(),
                    self.row.columns[181].into_u32().copied().unwrap(),
                    self.row.columns[190].into_u32().copied().unwrap(),
                    self.row.columns[199].into_u32().copied().unwrap(),
                    self.row.columns[208].into_u32().copied().unwrap(),
                    self.row.columns[217].into_u32().copied().unwrap(),
                    self.row.columns[226].into_u32().copied().unwrap(),
                    self.row.columns[235].into_u32().copied().unwrap(),
                    self.row.columns[244].into_u32().copied().unwrap(),
                    self.row.columns[253].into_u32().copied().unwrap(),
                    self.row.columns[262].into_u32().copied().unwrap(),
                    self.row.columns[271].into_u32().copied().unwrap(),
                    self.row.columns[280].into_u32().copied().unwrap(),
                    self.row.columns[289].into_u32().copied().unwrap(),
                    self.row.columns[298].into_u32().copied().unwrap(),
                    self.row.columns[307].into_u32().copied().unwrap(),
                    self.row.columns[316].into_u32().copied().unwrap(),
                    self.row.columns[325].into_u32().copied().unwrap(),
                    self.row.columns[334].into_u32().copied().unwrap(),
                    self.row.columns[343].into_u32().copied().unwrap(),
                    self.row.columns[352].into_u32().copied().unwrap(),
                    self.row.columns[361].into_u32().copied().unwrap(),
                    self.row.columns[370].into_u32().copied().unwrap(),
                    self.row.columns[379].into_u32().copied().unwrap(),
                    self.row.columns[388].into_u32().copied().unwrap(),
                    self.row.columns[397].into_u32().copied().unwrap(),
                    self.row.columns[406].into_u32().copied().unwrap(),
                    self.row.columns[415].into_u32().copied().unwrap(),
                    self.row.columns[424].into_u32().copied().unwrap(),
                    self.row.columns[433].into_u32().copied().unwrap(),
                    self.row.columns[442].into_u32().copied().unwrap(),
                    self.row.columns[451].into_u32().copied().unwrap(),
                    self.row.columns[460].into_u32().copied().unwrap(),
                    self.row.columns[469].into_u32().copied().unwrap(),
                    self.row.columns[478].into_u32().copied().unwrap(),
                    self.row.columns[487].into_u32().copied().unwrap(),
                    self.row.columns[496].into_u32().copied().unwrap(),
                    self.row.columns[505].into_u32().copied().unwrap(),
                    self.row.columns[514].into_u32().copied().unwrap(),
                    self.row.columns[523].into_u32().copied().unwrap(),
                    self.row.columns[532].into_u32().copied().unwrap(),
                    self.row.columns[541].into_u32().copied().unwrap(),
                    self.row.columns[550].into_u32().copied().unwrap(),
                    self.row.columns[559].into_u32().copied().unwrap(),
                    self.row.columns[568].into_u32().copied().unwrap(),
                    self.row.columns[577].into_u32().copied().unwrap(),
                    self.row.columns[586].into_u32().copied().unwrap(),
                    self.row.columns[595].into_u32().copied().unwrap(),
                    self.row.columns[604].into_u32().copied().unwrap(),
                    self.row.columns[613].into_u32().copied().unwrap(),
                    self.row.columns[622].into_u32().copied().unwrap(),
                    self.row.columns[631].into_u32().copied().unwrap(),
                    self.row.columns[640].into_u32().copied().unwrap(),
                    self.row.columns[649].into_u32().copied().unwrap(),
                    self.row.columns[658].into_u32().copied().unwrap(),
                    self.row.columns[667].into_u32().copied().unwrap(),
                    self.row.columns[676].into_u32().copied().unwrap(),
                    self.row.columns[685].into_u32().copied().unwrap(),
                    self.row.columns[694].into_u32().copied().unwrap(),
                    self.row.columns[703].into_u32().copied().unwrap(),
                    self.row.columns[712].into_u32().copied().unwrap(),
                    self.row.columns[721].into_u32().copied().unwrap(),
                    self.row.columns[730].into_u32().copied().unwrap(),
                    self.row.columns[739].into_u32().copied().unwrap(),
                    self.row.columns[748].into_u32().copied().unwrap(),
                    self.row.columns[757].into_u32().copied().unwrap(),
                    self.row.columns[766].into_u32().copied().unwrap(),
                    self.row.columns[775].into_u32().copied().unwrap(),
                    self.row.columns[784].into_u32().copied().unwrap(),
                    self.row.columns[793].into_u32().copied().unwrap(),
                    self.row.columns[802].into_u32().copied().unwrap(),
                    self.row.columns[811].into_u32().copied().unwrap(),
                    self.row.columns[820].into_u32().copied().unwrap(),
                    self.row.columns[829].into_u32().copied().unwrap(),
                    self.row.columns[838].into_u32().copied().unwrap(),
                    self.row.columns[847].into_u32().copied().unwrap(),
                    self.row.columns[856].into_u32().copied().unwrap(),
                    self.row.columns[865].into_u32().copied().unwrap(),
                    self.row.columns[874].into_u32().copied().unwrap(),
                    self.row.columns[883].into_u32().copied().unwrap(),
                    self.row.columns[892].into_u32().copied().unwrap(),
                    self.row.columns[901].into_u32().copied().unwrap(),
                    self.row.columns[910].into_u32().copied().unwrap(),
                    self.row.columns[919].into_u32().copied().unwrap(),
                    self.row.columns[928].into_u32().copied().unwrap(),
                    self.row.columns[937].into_u32().copied().unwrap(),
                    self.row.columns[946].into_u32().copied().unwrap(),
                    self.row.columns[955].into_u32().copied().unwrap(),
                    self.row.columns[964].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[973].into_u32().copied().unwrap(),
                    self.row.columns[982].into_u32().copied().unwrap(),
                    self.row.columns[991].into_u32().copied().unwrap(),
                    self.row.columns[1000].into_u32().copied().unwrap(),
                    self.row.columns[1009].into_u32().copied().unwrap(),
                    self.row.columns[1018].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[19].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[28].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[37].into_u8().copied().unwrap(),
                LookAt: self.row.columns[46].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1027].into_u8().copied().unwrap(),
                    self.row.columns[1036].into_u8().copied().unwrap(),
                    self.row.columns[1045].into_u8().copied().unwrap(),
                    self.row.columns[1054].into_u8().copied().unwrap(),
                    self.row.columns[1063].into_u8().copied().unwrap(),
                    self.row.columns[1072].into_u8().copied().unwrap(),
                    self.row.columns[1081].into_u8().copied().unwrap(),
                    self.row.columns[1090].into_u8().copied().unwrap(),
                    self.row.columns[1099].into_u8().copied().unwrap(),
                    self.row.columns[1108].into_u8().copied().unwrap(),
                ],
            },
            CharaMakeStructElement {
                Menu: self.row.columns[11].into_u32().copied().unwrap(),
                SubMenuMask: self.row.columns[56].into_u32().copied().unwrap(),
                Customize: self.row.columns[65].into_u32().copied().unwrap(),
                SubMenuParam: [
                    self.row.columns[74].into_u32().copied().unwrap(),
                    self.row.columns[83].into_u32().copied().unwrap(),
                    self.row.columns[92].into_u32().copied().unwrap(),
                    self.row.columns[101].into_u32().copied().unwrap(),
                    self.row.columns[110].into_u32().copied().unwrap(),
                    self.row.columns[119].into_u32().copied().unwrap(),
                    self.row.columns[128].into_u32().copied().unwrap(),
                    self.row.columns[137].into_u32().copied().unwrap(),
                    self.row.columns[146].into_u32().copied().unwrap(),
                    self.row.columns[155].into_u32().copied().unwrap(),
                    self.row.columns[164].into_u32().copied().unwrap(),
                    self.row.columns[173].into_u32().copied().unwrap(),
                    self.row.columns[182].into_u32().copied().unwrap(),
                    self.row.columns[191].into_u32().copied().unwrap(),
                    self.row.columns[200].into_u32().copied().unwrap(),
                    self.row.columns[209].into_u32().copied().unwrap(),
                    self.row.columns[218].into_u32().copied().unwrap(),
                    self.row.columns[227].into_u32().copied().unwrap(),
                    self.row.columns[236].into_u32().copied().unwrap(),
                    self.row.columns[245].into_u32().copied().unwrap(),
                    self.row.columns[254].into_u32().copied().unwrap(),
                    self.row.columns[263].into_u32().copied().unwrap(),
                    self.row.columns[272].into_u32().copied().unwrap(),
                    self.row.columns[281].into_u32().copied().unwrap(),
                    self.row.columns[290].into_u32().copied().unwrap(),
                    self.row.columns[299].into_u32().copied().unwrap(),
                    self.row.columns[308].into_u32().copied().unwrap(),
                    self.row.columns[317].into_u32().copied().unwrap(),
                    self.row.columns[326].into_u32().copied().unwrap(),
                    self.row.columns[335].into_u32().copied().unwrap(),
                    self.row.columns[344].into_u32().copied().unwrap(),
                    self.row.columns[353].into_u32().copied().unwrap(),
                    self.row.columns[362].into_u32().copied().unwrap(),
                    self.row.columns[371].into_u32().copied().unwrap(),
                    self.row.columns[380].into_u32().copied().unwrap(),
                    self.row.columns[389].into_u32().copied().unwrap(),
                    self.row.columns[398].into_u32().copied().unwrap(),
                    self.row.columns[407].into_u32().copied().unwrap(),
                    self.row.columns[416].into_u32().copied().unwrap(),
                    self.row.columns[425].into_u32().copied().unwrap(),
                    self.row.columns[434].into_u32().copied().unwrap(),
                    self.row.columns[443].into_u32().copied().unwrap(),
                    self.row.columns[452].into_u32().copied().unwrap(),
                    self.row.columns[461].into_u32().copied().unwrap(),
                    self.row.columns[470].into_u32().copied().unwrap(),
                    self.row.columns[479].into_u32().copied().unwrap(),
                    self.row.columns[488].into_u32().copied().unwrap(),
                    self.row.columns[497].into_u32().copied().unwrap(),
                    self.row.columns[506].into_u32().copied().unwrap(),
                    self.row.columns[515].into_u32().copied().unwrap(),
                    self.row.columns[524].into_u32().copied().unwrap(),
                    self.row.columns[533].into_u32().copied().unwrap(),
                    self.row.columns[542].into_u32().copied().unwrap(),
                    self.row.columns[551].into_u32().copied().unwrap(),
                    self.row.columns[560].into_u32().copied().unwrap(),
                    self.row.columns[569].into_u32().copied().unwrap(),
                    self.row.columns[578].into_u32().copied().unwrap(),
                    self.row.columns[587].into_u32().copied().unwrap(),
                    self.row.columns[596].into_u32().copied().unwrap(),
                    self.row.columns[605].into_u32().copied().unwrap(),
                    self.row.columns[614].into_u32().copied().unwrap(),
                    self.row.columns[623].into_u32().copied().unwrap(),
                    self.row.columns[632].into_u32().copied().unwrap(),
                    self.row.columns[641].into_u32().copied().unwrap(),
                    self.row.columns[650].into_u32().copied().unwrap(),
                    self.row.columns[659].into_u32().copied().unwrap(),
                    self.row.columns[668].into_u32().copied().unwrap(),
                    self.row.columns[677].into_u32().copied().unwrap(),
                    self.row.columns[686].into_u32().copied().unwrap(),
                    self.row.columns[695].into_u32().copied().unwrap(),
                    self.row.columns[704].into_u32().copied().unwrap(),
                    self.row.columns[713].into_u32().copied().unwrap(),
                    self.row.columns[722].into_u32().copied().unwrap(),
                    self.row.columns[731].into_u32().copied().unwrap(),
                    self.row.columns[740].into_u32().copied().unwrap(),
                    self.row.columns[749].into_u32().copied().unwrap(),
                    self.row.columns[758].into_u32().copied().unwrap(),
                    self.row.columns[767].into_u32().copied().unwrap(),
                    self.row.columns[776].into_u32().copied().unwrap(),
                    self.row.columns[785].into_u32().copied().unwrap(),
                    self.row.columns[794].into_u32().copied().unwrap(),
                    self.row.columns[803].into_u32().copied().unwrap(),
                    self.row.columns[812].into_u32().copied().unwrap(),
                    self.row.columns[821].into_u32().copied().unwrap(),
                    self.row.columns[830].into_u32().copied().unwrap(),
                    self.row.columns[839].into_u32().copied().unwrap(),
                    self.row.columns[848].into_u32().copied().unwrap(),
                    self.row.columns[857].into_u32().copied().unwrap(),
                    self.row.columns[866].into_u32().copied().unwrap(),
                    self.row.columns[875].into_u32().copied().unwrap(),
                    self.row.columns[884].into_u32().copied().unwrap(),
                    self.row.columns[893].into_u32().copied().unwrap(),
                    self.row.columns[902].into_u32().copied().unwrap(),
                    self.row.columns[911].into_u32().copied().unwrap(),
                    self.row.columns[920].into_u32().copied().unwrap(),
                    self.row.columns[929].into_u32().copied().unwrap(),
                    self.row.columns[938].into_u32().copied().unwrap(),
                    self.row.columns[947].into_u32().copied().unwrap(),
                    self.row.columns[956].into_u32().copied().unwrap(),
                    self.row.columns[965].into_u32().copied().unwrap(),
                ],
                Unknown0: [
                    self.row.columns[974].into_u32().copied().unwrap(),
                    self.row.columns[983].into_u32().copied().unwrap(),
                    self.row.columns[992].into_u32().copied().unwrap(),
                    self.row.columns[1001].into_u32().copied().unwrap(),
                    self.row.columns[1010].into_u32().copied().unwrap(),
                    self.row.columns[1019].into_u32().copied().unwrap(),
                ],
                InitVal: self.row.columns[20].into_u8().copied().unwrap(),
                SubMenuType: self.row.columns[29].into_u8().copied().unwrap(),
                SubMenuNum: self.row.columns[38].into_u8().copied().unwrap(),
                LookAt: self.row.columns[47].into_u8().copied().unwrap(),
                SubMenuGraphic: [
                    self.row.columns[1028].into_u8().copied().unwrap(),
                    self.row.columns[1037].into_u8().copied().unwrap(),
                    self.row.columns[1046].into_u8().copied().unwrap(),
                    self.row.columns[1055].into_u8().copied().unwrap(),
                    self.row.columns[1064].into_u8().copied().unwrap(),
                    self.row.columns[1073].into_u8().copied().unwrap(),
                    self.row.columns[1082].into_u8().copied().unwrap(),
                    self.row.columns[1091].into_u8().copied().unwrap(),
                    self.row.columns[1100].into_u8().copied().unwrap(),
                    self.row.columns[1109].into_u8().copied().unwrap(),
                ],
            },
        ]
    }
    pub fn FacialFeatureOption(&'a self) -> [FacialFeatureOptionElement; 8] {
        [
            FacialFeatureOptionElement {
                Option1: self.row.columns[1110].into_i32().copied().unwrap(),
                Option2: self.row.columns[1118].into_i32().copied().unwrap(),
                Option3: self.row.columns[1126].into_i32().copied().unwrap(),
                Option4: self.row.columns[1134].into_i32().copied().unwrap(),
                Option5: self.row.columns[1142].into_i32().copied().unwrap(),
                Option6: self.row.columns[1150].into_i32().copied().unwrap(),
                Option7: self.row.columns[1158].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1111].into_i32().copied().unwrap(),
                Option2: self.row.columns[1119].into_i32().copied().unwrap(),
                Option3: self.row.columns[1127].into_i32().copied().unwrap(),
                Option4: self.row.columns[1135].into_i32().copied().unwrap(),
                Option5: self.row.columns[1143].into_i32().copied().unwrap(),
                Option6: self.row.columns[1151].into_i32().copied().unwrap(),
                Option7: self.row.columns[1159].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1112].into_i32().copied().unwrap(),
                Option2: self.row.columns[1120].into_i32().copied().unwrap(),
                Option3: self.row.columns[1128].into_i32().copied().unwrap(),
                Option4: self.row.columns[1136].into_i32().copied().unwrap(),
                Option5: self.row.columns[1144].into_i32().copied().unwrap(),
                Option6: self.row.columns[1152].into_i32().copied().unwrap(),
                Option7: self.row.columns[1160].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1113].into_i32().copied().unwrap(),
                Option2: self.row.columns[1121].into_i32().copied().unwrap(),
                Option3: self.row.columns[1129].into_i32().copied().unwrap(),
                Option4: self.row.columns[1137].into_i32().copied().unwrap(),
                Option5: self.row.columns[1145].into_i32().copied().unwrap(),
                Option6: self.row.columns[1153].into_i32().copied().unwrap(),
                Option7: self.row.columns[1161].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1114].into_i32().copied().unwrap(),
                Option2: self.row.columns[1122].into_i32().copied().unwrap(),
                Option3: self.row.columns[1130].into_i32().copied().unwrap(),
                Option4: self.row.columns[1138].into_i32().copied().unwrap(),
                Option5: self.row.columns[1146].into_i32().copied().unwrap(),
                Option6: self.row.columns[1154].into_i32().copied().unwrap(),
                Option7: self.row.columns[1162].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1115].into_i32().copied().unwrap(),
                Option2: self.row.columns[1123].into_i32().copied().unwrap(),
                Option3: self.row.columns[1131].into_i32().copied().unwrap(),
                Option4: self.row.columns[1139].into_i32().copied().unwrap(),
                Option5: self.row.columns[1147].into_i32().copied().unwrap(),
                Option6: self.row.columns[1155].into_i32().copied().unwrap(),
                Option7: self.row.columns[1163].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1116].into_i32().copied().unwrap(),
                Option2: self.row.columns[1124].into_i32().copied().unwrap(),
                Option3: self.row.columns[1132].into_i32().copied().unwrap(),
                Option4: self.row.columns[1140].into_i32().copied().unwrap(),
                Option5: self.row.columns[1148].into_i32().copied().unwrap(),
                Option6: self.row.columns[1156].into_i32().copied().unwrap(),
                Option7: self.row.columns[1164].into_i32().copied().unwrap(),
            },
            FacialFeatureOptionElement {
                Option1: self.row.columns[1117].into_i32().copied().unwrap(),
                Option2: self.row.columns[1125].into_i32().copied().unwrap(),
                Option3: self.row.columns[1133].into_i32().copied().unwrap(),
                Option4: self.row.columns[1141].into_i32().copied().unwrap(),
                Option5: self.row.columns[1149].into_i32().copied().unwrap(),
                Option6: self.row.columns[1157].into_i32().copied().unwrap(),
                Option7: self.row.columns[1165].into_i32().copied().unwrap(),
            },
        ]
    }
    pub fn Race(&'a self) -> i32 {
        self.row.columns[0].into_i32().copied().unwrap()
    }
    pub fn Tribe(&'a self) -> i32 {
        self.row.columns[1].into_i32().copied().unwrap()
    }
    pub fn Gender(&'a self) -> i8 {
        self.row.columns[2].into_i8().copied().unwrap()
    }
}
