//! This file is auto-generated, do not edit it manually! This is generated based on the schema from https://github.com/xivdev/EXDSchema.
#![allow(warnings)]
use crate::{StructuredSheet, StructuredSheetIterator};
use physis::{
    Error, resource::{Resource, ResourceResolver},
    exd::EXD, exh::{EXH, ExcelColumnDefinition},
    excel::{Sheet, Field, Row},
    common::Language,
};
pub struct CharaMakeStructElement<'a> {
    pub Menu: &'a Field,
    pub SubMenuMask: &'a Field,
    pub Customize: &'a Field,
    pub SubMenuParam: [&'a Field; 100],
    pub Unknown0: [&'a Field; 6],
    pub InitVal: &'a Field,
    pub SubMenuType: &'a Field,
    pub SubMenuNum: &'a Field,
    pub LookAt: &'a Field,
    pub SubMenuGraphic: [&'a Field; 10],
}
pub struct FacialFeatureOptionElement<'a> {
    pub Option1: &'a Field,
    pub Option2: &'a Field,
    pub Option3: &'a Field,
    pub Option4: &'a Field,
    pub Option5: &'a Field,
    pub Option6: &'a Field,
    pub Option7: &'a Field,
}
#[derive(Debug, Clone)]
pub struct HairMakeTypeSheet {
    sheet: Sheet,
}
impl HairMakeTypeSheet {
    /// Read the sheet from a `ResourceResolver`.
    pub fn read_from(
        resolver: &mut ResourceResolver,
        language: Language,
    ) -> Result<Self, Error> {
        let exh = resolver.read_excel_sheet_header("HairMakeType")?;
        let sheet = resolver.read_excel_sheet(&exh, "HairMakeType", language)?;
        Ok(Self { sheet })
    }
    /// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
    pub fn row(&self, row_id: u32) -> Option<HairMakeTypeRow> {
        let row = &self.sheet.row(row_id)?;
        self.read_row(row)
    }
    /// Fetches the specified subrow from the sheet.
    pub fn subrow(&self, row_id: u32, subrow_id: u16) -> Option<HairMakeTypeRow> {
        let row = &self.sheet.subrow(row_id, subrow_id)?;
        self.read_row(row)
    }
    /// Returns the number of rows in this sheet.
    pub fn row_count(&self) -> u32 {
        self.sheet.exh.header.row_count
    }
}
impl StructuredSheet for HairMakeTypeSheet {
    type Row = HairMakeTypeRow;
    fn read_row(&self, row: &Row) -> Option<Self::Row> {
        let column_defs = &self.sheet.exh.column_definitions;
        let mut zipped: Vec<_> = row
            .columns
            .clone()
            .into_iter()
            .zip(column_defs)
            .collect();
        zipped.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
        let (columns, _): (Vec<Field>, Vec<ExcelColumnDefinition>) = zipped
            .into_iter()
            .unzip();
        Some(Self::Row { columns })
    }
}
impl<'a> IntoIterator for &'a HairMakeTypeSheet {
    type Item = (u32, Vec<(u16, HairMakeTypeRow)>);
    type IntoIter = StructuredSheetIterator<'a, HairMakeTypeSheet>;
    fn into_iter(self) -> StructuredSheetIterator<'a, HairMakeTypeSheet> {
        StructuredSheetIterator {
            sheet: self,
            iterator: (&self.sheet).into_iter(),
        }
    }
}
#[derive(Debug, Clone)]
pub struct HairMakeTypeRow {
    columns: Vec<Field>,
}
impl HairMakeTypeRow {
    pub fn CharaMakeStruct<'a>(&'a self) -> [CharaMakeStructElement<'a>; 9] {
        [
            CharaMakeStructElement {
                Menu: &self.columns[0],
                SubMenuMask: &self.columns[1],
                Customize: &self.columns[2],
                SubMenuParam: [
                    &self.columns[3],
                    &self.columns[4],
                    &self.columns[5],
                    &self.columns[6],
                    &self.columns[7],
                    &self.columns[8],
                    &self.columns[9],
                    &self.columns[10],
                    &self.columns[11],
                    &self.columns[12],
                    &self.columns[13],
                    &self.columns[14],
                    &self.columns[15],
                    &self.columns[16],
                    &self.columns[17],
                    &self.columns[18],
                    &self.columns[19],
                    &self.columns[20],
                    &self.columns[21],
                    &self.columns[22],
                    &self.columns[23],
                    &self.columns[24],
                    &self.columns[25],
                    &self.columns[26],
                    &self.columns[27],
                    &self.columns[28],
                    &self.columns[29],
                    &self.columns[30],
                    &self.columns[31],
                    &self.columns[32],
                    &self.columns[33],
                    &self.columns[34],
                    &self.columns[35],
                    &self.columns[36],
                    &self.columns[37],
                    &self.columns[38],
                    &self.columns[39],
                    &self.columns[40],
                    &self.columns[41],
                    &self.columns[42],
                    &self.columns[43],
                    &self.columns[44],
                    &self.columns[45],
                    &self.columns[46],
                    &self.columns[47],
                    &self.columns[48],
                    &self.columns[49],
                    &self.columns[50],
                    &self.columns[51],
                    &self.columns[52],
                    &self.columns[53],
                    &self.columns[54],
                    &self.columns[55],
                    &self.columns[56],
                    &self.columns[57],
                    &self.columns[58],
                    &self.columns[59],
                    &self.columns[60],
                    &self.columns[61],
                    &self.columns[62],
                    &self.columns[63],
                    &self.columns[64],
                    &self.columns[65],
                    &self.columns[66],
                    &self.columns[67],
                    &self.columns[68],
                    &self.columns[69],
                    &self.columns[70],
                    &self.columns[71],
                    &self.columns[72],
                    &self.columns[73],
                    &self.columns[74],
                    &self.columns[75],
                    &self.columns[76],
                    &self.columns[77],
                    &self.columns[78],
                    &self.columns[79],
                    &self.columns[80],
                    &self.columns[81],
                    &self.columns[82],
                    &self.columns[83],
                    &self.columns[84],
                    &self.columns[85],
                    &self.columns[86],
                    &self.columns[87],
                    &self.columns[88],
                    &self.columns[89],
                    &self.columns[90],
                    &self.columns[91],
                    &self.columns[92],
                    &self.columns[93],
                    &self.columns[94],
                    &self.columns[95],
                    &self.columns[96],
                    &self.columns[97],
                    &self.columns[98],
                    &self.columns[99],
                    &self.columns[100],
                    &self.columns[101],
                    &self.columns[102],
                ],
                Unknown0: [
                    &self.columns[103],
                    &self.columns[104],
                    &self.columns[105],
                    &self.columns[106],
                    &self.columns[107],
                    &self.columns[108],
                ],
                InitVal: &self.columns[109],
                SubMenuType: &self.columns[110],
                SubMenuNum: &self.columns[111],
                LookAt: &self.columns[112],
                SubMenuGraphic: [
                    &self.columns[113],
                    &self.columns[114],
                    &self.columns[115],
                    &self.columns[116],
                    &self.columns[117],
                    &self.columns[118],
                    &self.columns[119],
                    &self.columns[120],
                    &self.columns[121],
                    &self.columns[122],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[123],
                SubMenuMask: &self.columns[124],
                Customize: &self.columns[125],
                SubMenuParam: [
                    &self.columns[126],
                    &self.columns[127],
                    &self.columns[128],
                    &self.columns[129],
                    &self.columns[130],
                    &self.columns[131],
                    &self.columns[132],
                    &self.columns[133],
                    &self.columns[134],
                    &self.columns[135],
                    &self.columns[136],
                    &self.columns[137],
                    &self.columns[138],
                    &self.columns[139],
                    &self.columns[140],
                    &self.columns[141],
                    &self.columns[142],
                    &self.columns[143],
                    &self.columns[144],
                    &self.columns[145],
                    &self.columns[146],
                    &self.columns[147],
                    &self.columns[148],
                    &self.columns[149],
                    &self.columns[150],
                    &self.columns[151],
                    &self.columns[152],
                    &self.columns[153],
                    &self.columns[154],
                    &self.columns[155],
                    &self.columns[156],
                    &self.columns[157],
                    &self.columns[158],
                    &self.columns[159],
                    &self.columns[160],
                    &self.columns[161],
                    &self.columns[162],
                    &self.columns[163],
                    &self.columns[164],
                    &self.columns[165],
                    &self.columns[166],
                    &self.columns[167],
                    &self.columns[168],
                    &self.columns[169],
                    &self.columns[170],
                    &self.columns[171],
                    &self.columns[172],
                    &self.columns[173],
                    &self.columns[174],
                    &self.columns[175],
                    &self.columns[176],
                    &self.columns[177],
                    &self.columns[178],
                    &self.columns[179],
                    &self.columns[180],
                    &self.columns[181],
                    &self.columns[182],
                    &self.columns[183],
                    &self.columns[184],
                    &self.columns[185],
                    &self.columns[186],
                    &self.columns[187],
                    &self.columns[188],
                    &self.columns[189],
                    &self.columns[190],
                    &self.columns[191],
                    &self.columns[192],
                    &self.columns[193],
                    &self.columns[194],
                    &self.columns[195],
                    &self.columns[196],
                    &self.columns[197],
                    &self.columns[198],
                    &self.columns[199],
                    &self.columns[200],
                    &self.columns[201],
                    &self.columns[202],
                    &self.columns[203],
                    &self.columns[204],
                    &self.columns[205],
                    &self.columns[206],
                    &self.columns[207],
                    &self.columns[208],
                    &self.columns[209],
                    &self.columns[210],
                    &self.columns[211],
                    &self.columns[212],
                    &self.columns[213],
                    &self.columns[214],
                    &self.columns[215],
                    &self.columns[216],
                    &self.columns[217],
                    &self.columns[218],
                    &self.columns[219],
                    &self.columns[220],
                    &self.columns[221],
                    &self.columns[222],
                    &self.columns[223],
                    &self.columns[224],
                    &self.columns[225],
                ],
                Unknown0: [
                    &self.columns[226],
                    &self.columns[227],
                    &self.columns[228],
                    &self.columns[229],
                    &self.columns[230],
                    &self.columns[231],
                ],
                InitVal: &self.columns[232],
                SubMenuType: &self.columns[233],
                SubMenuNum: &self.columns[234],
                LookAt: &self.columns[235],
                SubMenuGraphic: [
                    &self.columns[236],
                    &self.columns[237],
                    &self.columns[238],
                    &self.columns[239],
                    &self.columns[240],
                    &self.columns[241],
                    &self.columns[242],
                    &self.columns[243],
                    &self.columns[244],
                    &self.columns[245],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[246],
                SubMenuMask: &self.columns[247],
                Customize: &self.columns[248],
                SubMenuParam: [
                    &self.columns[249],
                    &self.columns[250],
                    &self.columns[251],
                    &self.columns[252],
                    &self.columns[253],
                    &self.columns[254],
                    &self.columns[255],
                    &self.columns[256],
                    &self.columns[257],
                    &self.columns[258],
                    &self.columns[259],
                    &self.columns[260],
                    &self.columns[261],
                    &self.columns[262],
                    &self.columns[263],
                    &self.columns[264],
                    &self.columns[265],
                    &self.columns[266],
                    &self.columns[267],
                    &self.columns[268],
                    &self.columns[269],
                    &self.columns[270],
                    &self.columns[271],
                    &self.columns[272],
                    &self.columns[273],
                    &self.columns[274],
                    &self.columns[275],
                    &self.columns[276],
                    &self.columns[277],
                    &self.columns[278],
                    &self.columns[279],
                    &self.columns[280],
                    &self.columns[281],
                    &self.columns[282],
                    &self.columns[283],
                    &self.columns[284],
                    &self.columns[285],
                    &self.columns[286],
                    &self.columns[287],
                    &self.columns[288],
                    &self.columns[289],
                    &self.columns[290],
                    &self.columns[291],
                    &self.columns[292],
                    &self.columns[293],
                    &self.columns[294],
                    &self.columns[295],
                    &self.columns[296],
                    &self.columns[297],
                    &self.columns[298],
                    &self.columns[299],
                    &self.columns[300],
                    &self.columns[301],
                    &self.columns[302],
                    &self.columns[303],
                    &self.columns[304],
                    &self.columns[305],
                    &self.columns[306],
                    &self.columns[307],
                    &self.columns[308],
                    &self.columns[309],
                    &self.columns[310],
                    &self.columns[311],
                    &self.columns[312],
                    &self.columns[313],
                    &self.columns[314],
                    &self.columns[315],
                    &self.columns[316],
                    &self.columns[317],
                    &self.columns[318],
                    &self.columns[319],
                    &self.columns[320],
                    &self.columns[321],
                    &self.columns[322],
                    &self.columns[323],
                    &self.columns[324],
                    &self.columns[325],
                    &self.columns[326],
                    &self.columns[327],
                    &self.columns[328],
                    &self.columns[329],
                    &self.columns[330],
                    &self.columns[331],
                    &self.columns[332],
                    &self.columns[333],
                    &self.columns[334],
                    &self.columns[335],
                    &self.columns[336],
                    &self.columns[337],
                    &self.columns[338],
                    &self.columns[339],
                    &self.columns[340],
                    &self.columns[341],
                    &self.columns[342],
                    &self.columns[343],
                    &self.columns[344],
                    &self.columns[345],
                    &self.columns[346],
                    &self.columns[347],
                    &self.columns[348],
                ],
                Unknown0: [
                    &self.columns[349],
                    &self.columns[350],
                    &self.columns[351],
                    &self.columns[352],
                    &self.columns[353],
                    &self.columns[354],
                ],
                InitVal: &self.columns[355],
                SubMenuType: &self.columns[356],
                SubMenuNum: &self.columns[357],
                LookAt: &self.columns[358],
                SubMenuGraphic: [
                    &self.columns[359],
                    &self.columns[360],
                    &self.columns[361],
                    &self.columns[362],
                    &self.columns[363],
                    &self.columns[364],
                    &self.columns[365],
                    &self.columns[366],
                    &self.columns[367],
                    &self.columns[368],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[369],
                SubMenuMask: &self.columns[370],
                Customize: &self.columns[371],
                SubMenuParam: [
                    &self.columns[372],
                    &self.columns[373],
                    &self.columns[374],
                    &self.columns[375],
                    &self.columns[376],
                    &self.columns[377],
                    &self.columns[378],
                    &self.columns[379],
                    &self.columns[380],
                    &self.columns[381],
                    &self.columns[382],
                    &self.columns[383],
                    &self.columns[384],
                    &self.columns[385],
                    &self.columns[386],
                    &self.columns[387],
                    &self.columns[388],
                    &self.columns[389],
                    &self.columns[390],
                    &self.columns[391],
                    &self.columns[392],
                    &self.columns[393],
                    &self.columns[394],
                    &self.columns[395],
                    &self.columns[396],
                    &self.columns[397],
                    &self.columns[398],
                    &self.columns[399],
                    &self.columns[400],
                    &self.columns[401],
                    &self.columns[402],
                    &self.columns[403],
                    &self.columns[404],
                    &self.columns[405],
                    &self.columns[406],
                    &self.columns[407],
                    &self.columns[408],
                    &self.columns[409],
                    &self.columns[410],
                    &self.columns[411],
                    &self.columns[412],
                    &self.columns[413],
                    &self.columns[414],
                    &self.columns[415],
                    &self.columns[416],
                    &self.columns[417],
                    &self.columns[418],
                    &self.columns[419],
                    &self.columns[420],
                    &self.columns[421],
                    &self.columns[422],
                    &self.columns[423],
                    &self.columns[424],
                    &self.columns[425],
                    &self.columns[426],
                    &self.columns[427],
                    &self.columns[428],
                    &self.columns[429],
                    &self.columns[430],
                    &self.columns[431],
                    &self.columns[432],
                    &self.columns[433],
                    &self.columns[434],
                    &self.columns[435],
                    &self.columns[436],
                    &self.columns[437],
                    &self.columns[438],
                    &self.columns[439],
                    &self.columns[440],
                    &self.columns[441],
                    &self.columns[442],
                    &self.columns[443],
                    &self.columns[444],
                    &self.columns[445],
                    &self.columns[446],
                    &self.columns[447],
                    &self.columns[448],
                    &self.columns[449],
                    &self.columns[450],
                    &self.columns[451],
                    &self.columns[452],
                    &self.columns[453],
                    &self.columns[454],
                    &self.columns[455],
                    &self.columns[456],
                    &self.columns[457],
                    &self.columns[458],
                    &self.columns[459],
                    &self.columns[460],
                    &self.columns[461],
                    &self.columns[462],
                    &self.columns[463],
                    &self.columns[464],
                    &self.columns[465],
                    &self.columns[466],
                    &self.columns[467],
                    &self.columns[468],
                    &self.columns[469],
                    &self.columns[470],
                    &self.columns[471],
                ],
                Unknown0: [
                    &self.columns[472],
                    &self.columns[473],
                    &self.columns[474],
                    &self.columns[475],
                    &self.columns[476],
                    &self.columns[477],
                ],
                InitVal: &self.columns[478],
                SubMenuType: &self.columns[479],
                SubMenuNum: &self.columns[480],
                LookAt: &self.columns[481],
                SubMenuGraphic: [
                    &self.columns[482],
                    &self.columns[483],
                    &self.columns[484],
                    &self.columns[485],
                    &self.columns[486],
                    &self.columns[487],
                    &self.columns[488],
                    &self.columns[489],
                    &self.columns[490],
                    &self.columns[491],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[492],
                SubMenuMask: &self.columns[493],
                Customize: &self.columns[494],
                SubMenuParam: [
                    &self.columns[495],
                    &self.columns[496],
                    &self.columns[497],
                    &self.columns[498],
                    &self.columns[499],
                    &self.columns[500],
                    &self.columns[501],
                    &self.columns[502],
                    &self.columns[503],
                    &self.columns[504],
                    &self.columns[505],
                    &self.columns[506],
                    &self.columns[507],
                    &self.columns[508],
                    &self.columns[509],
                    &self.columns[510],
                    &self.columns[511],
                    &self.columns[512],
                    &self.columns[513],
                    &self.columns[514],
                    &self.columns[515],
                    &self.columns[516],
                    &self.columns[517],
                    &self.columns[518],
                    &self.columns[519],
                    &self.columns[520],
                    &self.columns[521],
                    &self.columns[522],
                    &self.columns[523],
                    &self.columns[524],
                    &self.columns[525],
                    &self.columns[526],
                    &self.columns[527],
                    &self.columns[528],
                    &self.columns[529],
                    &self.columns[530],
                    &self.columns[531],
                    &self.columns[532],
                    &self.columns[533],
                    &self.columns[534],
                    &self.columns[535],
                    &self.columns[536],
                    &self.columns[537],
                    &self.columns[538],
                    &self.columns[539],
                    &self.columns[540],
                    &self.columns[541],
                    &self.columns[542],
                    &self.columns[543],
                    &self.columns[544],
                    &self.columns[545],
                    &self.columns[546],
                    &self.columns[547],
                    &self.columns[548],
                    &self.columns[549],
                    &self.columns[550],
                    &self.columns[551],
                    &self.columns[552],
                    &self.columns[553],
                    &self.columns[554],
                    &self.columns[555],
                    &self.columns[556],
                    &self.columns[557],
                    &self.columns[558],
                    &self.columns[559],
                    &self.columns[560],
                    &self.columns[561],
                    &self.columns[562],
                    &self.columns[563],
                    &self.columns[564],
                    &self.columns[565],
                    &self.columns[566],
                    &self.columns[567],
                    &self.columns[568],
                    &self.columns[569],
                    &self.columns[570],
                    &self.columns[571],
                    &self.columns[572],
                    &self.columns[573],
                    &self.columns[574],
                    &self.columns[575],
                    &self.columns[576],
                    &self.columns[577],
                    &self.columns[578],
                    &self.columns[579],
                    &self.columns[580],
                    &self.columns[581],
                    &self.columns[582],
                    &self.columns[583],
                    &self.columns[584],
                    &self.columns[585],
                    &self.columns[586],
                    &self.columns[587],
                    &self.columns[588],
                    &self.columns[589],
                    &self.columns[590],
                    &self.columns[591],
                    &self.columns[592],
                    &self.columns[593],
                    &self.columns[594],
                ],
                Unknown0: [
                    &self.columns[595],
                    &self.columns[596],
                    &self.columns[597],
                    &self.columns[598],
                    &self.columns[599],
                    &self.columns[600],
                ],
                InitVal: &self.columns[601],
                SubMenuType: &self.columns[602],
                SubMenuNum: &self.columns[603],
                LookAt: &self.columns[604],
                SubMenuGraphic: [
                    &self.columns[605],
                    &self.columns[606],
                    &self.columns[607],
                    &self.columns[608],
                    &self.columns[609],
                    &self.columns[610],
                    &self.columns[611],
                    &self.columns[612],
                    &self.columns[613],
                    &self.columns[614],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[615],
                SubMenuMask: &self.columns[616],
                Customize: &self.columns[617],
                SubMenuParam: [
                    &self.columns[618],
                    &self.columns[619],
                    &self.columns[620],
                    &self.columns[621],
                    &self.columns[622],
                    &self.columns[623],
                    &self.columns[624],
                    &self.columns[625],
                    &self.columns[626],
                    &self.columns[627],
                    &self.columns[628],
                    &self.columns[629],
                    &self.columns[630],
                    &self.columns[631],
                    &self.columns[632],
                    &self.columns[633],
                    &self.columns[634],
                    &self.columns[635],
                    &self.columns[636],
                    &self.columns[637],
                    &self.columns[638],
                    &self.columns[639],
                    &self.columns[640],
                    &self.columns[641],
                    &self.columns[642],
                    &self.columns[643],
                    &self.columns[644],
                    &self.columns[645],
                    &self.columns[646],
                    &self.columns[647],
                    &self.columns[648],
                    &self.columns[649],
                    &self.columns[650],
                    &self.columns[651],
                    &self.columns[652],
                    &self.columns[653],
                    &self.columns[654],
                    &self.columns[655],
                    &self.columns[656],
                    &self.columns[657],
                    &self.columns[658],
                    &self.columns[659],
                    &self.columns[660],
                    &self.columns[661],
                    &self.columns[662],
                    &self.columns[663],
                    &self.columns[664],
                    &self.columns[665],
                    &self.columns[666],
                    &self.columns[667],
                    &self.columns[668],
                    &self.columns[669],
                    &self.columns[670],
                    &self.columns[671],
                    &self.columns[672],
                    &self.columns[673],
                    &self.columns[674],
                    &self.columns[675],
                    &self.columns[676],
                    &self.columns[677],
                    &self.columns[678],
                    &self.columns[679],
                    &self.columns[680],
                    &self.columns[681],
                    &self.columns[682],
                    &self.columns[683],
                    &self.columns[684],
                    &self.columns[685],
                    &self.columns[686],
                    &self.columns[687],
                    &self.columns[688],
                    &self.columns[689],
                    &self.columns[690],
                    &self.columns[691],
                    &self.columns[692],
                    &self.columns[693],
                    &self.columns[694],
                    &self.columns[695],
                    &self.columns[696],
                    &self.columns[697],
                    &self.columns[698],
                    &self.columns[699],
                    &self.columns[700],
                    &self.columns[701],
                    &self.columns[702],
                    &self.columns[703],
                    &self.columns[704],
                    &self.columns[705],
                    &self.columns[706],
                    &self.columns[707],
                    &self.columns[708],
                    &self.columns[709],
                    &self.columns[710],
                    &self.columns[711],
                    &self.columns[712],
                    &self.columns[713],
                    &self.columns[714],
                    &self.columns[715],
                    &self.columns[716],
                    &self.columns[717],
                ],
                Unknown0: [
                    &self.columns[718],
                    &self.columns[719],
                    &self.columns[720],
                    &self.columns[721],
                    &self.columns[722],
                    &self.columns[723],
                ],
                InitVal: &self.columns[724],
                SubMenuType: &self.columns[725],
                SubMenuNum: &self.columns[726],
                LookAt: &self.columns[727],
                SubMenuGraphic: [
                    &self.columns[728],
                    &self.columns[729],
                    &self.columns[730],
                    &self.columns[731],
                    &self.columns[732],
                    &self.columns[733],
                    &self.columns[734],
                    &self.columns[735],
                    &self.columns[736],
                    &self.columns[737],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[738],
                SubMenuMask: &self.columns[739],
                Customize: &self.columns[740],
                SubMenuParam: [
                    &self.columns[741],
                    &self.columns[742],
                    &self.columns[743],
                    &self.columns[744],
                    &self.columns[745],
                    &self.columns[746],
                    &self.columns[747],
                    &self.columns[748],
                    &self.columns[749],
                    &self.columns[750],
                    &self.columns[751],
                    &self.columns[752],
                    &self.columns[753],
                    &self.columns[754],
                    &self.columns[755],
                    &self.columns[756],
                    &self.columns[757],
                    &self.columns[758],
                    &self.columns[759],
                    &self.columns[760],
                    &self.columns[761],
                    &self.columns[762],
                    &self.columns[763],
                    &self.columns[764],
                    &self.columns[765],
                    &self.columns[766],
                    &self.columns[767],
                    &self.columns[768],
                    &self.columns[769],
                    &self.columns[770],
                    &self.columns[771],
                    &self.columns[772],
                    &self.columns[773],
                    &self.columns[774],
                    &self.columns[775],
                    &self.columns[776],
                    &self.columns[777],
                    &self.columns[778],
                    &self.columns[779],
                    &self.columns[780],
                    &self.columns[781],
                    &self.columns[782],
                    &self.columns[783],
                    &self.columns[784],
                    &self.columns[785],
                    &self.columns[786],
                    &self.columns[787],
                    &self.columns[788],
                    &self.columns[789],
                    &self.columns[790],
                    &self.columns[791],
                    &self.columns[792],
                    &self.columns[793],
                    &self.columns[794],
                    &self.columns[795],
                    &self.columns[796],
                    &self.columns[797],
                    &self.columns[798],
                    &self.columns[799],
                    &self.columns[800],
                    &self.columns[801],
                    &self.columns[802],
                    &self.columns[803],
                    &self.columns[804],
                    &self.columns[805],
                    &self.columns[806],
                    &self.columns[807],
                    &self.columns[808],
                    &self.columns[809],
                    &self.columns[810],
                    &self.columns[811],
                    &self.columns[812],
                    &self.columns[813],
                    &self.columns[814],
                    &self.columns[815],
                    &self.columns[816],
                    &self.columns[817],
                    &self.columns[818],
                    &self.columns[819],
                    &self.columns[820],
                    &self.columns[821],
                    &self.columns[822],
                    &self.columns[823],
                    &self.columns[824],
                    &self.columns[825],
                    &self.columns[826],
                    &self.columns[827],
                    &self.columns[828],
                    &self.columns[829],
                    &self.columns[830],
                    &self.columns[831],
                    &self.columns[832],
                    &self.columns[833],
                    &self.columns[834],
                    &self.columns[835],
                    &self.columns[836],
                    &self.columns[837],
                    &self.columns[838],
                    &self.columns[839],
                    &self.columns[840],
                ],
                Unknown0: [
                    &self.columns[841],
                    &self.columns[842],
                    &self.columns[843],
                    &self.columns[844],
                    &self.columns[845],
                    &self.columns[846],
                ],
                InitVal: &self.columns[847],
                SubMenuType: &self.columns[848],
                SubMenuNum: &self.columns[849],
                LookAt: &self.columns[850],
                SubMenuGraphic: [
                    &self.columns[851],
                    &self.columns[852],
                    &self.columns[853],
                    &self.columns[854],
                    &self.columns[855],
                    &self.columns[856],
                    &self.columns[857],
                    &self.columns[858],
                    &self.columns[859],
                    &self.columns[860],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[861],
                SubMenuMask: &self.columns[862],
                Customize: &self.columns[863],
                SubMenuParam: [
                    &self.columns[864],
                    &self.columns[865],
                    &self.columns[866],
                    &self.columns[867],
                    &self.columns[868],
                    &self.columns[869],
                    &self.columns[870],
                    &self.columns[871],
                    &self.columns[872],
                    &self.columns[873],
                    &self.columns[874],
                    &self.columns[875],
                    &self.columns[876],
                    &self.columns[877],
                    &self.columns[878],
                    &self.columns[879],
                    &self.columns[880],
                    &self.columns[881],
                    &self.columns[882],
                    &self.columns[883],
                    &self.columns[884],
                    &self.columns[885],
                    &self.columns[886],
                    &self.columns[887],
                    &self.columns[888],
                    &self.columns[889],
                    &self.columns[890],
                    &self.columns[891],
                    &self.columns[892],
                    &self.columns[893],
                    &self.columns[894],
                    &self.columns[895],
                    &self.columns[896],
                    &self.columns[897],
                    &self.columns[898],
                    &self.columns[899],
                    &self.columns[900],
                    &self.columns[901],
                    &self.columns[902],
                    &self.columns[903],
                    &self.columns[904],
                    &self.columns[905],
                    &self.columns[906],
                    &self.columns[907],
                    &self.columns[908],
                    &self.columns[909],
                    &self.columns[910],
                    &self.columns[911],
                    &self.columns[912],
                    &self.columns[913],
                    &self.columns[914],
                    &self.columns[915],
                    &self.columns[916],
                    &self.columns[917],
                    &self.columns[918],
                    &self.columns[919],
                    &self.columns[920],
                    &self.columns[921],
                    &self.columns[922],
                    &self.columns[923],
                    &self.columns[924],
                    &self.columns[925],
                    &self.columns[926],
                    &self.columns[927],
                    &self.columns[928],
                    &self.columns[929],
                    &self.columns[930],
                    &self.columns[931],
                    &self.columns[932],
                    &self.columns[933],
                    &self.columns[934],
                    &self.columns[935],
                    &self.columns[936],
                    &self.columns[937],
                    &self.columns[938],
                    &self.columns[939],
                    &self.columns[940],
                    &self.columns[941],
                    &self.columns[942],
                    &self.columns[943],
                    &self.columns[944],
                    &self.columns[945],
                    &self.columns[946],
                    &self.columns[947],
                    &self.columns[948],
                    &self.columns[949],
                    &self.columns[950],
                    &self.columns[951],
                    &self.columns[952],
                    &self.columns[953],
                    &self.columns[954],
                    &self.columns[955],
                    &self.columns[956],
                    &self.columns[957],
                    &self.columns[958],
                    &self.columns[959],
                    &self.columns[960],
                    &self.columns[961],
                    &self.columns[962],
                    &self.columns[963],
                ],
                Unknown0: [
                    &self.columns[964],
                    &self.columns[965],
                    &self.columns[966],
                    &self.columns[967],
                    &self.columns[968],
                    &self.columns[969],
                ],
                InitVal: &self.columns[970],
                SubMenuType: &self.columns[971],
                SubMenuNum: &self.columns[972],
                LookAt: &self.columns[973],
                SubMenuGraphic: [
                    &self.columns[974],
                    &self.columns[975],
                    &self.columns[976],
                    &self.columns[977],
                    &self.columns[978],
                    &self.columns[979],
                    &self.columns[980],
                    &self.columns[981],
                    &self.columns[982],
                    &self.columns[983],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.columns[984],
                SubMenuMask: &self.columns[985],
                Customize: &self.columns[986],
                SubMenuParam: [
                    &self.columns[987],
                    &self.columns[988],
                    &self.columns[989],
                    &self.columns[990],
                    &self.columns[991],
                    &self.columns[992],
                    &self.columns[993],
                    &self.columns[994],
                    &self.columns[995],
                    &self.columns[996],
                    &self.columns[997],
                    &self.columns[998],
                    &self.columns[999],
                    &self.columns[1000],
                    &self.columns[1001],
                    &self.columns[1002],
                    &self.columns[1003],
                    &self.columns[1004],
                    &self.columns[1005],
                    &self.columns[1006],
                    &self.columns[1007],
                    &self.columns[1008],
                    &self.columns[1009],
                    &self.columns[1010],
                    &self.columns[1011],
                    &self.columns[1012],
                    &self.columns[1013],
                    &self.columns[1014],
                    &self.columns[1015],
                    &self.columns[1016],
                    &self.columns[1017],
                    &self.columns[1018],
                    &self.columns[1019],
                    &self.columns[1020],
                    &self.columns[1021],
                    &self.columns[1022],
                    &self.columns[1023],
                    &self.columns[1024],
                    &self.columns[1025],
                    &self.columns[1026],
                    &self.columns[1027],
                    &self.columns[1028],
                    &self.columns[1029],
                    &self.columns[1030],
                    &self.columns[1031],
                    &self.columns[1032],
                    &self.columns[1033],
                    &self.columns[1034],
                    &self.columns[1035],
                    &self.columns[1036],
                    &self.columns[1037],
                    &self.columns[1038],
                    &self.columns[1039],
                    &self.columns[1040],
                    &self.columns[1041],
                    &self.columns[1042],
                    &self.columns[1043],
                    &self.columns[1044],
                    &self.columns[1045],
                    &self.columns[1046],
                    &self.columns[1047],
                    &self.columns[1048],
                    &self.columns[1049],
                    &self.columns[1050],
                    &self.columns[1051],
                    &self.columns[1052],
                    &self.columns[1053],
                    &self.columns[1054],
                    &self.columns[1055],
                    &self.columns[1056],
                    &self.columns[1057],
                    &self.columns[1058],
                    &self.columns[1059],
                    &self.columns[1060],
                    &self.columns[1061],
                    &self.columns[1062],
                    &self.columns[1063],
                    &self.columns[1064],
                    &self.columns[1065],
                    &self.columns[1066],
                    &self.columns[1067],
                    &self.columns[1068],
                    &self.columns[1069],
                    &self.columns[1070],
                    &self.columns[1071],
                    &self.columns[1072],
                    &self.columns[1073],
                    &self.columns[1074],
                    &self.columns[1075],
                    &self.columns[1076],
                    &self.columns[1077],
                    &self.columns[1078],
                    &self.columns[1079],
                    &self.columns[1080],
                    &self.columns[1081],
                    &self.columns[1082],
                    &self.columns[1083],
                    &self.columns[1084],
                    &self.columns[1085],
                    &self.columns[1086],
                ],
                Unknown0: [
                    &self.columns[1087],
                    &self.columns[1088],
                    &self.columns[1089],
                    &self.columns[1090],
                    &self.columns[1091],
                    &self.columns[1092],
                ],
                InitVal: &self.columns[1093],
                SubMenuType: &self.columns[1094],
                SubMenuNum: &self.columns[1095],
                LookAt: &self.columns[1096],
                SubMenuGraphic: [
                    &self.columns[1097],
                    &self.columns[1098],
                    &self.columns[1099],
                    &self.columns[1100],
                    &self.columns[1101],
                    &self.columns[1102],
                    &self.columns[1103],
                    &self.columns[1104],
                    &self.columns[1105],
                    &self.columns[1106],
                ],
            },
        ]
    }
    pub fn FacialFeatureOption<'a>(&'a self) -> [FacialFeatureOptionElement<'a>; 8] {
        [
            FacialFeatureOptionElement {
                Option1: &self.columns[1107],
                Option2: &self.columns[1108],
                Option3: &self.columns[1109],
                Option4: &self.columns[1110],
                Option5: &self.columns[1111],
                Option6: &self.columns[1112],
                Option7: &self.columns[1113],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1114],
                Option2: &self.columns[1115],
                Option3: &self.columns[1116],
                Option4: &self.columns[1117],
                Option5: &self.columns[1118],
                Option6: &self.columns[1119],
                Option7: &self.columns[1120],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1121],
                Option2: &self.columns[1122],
                Option3: &self.columns[1123],
                Option4: &self.columns[1124],
                Option5: &self.columns[1125],
                Option6: &self.columns[1126],
                Option7: &self.columns[1127],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1128],
                Option2: &self.columns[1129],
                Option3: &self.columns[1130],
                Option4: &self.columns[1131],
                Option5: &self.columns[1132],
                Option6: &self.columns[1133],
                Option7: &self.columns[1134],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1135],
                Option2: &self.columns[1136],
                Option3: &self.columns[1137],
                Option4: &self.columns[1138],
                Option5: &self.columns[1139],
                Option6: &self.columns[1140],
                Option7: &self.columns[1141],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1142],
                Option2: &self.columns[1143],
                Option3: &self.columns[1144],
                Option4: &self.columns[1145],
                Option5: &self.columns[1146],
                Option6: &self.columns[1147],
                Option7: &self.columns[1148],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1149],
                Option2: &self.columns[1150],
                Option3: &self.columns[1151],
                Option4: &self.columns[1152],
                Option5: &self.columns[1153],
                Option6: &self.columns[1154],
                Option7: &self.columns[1155],
            },
            FacialFeatureOptionElement {
                Option1: &self.columns[1156],
                Option2: &self.columns[1157],
                Option3: &self.columns[1158],
                Option4: &self.columns[1159],
                Option5: &self.columns[1160],
                Option6: &self.columns[1161],
                Option7: &self.columns[1162],
            },
        ]
    }
    pub fn Race<'a>(&'a self) -> &'a Field {
        &self.columns[1163]
    }
    pub fn Tribe<'a>(&'a self) -> &'a Field {
        &self.columns[1164]
    }
    pub fn Gender<'a>(&'a self) -> &'a Field {
        &self.columns[1165]
    }
}
