//! This file is auto-generated, do not edit it manually! This is generated based on the schema from https://github.com/xivdev/EXDSchema.
#![allow(warnings)]
use crate::{StructuredSheet, StructuredSheetIterator};
use physis::{
    Error, resource::{Resource, ResourceResolver},
    exd::EXD, exh::{EXH, ExcelColumnDefinition},
    excel::{Sheet, Field, Row},
    Language,
};
pub struct CharaMakeStructElement<'a> {
    pub Menu: &'a Field,
    pub SubMenuMask: &'a Field,
    pub Customize: &'a Field,
    pub SubMenuParam: [&'a Field; 100],
    pub Unknown0: [&'a Field; 6],
    pub InitVal: &'a Field,
    pub SubMenuType: &'a Field,
    pub SubMenuNum: &'a Field,
    pub LookAt: &'a Field,
    pub SubMenuGraphic: [&'a Field; 10],
}
pub struct FacialFeatureOptionElement<'a> {
    pub Option1: &'a Field,
    pub Option2: &'a Field,
    pub Option3: &'a Field,
    pub Option4: &'a Field,
    pub Option5: &'a Field,
    pub Option6: &'a Field,
    pub Option7: &'a Field,
}
#[derive(Debug, Clone)]
pub struct HairMakeTypeSheet {
    sheet: Sheet,
    index_mapping: Vec<usize>,
}
impl HairMakeTypeSheet {
    /// Read the sheet from a `ResourceResolver`.
    pub fn read_from(
        resolver: &mut ResourceResolver,
        language: Language,
    ) -> Result<Self, Error> {
        let exh = resolver.read_excel_sheet_header("HairMakeType")?;
        let sheet = resolver.read_excel_sheet(&exh, "HairMakeType", language)?;
        let mut index_mapping: Vec<(usize, &ExcelColumnDefinition)> = sheet
            .exh
            .column_definitions
            .iter()
            .enumerate()
            .collect();
        index_mapping.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
        let index_mapping: Vec<usize> = index_mapping
            .iter()
            .map(|(index, _)| *index)
            .collect();
        Ok(Self { sheet, index_mapping })
    }
    /// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
    pub fn row(&self, row_id: u32) -> Option<HairMakeTypeRow> {
        let row = &self.sheet.row(row_id)?;
        self.read_row(row)
    }
    /// Fetches the specified subrow from the sheet.
    pub fn subrow(&self, row_id: u32, subrow_id: u16) -> Option<HairMakeTypeRow> {
        let row = &self.sheet.subrow(row_id, subrow_id)?;
        self.read_row(row)
    }
    /// Returns the number of rows in this sheet.
    pub fn row_count(&self) -> u32 {
        self.sheet.exh.header.row_count
    }
}
impl<'a> StructuredSheet<'a> for HairMakeTypeSheet {
    type Row = HairMakeTypeRow<'a>;
    fn read_row(&self, row: &'a Row) -> Option<Self::Row> {
        Some(Self::Row {
            row,
            index_mapping: self.index_mapping.clone(),
        })
    }
}
impl<'a> IntoIterator for &'a HairMakeTypeSheet {
    type Item = (u32, Vec<(u16, HairMakeTypeRow<'a>)>);
    type IntoIter = StructuredSheetIterator<'a, HairMakeTypeSheet>;
    fn into_iter(self) -> StructuredSheetIterator<'a, HairMakeTypeSheet> {
        StructuredSheetIterator {
            sheet: self,
            iterator: (&self.sheet).into_iter(),
        }
    }
}
#[derive(Debug, Clone)]
pub struct HairMakeTypeRow<'a> {
    row: &'a Row,
    index_mapping: Vec<usize>,
}
impl<'a> HairMakeTypeRow<'a> {
    pub fn CharaMakeStruct(&'a self) -> [CharaMakeStructElement<'a>; 9] {
        [
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[0]],
                SubMenuMask: &self.row.columns[self.index_mapping[1]],
                Customize: &self.row.columns[self.index_mapping[2]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[3]],
                    &self.row.columns[self.index_mapping[4]],
                    &self.row.columns[self.index_mapping[5]],
                    &self.row.columns[self.index_mapping[6]],
                    &self.row.columns[self.index_mapping[7]],
                    &self.row.columns[self.index_mapping[8]],
                    &self.row.columns[self.index_mapping[9]],
                    &self.row.columns[self.index_mapping[10]],
                    &self.row.columns[self.index_mapping[11]],
                    &self.row.columns[self.index_mapping[12]],
                    &self.row.columns[self.index_mapping[13]],
                    &self.row.columns[self.index_mapping[14]],
                    &self.row.columns[self.index_mapping[15]],
                    &self.row.columns[self.index_mapping[16]],
                    &self.row.columns[self.index_mapping[17]],
                    &self.row.columns[self.index_mapping[18]],
                    &self.row.columns[self.index_mapping[19]],
                    &self.row.columns[self.index_mapping[20]],
                    &self.row.columns[self.index_mapping[21]],
                    &self.row.columns[self.index_mapping[22]],
                    &self.row.columns[self.index_mapping[23]],
                    &self.row.columns[self.index_mapping[24]],
                    &self.row.columns[self.index_mapping[25]],
                    &self.row.columns[self.index_mapping[26]],
                    &self.row.columns[self.index_mapping[27]],
                    &self.row.columns[self.index_mapping[28]],
                    &self.row.columns[self.index_mapping[29]],
                    &self.row.columns[self.index_mapping[30]],
                    &self.row.columns[self.index_mapping[31]],
                    &self.row.columns[self.index_mapping[32]],
                    &self.row.columns[self.index_mapping[33]],
                    &self.row.columns[self.index_mapping[34]],
                    &self.row.columns[self.index_mapping[35]],
                    &self.row.columns[self.index_mapping[36]],
                    &self.row.columns[self.index_mapping[37]],
                    &self.row.columns[self.index_mapping[38]],
                    &self.row.columns[self.index_mapping[39]],
                    &self.row.columns[self.index_mapping[40]],
                    &self.row.columns[self.index_mapping[41]],
                    &self.row.columns[self.index_mapping[42]],
                    &self.row.columns[self.index_mapping[43]],
                    &self.row.columns[self.index_mapping[44]],
                    &self.row.columns[self.index_mapping[45]],
                    &self.row.columns[self.index_mapping[46]],
                    &self.row.columns[self.index_mapping[47]],
                    &self.row.columns[self.index_mapping[48]],
                    &self.row.columns[self.index_mapping[49]],
                    &self.row.columns[self.index_mapping[50]],
                    &self.row.columns[self.index_mapping[51]],
                    &self.row.columns[self.index_mapping[52]],
                    &self.row.columns[self.index_mapping[53]],
                    &self.row.columns[self.index_mapping[54]],
                    &self.row.columns[self.index_mapping[55]],
                    &self.row.columns[self.index_mapping[56]],
                    &self.row.columns[self.index_mapping[57]],
                    &self.row.columns[self.index_mapping[58]],
                    &self.row.columns[self.index_mapping[59]],
                    &self.row.columns[self.index_mapping[60]],
                    &self.row.columns[self.index_mapping[61]],
                    &self.row.columns[self.index_mapping[62]],
                    &self.row.columns[self.index_mapping[63]],
                    &self.row.columns[self.index_mapping[64]],
                    &self.row.columns[self.index_mapping[65]],
                    &self.row.columns[self.index_mapping[66]],
                    &self.row.columns[self.index_mapping[67]],
                    &self.row.columns[self.index_mapping[68]],
                    &self.row.columns[self.index_mapping[69]],
                    &self.row.columns[self.index_mapping[70]],
                    &self.row.columns[self.index_mapping[71]],
                    &self.row.columns[self.index_mapping[72]],
                    &self.row.columns[self.index_mapping[73]],
                    &self.row.columns[self.index_mapping[74]],
                    &self.row.columns[self.index_mapping[75]],
                    &self.row.columns[self.index_mapping[76]],
                    &self.row.columns[self.index_mapping[77]],
                    &self.row.columns[self.index_mapping[78]],
                    &self.row.columns[self.index_mapping[79]],
                    &self.row.columns[self.index_mapping[80]],
                    &self.row.columns[self.index_mapping[81]],
                    &self.row.columns[self.index_mapping[82]],
                    &self.row.columns[self.index_mapping[83]],
                    &self.row.columns[self.index_mapping[84]],
                    &self.row.columns[self.index_mapping[85]],
                    &self.row.columns[self.index_mapping[86]],
                    &self.row.columns[self.index_mapping[87]],
                    &self.row.columns[self.index_mapping[88]],
                    &self.row.columns[self.index_mapping[89]],
                    &self.row.columns[self.index_mapping[90]],
                    &self.row.columns[self.index_mapping[91]],
                    &self.row.columns[self.index_mapping[92]],
                    &self.row.columns[self.index_mapping[93]],
                    &self.row.columns[self.index_mapping[94]],
                    &self.row.columns[self.index_mapping[95]],
                    &self.row.columns[self.index_mapping[96]],
                    &self.row.columns[self.index_mapping[97]],
                    &self.row.columns[self.index_mapping[98]],
                    &self.row.columns[self.index_mapping[99]],
                    &self.row.columns[self.index_mapping[100]],
                    &self.row.columns[self.index_mapping[101]],
                    &self.row.columns[self.index_mapping[102]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[103]],
                    &self.row.columns[self.index_mapping[104]],
                    &self.row.columns[self.index_mapping[105]],
                    &self.row.columns[self.index_mapping[106]],
                    &self.row.columns[self.index_mapping[107]],
                    &self.row.columns[self.index_mapping[108]],
                ],
                InitVal: &self.row.columns[self.index_mapping[109]],
                SubMenuType: &self.row.columns[self.index_mapping[110]],
                SubMenuNum: &self.row.columns[self.index_mapping[111]],
                LookAt: &self.row.columns[self.index_mapping[112]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[113]],
                    &self.row.columns[self.index_mapping[114]],
                    &self.row.columns[self.index_mapping[115]],
                    &self.row.columns[self.index_mapping[116]],
                    &self.row.columns[self.index_mapping[117]],
                    &self.row.columns[self.index_mapping[118]],
                    &self.row.columns[self.index_mapping[119]],
                    &self.row.columns[self.index_mapping[120]],
                    &self.row.columns[self.index_mapping[121]],
                    &self.row.columns[self.index_mapping[122]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[123]],
                SubMenuMask: &self.row.columns[self.index_mapping[124]],
                Customize: &self.row.columns[self.index_mapping[125]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[126]],
                    &self.row.columns[self.index_mapping[127]],
                    &self.row.columns[self.index_mapping[128]],
                    &self.row.columns[self.index_mapping[129]],
                    &self.row.columns[self.index_mapping[130]],
                    &self.row.columns[self.index_mapping[131]],
                    &self.row.columns[self.index_mapping[132]],
                    &self.row.columns[self.index_mapping[133]],
                    &self.row.columns[self.index_mapping[134]],
                    &self.row.columns[self.index_mapping[135]],
                    &self.row.columns[self.index_mapping[136]],
                    &self.row.columns[self.index_mapping[137]],
                    &self.row.columns[self.index_mapping[138]],
                    &self.row.columns[self.index_mapping[139]],
                    &self.row.columns[self.index_mapping[140]],
                    &self.row.columns[self.index_mapping[141]],
                    &self.row.columns[self.index_mapping[142]],
                    &self.row.columns[self.index_mapping[143]],
                    &self.row.columns[self.index_mapping[144]],
                    &self.row.columns[self.index_mapping[145]],
                    &self.row.columns[self.index_mapping[146]],
                    &self.row.columns[self.index_mapping[147]],
                    &self.row.columns[self.index_mapping[148]],
                    &self.row.columns[self.index_mapping[149]],
                    &self.row.columns[self.index_mapping[150]],
                    &self.row.columns[self.index_mapping[151]],
                    &self.row.columns[self.index_mapping[152]],
                    &self.row.columns[self.index_mapping[153]],
                    &self.row.columns[self.index_mapping[154]],
                    &self.row.columns[self.index_mapping[155]],
                    &self.row.columns[self.index_mapping[156]],
                    &self.row.columns[self.index_mapping[157]],
                    &self.row.columns[self.index_mapping[158]],
                    &self.row.columns[self.index_mapping[159]],
                    &self.row.columns[self.index_mapping[160]],
                    &self.row.columns[self.index_mapping[161]],
                    &self.row.columns[self.index_mapping[162]],
                    &self.row.columns[self.index_mapping[163]],
                    &self.row.columns[self.index_mapping[164]],
                    &self.row.columns[self.index_mapping[165]],
                    &self.row.columns[self.index_mapping[166]],
                    &self.row.columns[self.index_mapping[167]],
                    &self.row.columns[self.index_mapping[168]],
                    &self.row.columns[self.index_mapping[169]],
                    &self.row.columns[self.index_mapping[170]],
                    &self.row.columns[self.index_mapping[171]],
                    &self.row.columns[self.index_mapping[172]],
                    &self.row.columns[self.index_mapping[173]],
                    &self.row.columns[self.index_mapping[174]],
                    &self.row.columns[self.index_mapping[175]],
                    &self.row.columns[self.index_mapping[176]],
                    &self.row.columns[self.index_mapping[177]],
                    &self.row.columns[self.index_mapping[178]],
                    &self.row.columns[self.index_mapping[179]],
                    &self.row.columns[self.index_mapping[180]],
                    &self.row.columns[self.index_mapping[181]],
                    &self.row.columns[self.index_mapping[182]],
                    &self.row.columns[self.index_mapping[183]],
                    &self.row.columns[self.index_mapping[184]],
                    &self.row.columns[self.index_mapping[185]],
                    &self.row.columns[self.index_mapping[186]],
                    &self.row.columns[self.index_mapping[187]],
                    &self.row.columns[self.index_mapping[188]],
                    &self.row.columns[self.index_mapping[189]],
                    &self.row.columns[self.index_mapping[190]],
                    &self.row.columns[self.index_mapping[191]],
                    &self.row.columns[self.index_mapping[192]],
                    &self.row.columns[self.index_mapping[193]],
                    &self.row.columns[self.index_mapping[194]],
                    &self.row.columns[self.index_mapping[195]],
                    &self.row.columns[self.index_mapping[196]],
                    &self.row.columns[self.index_mapping[197]],
                    &self.row.columns[self.index_mapping[198]],
                    &self.row.columns[self.index_mapping[199]],
                    &self.row.columns[self.index_mapping[200]],
                    &self.row.columns[self.index_mapping[201]],
                    &self.row.columns[self.index_mapping[202]],
                    &self.row.columns[self.index_mapping[203]],
                    &self.row.columns[self.index_mapping[204]],
                    &self.row.columns[self.index_mapping[205]],
                    &self.row.columns[self.index_mapping[206]],
                    &self.row.columns[self.index_mapping[207]],
                    &self.row.columns[self.index_mapping[208]],
                    &self.row.columns[self.index_mapping[209]],
                    &self.row.columns[self.index_mapping[210]],
                    &self.row.columns[self.index_mapping[211]],
                    &self.row.columns[self.index_mapping[212]],
                    &self.row.columns[self.index_mapping[213]],
                    &self.row.columns[self.index_mapping[214]],
                    &self.row.columns[self.index_mapping[215]],
                    &self.row.columns[self.index_mapping[216]],
                    &self.row.columns[self.index_mapping[217]],
                    &self.row.columns[self.index_mapping[218]],
                    &self.row.columns[self.index_mapping[219]],
                    &self.row.columns[self.index_mapping[220]],
                    &self.row.columns[self.index_mapping[221]],
                    &self.row.columns[self.index_mapping[222]],
                    &self.row.columns[self.index_mapping[223]],
                    &self.row.columns[self.index_mapping[224]],
                    &self.row.columns[self.index_mapping[225]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[226]],
                    &self.row.columns[self.index_mapping[227]],
                    &self.row.columns[self.index_mapping[228]],
                    &self.row.columns[self.index_mapping[229]],
                    &self.row.columns[self.index_mapping[230]],
                    &self.row.columns[self.index_mapping[231]],
                ],
                InitVal: &self.row.columns[self.index_mapping[232]],
                SubMenuType: &self.row.columns[self.index_mapping[233]],
                SubMenuNum: &self.row.columns[self.index_mapping[234]],
                LookAt: &self.row.columns[self.index_mapping[235]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[236]],
                    &self.row.columns[self.index_mapping[237]],
                    &self.row.columns[self.index_mapping[238]],
                    &self.row.columns[self.index_mapping[239]],
                    &self.row.columns[self.index_mapping[240]],
                    &self.row.columns[self.index_mapping[241]],
                    &self.row.columns[self.index_mapping[242]],
                    &self.row.columns[self.index_mapping[243]],
                    &self.row.columns[self.index_mapping[244]],
                    &self.row.columns[self.index_mapping[245]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[246]],
                SubMenuMask: &self.row.columns[self.index_mapping[247]],
                Customize: &self.row.columns[self.index_mapping[248]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[249]],
                    &self.row.columns[self.index_mapping[250]],
                    &self.row.columns[self.index_mapping[251]],
                    &self.row.columns[self.index_mapping[252]],
                    &self.row.columns[self.index_mapping[253]],
                    &self.row.columns[self.index_mapping[254]],
                    &self.row.columns[self.index_mapping[255]],
                    &self.row.columns[self.index_mapping[256]],
                    &self.row.columns[self.index_mapping[257]],
                    &self.row.columns[self.index_mapping[258]],
                    &self.row.columns[self.index_mapping[259]],
                    &self.row.columns[self.index_mapping[260]],
                    &self.row.columns[self.index_mapping[261]],
                    &self.row.columns[self.index_mapping[262]],
                    &self.row.columns[self.index_mapping[263]],
                    &self.row.columns[self.index_mapping[264]],
                    &self.row.columns[self.index_mapping[265]],
                    &self.row.columns[self.index_mapping[266]],
                    &self.row.columns[self.index_mapping[267]],
                    &self.row.columns[self.index_mapping[268]],
                    &self.row.columns[self.index_mapping[269]],
                    &self.row.columns[self.index_mapping[270]],
                    &self.row.columns[self.index_mapping[271]],
                    &self.row.columns[self.index_mapping[272]],
                    &self.row.columns[self.index_mapping[273]],
                    &self.row.columns[self.index_mapping[274]],
                    &self.row.columns[self.index_mapping[275]],
                    &self.row.columns[self.index_mapping[276]],
                    &self.row.columns[self.index_mapping[277]],
                    &self.row.columns[self.index_mapping[278]],
                    &self.row.columns[self.index_mapping[279]],
                    &self.row.columns[self.index_mapping[280]],
                    &self.row.columns[self.index_mapping[281]],
                    &self.row.columns[self.index_mapping[282]],
                    &self.row.columns[self.index_mapping[283]],
                    &self.row.columns[self.index_mapping[284]],
                    &self.row.columns[self.index_mapping[285]],
                    &self.row.columns[self.index_mapping[286]],
                    &self.row.columns[self.index_mapping[287]],
                    &self.row.columns[self.index_mapping[288]],
                    &self.row.columns[self.index_mapping[289]],
                    &self.row.columns[self.index_mapping[290]],
                    &self.row.columns[self.index_mapping[291]],
                    &self.row.columns[self.index_mapping[292]],
                    &self.row.columns[self.index_mapping[293]],
                    &self.row.columns[self.index_mapping[294]],
                    &self.row.columns[self.index_mapping[295]],
                    &self.row.columns[self.index_mapping[296]],
                    &self.row.columns[self.index_mapping[297]],
                    &self.row.columns[self.index_mapping[298]],
                    &self.row.columns[self.index_mapping[299]],
                    &self.row.columns[self.index_mapping[300]],
                    &self.row.columns[self.index_mapping[301]],
                    &self.row.columns[self.index_mapping[302]],
                    &self.row.columns[self.index_mapping[303]],
                    &self.row.columns[self.index_mapping[304]],
                    &self.row.columns[self.index_mapping[305]],
                    &self.row.columns[self.index_mapping[306]],
                    &self.row.columns[self.index_mapping[307]],
                    &self.row.columns[self.index_mapping[308]],
                    &self.row.columns[self.index_mapping[309]],
                    &self.row.columns[self.index_mapping[310]],
                    &self.row.columns[self.index_mapping[311]],
                    &self.row.columns[self.index_mapping[312]],
                    &self.row.columns[self.index_mapping[313]],
                    &self.row.columns[self.index_mapping[314]],
                    &self.row.columns[self.index_mapping[315]],
                    &self.row.columns[self.index_mapping[316]],
                    &self.row.columns[self.index_mapping[317]],
                    &self.row.columns[self.index_mapping[318]],
                    &self.row.columns[self.index_mapping[319]],
                    &self.row.columns[self.index_mapping[320]],
                    &self.row.columns[self.index_mapping[321]],
                    &self.row.columns[self.index_mapping[322]],
                    &self.row.columns[self.index_mapping[323]],
                    &self.row.columns[self.index_mapping[324]],
                    &self.row.columns[self.index_mapping[325]],
                    &self.row.columns[self.index_mapping[326]],
                    &self.row.columns[self.index_mapping[327]],
                    &self.row.columns[self.index_mapping[328]],
                    &self.row.columns[self.index_mapping[329]],
                    &self.row.columns[self.index_mapping[330]],
                    &self.row.columns[self.index_mapping[331]],
                    &self.row.columns[self.index_mapping[332]],
                    &self.row.columns[self.index_mapping[333]],
                    &self.row.columns[self.index_mapping[334]],
                    &self.row.columns[self.index_mapping[335]],
                    &self.row.columns[self.index_mapping[336]],
                    &self.row.columns[self.index_mapping[337]],
                    &self.row.columns[self.index_mapping[338]],
                    &self.row.columns[self.index_mapping[339]],
                    &self.row.columns[self.index_mapping[340]],
                    &self.row.columns[self.index_mapping[341]],
                    &self.row.columns[self.index_mapping[342]],
                    &self.row.columns[self.index_mapping[343]],
                    &self.row.columns[self.index_mapping[344]],
                    &self.row.columns[self.index_mapping[345]],
                    &self.row.columns[self.index_mapping[346]],
                    &self.row.columns[self.index_mapping[347]],
                    &self.row.columns[self.index_mapping[348]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[349]],
                    &self.row.columns[self.index_mapping[350]],
                    &self.row.columns[self.index_mapping[351]],
                    &self.row.columns[self.index_mapping[352]],
                    &self.row.columns[self.index_mapping[353]],
                    &self.row.columns[self.index_mapping[354]],
                ],
                InitVal: &self.row.columns[self.index_mapping[355]],
                SubMenuType: &self.row.columns[self.index_mapping[356]],
                SubMenuNum: &self.row.columns[self.index_mapping[357]],
                LookAt: &self.row.columns[self.index_mapping[358]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[359]],
                    &self.row.columns[self.index_mapping[360]],
                    &self.row.columns[self.index_mapping[361]],
                    &self.row.columns[self.index_mapping[362]],
                    &self.row.columns[self.index_mapping[363]],
                    &self.row.columns[self.index_mapping[364]],
                    &self.row.columns[self.index_mapping[365]],
                    &self.row.columns[self.index_mapping[366]],
                    &self.row.columns[self.index_mapping[367]],
                    &self.row.columns[self.index_mapping[368]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[369]],
                SubMenuMask: &self.row.columns[self.index_mapping[370]],
                Customize: &self.row.columns[self.index_mapping[371]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[372]],
                    &self.row.columns[self.index_mapping[373]],
                    &self.row.columns[self.index_mapping[374]],
                    &self.row.columns[self.index_mapping[375]],
                    &self.row.columns[self.index_mapping[376]],
                    &self.row.columns[self.index_mapping[377]],
                    &self.row.columns[self.index_mapping[378]],
                    &self.row.columns[self.index_mapping[379]],
                    &self.row.columns[self.index_mapping[380]],
                    &self.row.columns[self.index_mapping[381]],
                    &self.row.columns[self.index_mapping[382]],
                    &self.row.columns[self.index_mapping[383]],
                    &self.row.columns[self.index_mapping[384]],
                    &self.row.columns[self.index_mapping[385]],
                    &self.row.columns[self.index_mapping[386]],
                    &self.row.columns[self.index_mapping[387]],
                    &self.row.columns[self.index_mapping[388]],
                    &self.row.columns[self.index_mapping[389]],
                    &self.row.columns[self.index_mapping[390]],
                    &self.row.columns[self.index_mapping[391]],
                    &self.row.columns[self.index_mapping[392]],
                    &self.row.columns[self.index_mapping[393]],
                    &self.row.columns[self.index_mapping[394]],
                    &self.row.columns[self.index_mapping[395]],
                    &self.row.columns[self.index_mapping[396]],
                    &self.row.columns[self.index_mapping[397]],
                    &self.row.columns[self.index_mapping[398]],
                    &self.row.columns[self.index_mapping[399]],
                    &self.row.columns[self.index_mapping[400]],
                    &self.row.columns[self.index_mapping[401]],
                    &self.row.columns[self.index_mapping[402]],
                    &self.row.columns[self.index_mapping[403]],
                    &self.row.columns[self.index_mapping[404]],
                    &self.row.columns[self.index_mapping[405]],
                    &self.row.columns[self.index_mapping[406]],
                    &self.row.columns[self.index_mapping[407]],
                    &self.row.columns[self.index_mapping[408]],
                    &self.row.columns[self.index_mapping[409]],
                    &self.row.columns[self.index_mapping[410]],
                    &self.row.columns[self.index_mapping[411]],
                    &self.row.columns[self.index_mapping[412]],
                    &self.row.columns[self.index_mapping[413]],
                    &self.row.columns[self.index_mapping[414]],
                    &self.row.columns[self.index_mapping[415]],
                    &self.row.columns[self.index_mapping[416]],
                    &self.row.columns[self.index_mapping[417]],
                    &self.row.columns[self.index_mapping[418]],
                    &self.row.columns[self.index_mapping[419]],
                    &self.row.columns[self.index_mapping[420]],
                    &self.row.columns[self.index_mapping[421]],
                    &self.row.columns[self.index_mapping[422]],
                    &self.row.columns[self.index_mapping[423]],
                    &self.row.columns[self.index_mapping[424]],
                    &self.row.columns[self.index_mapping[425]],
                    &self.row.columns[self.index_mapping[426]],
                    &self.row.columns[self.index_mapping[427]],
                    &self.row.columns[self.index_mapping[428]],
                    &self.row.columns[self.index_mapping[429]],
                    &self.row.columns[self.index_mapping[430]],
                    &self.row.columns[self.index_mapping[431]],
                    &self.row.columns[self.index_mapping[432]],
                    &self.row.columns[self.index_mapping[433]],
                    &self.row.columns[self.index_mapping[434]],
                    &self.row.columns[self.index_mapping[435]],
                    &self.row.columns[self.index_mapping[436]],
                    &self.row.columns[self.index_mapping[437]],
                    &self.row.columns[self.index_mapping[438]],
                    &self.row.columns[self.index_mapping[439]],
                    &self.row.columns[self.index_mapping[440]],
                    &self.row.columns[self.index_mapping[441]],
                    &self.row.columns[self.index_mapping[442]],
                    &self.row.columns[self.index_mapping[443]],
                    &self.row.columns[self.index_mapping[444]],
                    &self.row.columns[self.index_mapping[445]],
                    &self.row.columns[self.index_mapping[446]],
                    &self.row.columns[self.index_mapping[447]],
                    &self.row.columns[self.index_mapping[448]],
                    &self.row.columns[self.index_mapping[449]],
                    &self.row.columns[self.index_mapping[450]],
                    &self.row.columns[self.index_mapping[451]],
                    &self.row.columns[self.index_mapping[452]],
                    &self.row.columns[self.index_mapping[453]],
                    &self.row.columns[self.index_mapping[454]],
                    &self.row.columns[self.index_mapping[455]],
                    &self.row.columns[self.index_mapping[456]],
                    &self.row.columns[self.index_mapping[457]],
                    &self.row.columns[self.index_mapping[458]],
                    &self.row.columns[self.index_mapping[459]],
                    &self.row.columns[self.index_mapping[460]],
                    &self.row.columns[self.index_mapping[461]],
                    &self.row.columns[self.index_mapping[462]],
                    &self.row.columns[self.index_mapping[463]],
                    &self.row.columns[self.index_mapping[464]],
                    &self.row.columns[self.index_mapping[465]],
                    &self.row.columns[self.index_mapping[466]],
                    &self.row.columns[self.index_mapping[467]],
                    &self.row.columns[self.index_mapping[468]],
                    &self.row.columns[self.index_mapping[469]],
                    &self.row.columns[self.index_mapping[470]],
                    &self.row.columns[self.index_mapping[471]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[472]],
                    &self.row.columns[self.index_mapping[473]],
                    &self.row.columns[self.index_mapping[474]],
                    &self.row.columns[self.index_mapping[475]],
                    &self.row.columns[self.index_mapping[476]],
                    &self.row.columns[self.index_mapping[477]],
                ],
                InitVal: &self.row.columns[self.index_mapping[478]],
                SubMenuType: &self.row.columns[self.index_mapping[479]],
                SubMenuNum: &self.row.columns[self.index_mapping[480]],
                LookAt: &self.row.columns[self.index_mapping[481]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[482]],
                    &self.row.columns[self.index_mapping[483]],
                    &self.row.columns[self.index_mapping[484]],
                    &self.row.columns[self.index_mapping[485]],
                    &self.row.columns[self.index_mapping[486]],
                    &self.row.columns[self.index_mapping[487]],
                    &self.row.columns[self.index_mapping[488]],
                    &self.row.columns[self.index_mapping[489]],
                    &self.row.columns[self.index_mapping[490]],
                    &self.row.columns[self.index_mapping[491]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[492]],
                SubMenuMask: &self.row.columns[self.index_mapping[493]],
                Customize: &self.row.columns[self.index_mapping[494]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[495]],
                    &self.row.columns[self.index_mapping[496]],
                    &self.row.columns[self.index_mapping[497]],
                    &self.row.columns[self.index_mapping[498]],
                    &self.row.columns[self.index_mapping[499]],
                    &self.row.columns[self.index_mapping[500]],
                    &self.row.columns[self.index_mapping[501]],
                    &self.row.columns[self.index_mapping[502]],
                    &self.row.columns[self.index_mapping[503]],
                    &self.row.columns[self.index_mapping[504]],
                    &self.row.columns[self.index_mapping[505]],
                    &self.row.columns[self.index_mapping[506]],
                    &self.row.columns[self.index_mapping[507]],
                    &self.row.columns[self.index_mapping[508]],
                    &self.row.columns[self.index_mapping[509]],
                    &self.row.columns[self.index_mapping[510]],
                    &self.row.columns[self.index_mapping[511]],
                    &self.row.columns[self.index_mapping[512]],
                    &self.row.columns[self.index_mapping[513]],
                    &self.row.columns[self.index_mapping[514]],
                    &self.row.columns[self.index_mapping[515]],
                    &self.row.columns[self.index_mapping[516]],
                    &self.row.columns[self.index_mapping[517]],
                    &self.row.columns[self.index_mapping[518]],
                    &self.row.columns[self.index_mapping[519]],
                    &self.row.columns[self.index_mapping[520]],
                    &self.row.columns[self.index_mapping[521]],
                    &self.row.columns[self.index_mapping[522]],
                    &self.row.columns[self.index_mapping[523]],
                    &self.row.columns[self.index_mapping[524]],
                    &self.row.columns[self.index_mapping[525]],
                    &self.row.columns[self.index_mapping[526]],
                    &self.row.columns[self.index_mapping[527]],
                    &self.row.columns[self.index_mapping[528]],
                    &self.row.columns[self.index_mapping[529]],
                    &self.row.columns[self.index_mapping[530]],
                    &self.row.columns[self.index_mapping[531]],
                    &self.row.columns[self.index_mapping[532]],
                    &self.row.columns[self.index_mapping[533]],
                    &self.row.columns[self.index_mapping[534]],
                    &self.row.columns[self.index_mapping[535]],
                    &self.row.columns[self.index_mapping[536]],
                    &self.row.columns[self.index_mapping[537]],
                    &self.row.columns[self.index_mapping[538]],
                    &self.row.columns[self.index_mapping[539]],
                    &self.row.columns[self.index_mapping[540]],
                    &self.row.columns[self.index_mapping[541]],
                    &self.row.columns[self.index_mapping[542]],
                    &self.row.columns[self.index_mapping[543]],
                    &self.row.columns[self.index_mapping[544]],
                    &self.row.columns[self.index_mapping[545]],
                    &self.row.columns[self.index_mapping[546]],
                    &self.row.columns[self.index_mapping[547]],
                    &self.row.columns[self.index_mapping[548]],
                    &self.row.columns[self.index_mapping[549]],
                    &self.row.columns[self.index_mapping[550]],
                    &self.row.columns[self.index_mapping[551]],
                    &self.row.columns[self.index_mapping[552]],
                    &self.row.columns[self.index_mapping[553]],
                    &self.row.columns[self.index_mapping[554]],
                    &self.row.columns[self.index_mapping[555]],
                    &self.row.columns[self.index_mapping[556]],
                    &self.row.columns[self.index_mapping[557]],
                    &self.row.columns[self.index_mapping[558]],
                    &self.row.columns[self.index_mapping[559]],
                    &self.row.columns[self.index_mapping[560]],
                    &self.row.columns[self.index_mapping[561]],
                    &self.row.columns[self.index_mapping[562]],
                    &self.row.columns[self.index_mapping[563]],
                    &self.row.columns[self.index_mapping[564]],
                    &self.row.columns[self.index_mapping[565]],
                    &self.row.columns[self.index_mapping[566]],
                    &self.row.columns[self.index_mapping[567]],
                    &self.row.columns[self.index_mapping[568]],
                    &self.row.columns[self.index_mapping[569]],
                    &self.row.columns[self.index_mapping[570]],
                    &self.row.columns[self.index_mapping[571]],
                    &self.row.columns[self.index_mapping[572]],
                    &self.row.columns[self.index_mapping[573]],
                    &self.row.columns[self.index_mapping[574]],
                    &self.row.columns[self.index_mapping[575]],
                    &self.row.columns[self.index_mapping[576]],
                    &self.row.columns[self.index_mapping[577]],
                    &self.row.columns[self.index_mapping[578]],
                    &self.row.columns[self.index_mapping[579]],
                    &self.row.columns[self.index_mapping[580]],
                    &self.row.columns[self.index_mapping[581]],
                    &self.row.columns[self.index_mapping[582]],
                    &self.row.columns[self.index_mapping[583]],
                    &self.row.columns[self.index_mapping[584]],
                    &self.row.columns[self.index_mapping[585]],
                    &self.row.columns[self.index_mapping[586]],
                    &self.row.columns[self.index_mapping[587]],
                    &self.row.columns[self.index_mapping[588]],
                    &self.row.columns[self.index_mapping[589]],
                    &self.row.columns[self.index_mapping[590]],
                    &self.row.columns[self.index_mapping[591]],
                    &self.row.columns[self.index_mapping[592]],
                    &self.row.columns[self.index_mapping[593]],
                    &self.row.columns[self.index_mapping[594]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[595]],
                    &self.row.columns[self.index_mapping[596]],
                    &self.row.columns[self.index_mapping[597]],
                    &self.row.columns[self.index_mapping[598]],
                    &self.row.columns[self.index_mapping[599]],
                    &self.row.columns[self.index_mapping[600]],
                ],
                InitVal: &self.row.columns[self.index_mapping[601]],
                SubMenuType: &self.row.columns[self.index_mapping[602]],
                SubMenuNum: &self.row.columns[self.index_mapping[603]],
                LookAt: &self.row.columns[self.index_mapping[604]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[605]],
                    &self.row.columns[self.index_mapping[606]],
                    &self.row.columns[self.index_mapping[607]],
                    &self.row.columns[self.index_mapping[608]],
                    &self.row.columns[self.index_mapping[609]],
                    &self.row.columns[self.index_mapping[610]],
                    &self.row.columns[self.index_mapping[611]],
                    &self.row.columns[self.index_mapping[612]],
                    &self.row.columns[self.index_mapping[613]],
                    &self.row.columns[self.index_mapping[614]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[615]],
                SubMenuMask: &self.row.columns[self.index_mapping[616]],
                Customize: &self.row.columns[self.index_mapping[617]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[618]],
                    &self.row.columns[self.index_mapping[619]],
                    &self.row.columns[self.index_mapping[620]],
                    &self.row.columns[self.index_mapping[621]],
                    &self.row.columns[self.index_mapping[622]],
                    &self.row.columns[self.index_mapping[623]],
                    &self.row.columns[self.index_mapping[624]],
                    &self.row.columns[self.index_mapping[625]],
                    &self.row.columns[self.index_mapping[626]],
                    &self.row.columns[self.index_mapping[627]],
                    &self.row.columns[self.index_mapping[628]],
                    &self.row.columns[self.index_mapping[629]],
                    &self.row.columns[self.index_mapping[630]],
                    &self.row.columns[self.index_mapping[631]],
                    &self.row.columns[self.index_mapping[632]],
                    &self.row.columns[self.index_mapping[633]],
                    &self.row.columns[self.index_mapping[634]],
                    &self.row.columns[self.index_mapping[635]],
                    &self.row.columns[self.index_mapping[636]],
                    &self.row.columns[self.index_mapping[637]],
                    &self.row.columns[self.index_mapping[638]],
                    &self.row.columns[self.index_mapping[639]],
                    &self.row.columns[self.index_mapping[640]],
                    &self.row.columns[self.index_mapping[641]],
                    &self.row.columns[self.index_mapping[642]],
                    &self.row.columns[self.index_mapping[643]],
                    &self.row.columns[self.index_mapping[644]],
                    &self.row.columns[self.index_mapping[645]],
                    &self.row.columns[self.index_mapping[646]],
                    &self.row.columns[self.index_mapping[647]],
                    &self.row.columns[self.index_mapping[648]],
                    &self.row.columns[self.index_mapping[649]],
                    &self.row.columns[self.index_mapping[650]],
                    &self.row.columns[self.index_mapping[651]],
                    &self.row.columns[self.index_mapping[652]],
                    &self.row.columns[self.index_mapping[653]],
                    &self.row.columns[self.index_mapping[654]],
                    &self.row.columns[self.index_mapping[655]],
                    &self.row.columns[self.index_mapping[656]],
                    &self.row.columns[self.index_mapping[657]],
                    &self.row.columns[self.index_mapping[658]],
                    &self.row.columns[self.index_mapping[659]],
                    &self.row.columns[self.index_mapping[660]],
                    &self.row.columns[self.index_mapping[661]],
                    &self.row.columns[self.index_mapping[662]],
                    &self.row.columns[self.index_mapping[663]],
                    &self.row.columns[self.index_mapping[664]],
                    &self.row.columns[self.index_mapping[665]],
                    &self.row.columns[self.index_mapping[666]],
                    &self.row.columns[self.index_mapping[667]],
                    &self.row.columns[self.index_mapping[668]],
                    &self.row.columns[self.index_mapping[669]],
                    &self.row.columns[self.index_mapping[670]],
                    &self.row.columns[self.index_mapping[671]],
                    &self.row.columns[self.index_mapping[672]],
                    &self.row.columns[self.index_mapping[673]],
                    &self.row.columns[self.index_mapping[674]],
                    &self.row.columns[self.index_mapping[675]],
                    &self.row.columns[self.index_mapping[676]],
                    &self.row.columns[self.index_mapping[677]],
                    &self.row.columns[self.index_mapping[678]],
                    &self.row.columns[self.index_mapping[679]],
                    &self.row.columns[self.index_mapping[680]],
                    &self.row.columns[self.index_mapping[681]],
                    &self.row.columns[self.index_mapping[682]],
                    &self.row.columns[self.index_mapping[683]],
                    &self.row.columns[self.index_mapping[684]],
                    &self.row.columns[self.index_mapping[685]],
                    &self.row.columns[self.index_mapping[686]],
                    &self.row.columns[self.index_mapping[687]],
                    &self.row.columns[self.index_mapping[688]],
                    &self.row.columns[self.index_mapping[689]],
                    &self.row.columns[self.index_mapping[690]],
                    &self.row.columns[self.index_mapping[691]],
                    &self.row.columns[self.index_mapping[692]],
                    &self.row.columns[self.index_mapping[693]],
                    &self.row.columns[self.index_mapping[694]],
                    &self.row.columns[self.index_mapping[695]],
                    &self.row.columns[self.index_mapping[696]],
                    &self.row.columns[self.index_mapping[697]],
                    &self.row.columns[self.index_mapping[698]],
                    &self.row.columns[self.index_mapping[699]],
                    &self.row.columns[self.index_mapping[700]],
                    &self.row.columns[self.index_mapping[701]],
                    &self.row.columns[self.index_mapping[702]],
                    &self.row.columns[self.index_mapping[703]],
                    &self.row.columns[self.index_mapping[704]],
                    &self.row.columns[self.index_mapping[705]],
                    &self.row.columns[self.index_mapping[706]],
                    &self.row.columns[self.index_mapping[707]],
                    &self.row.columns[self.index_mapping[708]],
                    &self.row.columns[self.index_mapping[709]],
                    &self.row.columns[self.index_mapping[710]],
                    &self.row.columns[self.index_mapping[711]],
                    &self.row.columns[self.index_mapping[712]],
                    &self.row.columns[self.index_mapping[713]],
                    &self.row.columns[self.index_mapping[714]],
                    &self.row.columns[self.index_mapping[715]],
                    &self.row.columns[self.index_mapping[716]],
                    &self.row.columns[self.index_mapping[717]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[718]],
                    &self.row.columns[self.index_mapping[719]],
                    &self.row.columns[self.index_mapping[720]],
                    &self.row.columns[self.index_mapping[721]],
                    &self.row.columns[self.index_mapping[722]],
                    &self.row.columns[self.index_mapping[723]],
                ],
                InitVal: &self.row.columns[self.index_mapping[724]],
                SubMenuType: &self.row.columns[self.index_mapping[725]],
                SubMenuNum: &self.row.columns[self.index_mapping[726]],
                LookAt: &self.row.columns[self.index_mapping[727]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[728]],
                    &self.row.columns[self.index_mapping[729]],
                    &self.row.columns[self.index_mapping[730]],
                    &self.row.columns[self.index_mapping[731]],
                    &self.row.columns[self.index_mapping[732]],
                    &self.row.columns[self.index_mapping[733]],
                    &self.row.columns[self.index_mapping[734]],
                    &self.row.columns[self.index_mapping[735]],
                    &self.row.columns[self.index_mapping[736]],
                    &self.row.columns[self.index_mapping[737]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[738]],
                SubMenuMask: &self.row.columns[self.index_mapping[739]],
                Customize: &self.row.columns[self.index_mapping[740]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[741]],
                    &self.row.columns[self.index_mapping[742]],
                    &self.row.columns[self.index_mapping[743]],
                    &self.row.columns[self.index_mapping[744]],
                    &self.row.columns[self.index_mapping[745]],
                    &self.row.columns[self.index_mapping[746]],
                    &self.row.columns[self.index_mapping[747]],
                    &self.row.columns[self.index_mapping[748]],
                    &self.row.columns[self.index_mapping[749]],
                    &self.row.columns[self.index_mapping[750]],
                    &self.row.columns[self.index_mapping[751]],
                    &self.row.columns[self.index_mapping[752]],
                    &self.row.columns[self.index_mapping[753]],
                    &self.row.columns[self.index_mapping[754]],
                    &self.row.columns[self.index_mapping[755]],
                    &self.row.columns[self.index_mapping[756]],
                    &self.row.columns[self.index_mapping[757]],
                    &self.row.columns[self.index_mapping[758]],
                    &self.row.columns[self.index_mapping[759]],
                    &self.row.columns[self.index_mapping[760]],
                    &self.row.columns[self.index_mapping[761]],
                    &self.row.columns[self.index_mapping[762]],
                    &self.row.columns[self.index_mapping[763]],
                    &self.row.columns[self.index_mapping[764]],
                    &self.row.columns[self.index_mapping[765]],
                    &self.row.columns[self.index_mapping[766]],
                    &self.row.columns[self.index_mapping[767]],
                    &self.row.columns[self.index_mapping[768]],
                    &self.row.columns[self.index_mapping[769]],
                    &self.row.columns[self.index_mapping[770]],
                    &self.row.columns[self.index_mapping[771]],
                    &self.row.columns[self.index_mapping[772]],
                    &self.row.columns[self.index_mapping[773]],
                    &self.row.columns[self.index_mapping[774]],
                    &self.row.columns[self.index_mapping[775]],
                    &self.row.columns[self.index_mapping[776]],
                    &self.row.columns[self.index_mapping[777]],
                    &self.row.columns[self.index_mapping[778]],
                    &self.row.columns[self.index_mapping[779]],
                    &self.row.columns[self.index_mapping[780]],
                    &self.row.columns[self.index_mapping[781]],
                    &self.row.columns[self.index_mapping[782]],
                    &self.row.columns[self.index_mapping[783]],
                    &self.row.columns[self.index_mapping[784]],
                    &self.row.columns[self.index_mapping[785]],
                    &self.row.columns[self.index_mapping[786]],
                    &self.row.columns[self.index_mapping[787]],
                    &self.row.columns[self.index_mapping[788]],
                    &self.row.columns[self.index_mapping[789]],
                    &self.row.columns[self.index_mapping[790]],
                    &self.row.columns[self.index_mapping[791]],
                    &self.row.columns[self.index_mapping[792]],
                    &self.row.columns[self.index_mapping[793]],
                    &self.row.columns[self.index_mapping[794]],
                    &self.row.columns[self.index_mapping[795]],
                    &self.row.columns[self.index_mapping[796]],
                    &self.row.columns[self.index_mapping[797]],
                    &self.row.columns[self.index_mapping[798]],
                    &self.row.columns[self.index_mapping[799]],
                    &self.row.columns[self.index_mapping[800]],
                    &self.row.columns[self.index_mapping[801]],
                    &self.row.columns[self.index_mapping[802]],
                    &self.row.columns[self.index_mapping[803]],
                    &self.row.columns[self.index_mapping[804]],
                    &self.row.columns[self.index_mapping[805]],
                    &self.row.columns[self.index_mapping[806]],
                    &self.row.columns[self.index_mapping[807]],
                    &self.row.columns[self.index_mapping[808]],
                    &self.row.columns[self.index_mapping[809]],
                    &self.row.columns[self.index_mapping[810]],
                    &self.row.columns[self.index_mapping[811]],
                    &self.row.columns[self.index_mapping[812]],
                    &self.row.columns[self.index_mapping[813]],
                    &self.row.columns[self.index_mapping[814]],
                    &self.row.columns[self.index_mapping[815]],
                    &self.row.columns[self.index_mapping[816]],
                    &self.row.columns[self.index_mapping[817]],
                    &self.row.columns[self.index_mapping[818]],
                    &self.row.columns[self.index_mapping[819]],
                    &self.row.columns[self.index_mapping[820]],
                    &self.row.columns[self.index_mapping[821]],
                    &self.row.columns[self.index_mapping[822]],
                    &self.row.columns[self.index_mapping[823]],
                    &self.row.columns[self.index_mapping[824]],
                    &self.row.columns[self.index_mapping[825]],
                    &self.row.columns[self.index_mapping[826]],
                    &self.row.columns[self.index_mapping[827]],
                    &self.row.columns[self.index_mapping[828]],
                    &self.row.columns[self.index_mapping[829]],
                    &self.row.columns[self.index_mapping[830]],
                    &self.row.columns[self.index_mapping[831]],
                    &self.row.columns[self.index_mapping[832]],
                    &self.row.columns[self.index_mapping[833]],
                    &self.row.columns[self.index_mapping[834]],
                    &self.row.columns[self.index_mapping[835]],
                    &self.row.columns[self.index_mapping[836]],
                    &self.row.columns[self.index_mapping[837]],
                    &self.row.columns[self.index_mapping[838]],
                    &self.row.columns[self.index_mapping[839]],
                    &self.row.columns[self.index_mapping[840]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[841]],
                    &self.row.columns[self.index_mapping[842]],
                    &self.row.columns[self.index_mapping[843]],
                    &self.row.columns[self.index_mapping[844]],
                    &self.row.columns[self.index_mapping[845]],
                    &self.row.columns[self.index_mapping[846]],
                ],
                InitVal: &self.row.columns[self.index_mapping[847]],
                SubMenuType: &self.row.columns[self.index_mapping[848]],
                SubMenuNum: &self.row.columns[self.index_mapping[849]],
                LookAt: &self.row.columns[self.index_mapping[850]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[851]],
                    &self.row.columns[self.index_mapping[852]],
                    &self.row.columns[self.index_mapping[853]],
                    &self.row.columns[self.index_mapping[854]],
                    &self.row.columns[self.index_mapping[855]],
                    &self.row.columns[self.index_mapping[856]],
                    &self.row.columns[self.index_mapping[857]],
                    &self.row.columns[self.index_mapping[858]],
                    &self.row.columns[self.index_mapping[859]],
                    &self.row.columns[self.index_mapping[860]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[861]],
                SubMenuMask: &self.row.columns[self.index_mapping[862]],
                Customize: &self.row.columns[self.index_mapping[863]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[864]],
                    &self.row.columns[self.index_mapping[865]],
                    &self.row.columns[self.index_mapping[866]],
                    &self.row.columns[self.index_mapping[867]],
                    &self.row.columns[self.index_mapping[868]],
                    &self.row.columns[self.index_mapping[869]],
                    &self.row.columns[self.index_mapping[870]],
                    &self.row.columns[self.index_mapping[871]],
                    &self.row.columns[self.index_mapping[872]],
                    &self.row.columns[self.index_mapping[873]],
                    &self.row.columns[self.index_mapping[874]],
                    &self.row.columns[self.index_mapping[875]],
                    &self.row.columns[self.index_mapping[876]],
                    &self.row.columns[self.index_mapping[877]],
                    &self.row.columns[self.index_mapping[878]],
                    &self.row.columns[self.index_mapping[879]],
                    &self.row.columns[self.index_mapping[880]],
                    &self.row.columns[self.index_mapping[881]],
                    &self.row.columns[self.index_mapping[882]],
                    &self.row.columns[self.index_mapping[883]],
                    &self.row.columns[self.index_mapping[884]],
                    &self.row.columns[self.index_mapping[885]],
                    &self.row.columns[self.index_mapping[886]],
                    &self.row.columns[self.index_mapping[887]],
                    &self.row.columns[self.index_mapping[888]],
                    &self.row.columns[self.index_mapping[889]],
                    &self.row.columns[self.index_mapping[890]],
                    &self.row.columns[self.index_mapping[891]],
                    &self.row.columns[self.index_mapping[892]],
                    &self.row.columns[self.index_mapping[893]],
                    &self.row.columns[self.index_mapping[894]],
                    &self.row.columns[self.index_mapping[895]],
                    &self.row.columns[self.index_mapping[896]],
                    &self.row.columns[self.index_mapping[897]],
                    &self.row.columns[self.index_mapping[898]],
                    &self.row.columns[self.index_mapping[899]],
                    &self.row.columns[self.index_mapping[900]],
                    &self.row.columns[self.index_mapping[901]],
                    &self.row.columns[self.index_mapping[902]],
                    &self.row.columns[self.index_mapping[903]],
                    &self.row.columns[self.index_mapping[904]],
                    &self.row.columns[self.index_mapping[905]],
                    &self.row.columns[self.index_mapping[906]],
                    &self.row.columns[self.index_mapping[907]],
                    &self.row.columns[self.index_mapping[908]],
                    &self.row.columns[self.index_mapping[909]],
                    &self.row.columns[self.index_mapping[910]],
                    &self.row.columns[self.index_mapping[911]],
                    &self.row.columns[self.index_mapping[912]],
                    &self.row.columns[self.index_mapping[913]],
                    &self.row.columns[self.index_mapping[914]],
                    &self.row.columns[self.index_mapping[915]],
                    &self.row.columns[self.index_mapping[916]],
                    &self.row.columns[self.index_mapping[917]],
                    &self.row.columns[self.index_mapping[918]],
                    &self.row.columns[self.index_mapping[919]],
                    &self.row.columns[self.index_mapping[920]],
                    &self.row.columns[self.index_mapping[921]],
                    &self.row.columns[self.index_mapping[922]],
                    &self.row.columns[self.index_mapping[923]],
                    &self.row.columns[self.index_mapping[924]],
                    &self.row.columns[self.index_mapping[925]],
                    &self.row.columns[self.index_mapping[926]],
                    &self.row.columns[self.index_mapping[927]],
                    &self.row.columns[self.index_mapping[928]],
                    &self.row.columns[self.index_mapping[929]],
                    &self.row.columns[self.index_mapping[930]],
                    &self.row.columns[self.index_mapping[931]],
                    &self.row.columns[self.index_mapping[932]],
                    &self.row.columns[self.index_mapping[933]],
                    &self.row.columns[self.index_mapping[934]],
                    &self.row.columns[self.index_mapping[935]],
                    &self.row.columns[self.index_mapping[936]],
                    &self.row.columns[self.index_mapping[937]],
                    &self.row.columns[self.index_mapping[938]],
                    &self.row.columns[self.index_mapping[939]],
                    &self.row.columns[self.index_mapping[940]],
                    &self.row.columns[self.index_mapping[941]],
                    &self.row.columns[self.index_mapping[942]],
                    &self.row.columns[self.index_mapping[943]],
                    &self.row.columns[self.index_mapping[944]],
                    &self.row.columns[self.index_mapping[945]],
                    &self.row.columns[self.index_mapping[946]],
                    &self.row.columns[self.index_mapping[947]],
                    &self.row.columns[self.index_mapping[948]],
                    &self.row.columns[self.index_mapping[949]],
                    &self.row.columns[self.index_mapping[950]],
                    &self.row.columns[self.index_mapping[951]],
                    &self.row.columns[self.index_mapping[952]],
                    &self.row.columns[self.index_mapping[953]],
                    &self.row.columns[self.index_mapping[954]],
                    &self.row.columns[self.index_mapping[955]],
                    &self.row.columns[self.index_mapping[956]],
                    &self.row.columns[self.index_mapping[957]],
                    &self.row.columns[self.index_mapping[958]],
                    &self.row.columns[self.index_mapping[959]],
                    &self.row.columns[self.index_mapping[960]],
                    &self.row.columns[self.index_mapping[961]],
                    &self.row.columns[self.index_mapping[962]],
                    &self.row.columns[self.index_mapping[963]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[964]],
                    &self.row.columns[self.index_mapping[965]],
                    &self.row.columns[self.index_mapping[966]],
                    &self.row.columns[self.index_mapping[967]],
                    &self.row.columns[self.index_mapping[968]],
                    &self.row.columns[self.index_mapping[969]],
                ],
                InitVal: &self.row.columns[self.index_mapping[970]],
                SubMenuType: &self.row.columns[self.index_mapping[971]],
                SubMenuNum: &self.row.columns[self.index_mapping[972]],
                LookAt: &self.row.columns[self.index_mapping[973]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[974]],
                    &self.row.columns[self.index_mapping[975]],
                    &self.row.columns[self.index_mapping[976]],
                    &self.row.columns[self.index_mapping[977]],
                    &self.row.columns[self.index_mapping[978]],
                    &self.row.columns[self.index_mapping[979]],
                    &self.row.columns[self.index_mapping[980]],
                    &self.row.columns[self.index_mapping[981]],
                    &self.row.columns[self.index_mapping[982]],
                    &self.row.columns[self.index_mapping[983]],
                ],
            },
            CharaMakeStructElement {
                Menu: &self.row.columns[self.index_mapping[984]],
                SubMenuMask: &self.row.columns[self.index_mapping[985]],
                Customize: &self.row.columns[self.index_mapping[986]],
                SubMenuParam: [
                    &self.row.columns[self.index_mapping[987]],
                    &self.row.columns[self.index_mapping[988]],
                    &self.row.columns[self.index_mapping[989]],
                    &self.row.columns[self.index_mapping[990]],
                    &self.row.columns[self.index_mapping[991]],
                    &self.row.columns[self.index_mapping[992]],
                    &self.row.columns[self.index_mapping[993]],
                    &self.row.columns[self.index_mapping[994]],
                    &self.row.columns[self.index_mapping[995]],
                    &self.row.columns[self.index_mapping[996]],
                    &self.row.columns[self.index_mapping[997]],
                    &self.row.columns[self.index_mapping[998]],
                    &self.row.columns[self.index_mapping[999]],
                    &self.row.columns[self.index_mapping[1000]],
                    &self.row.columns[self.index_mapping[1001]],
                    &self.row.columns[self.index_mapping[1002]],
                    &self.row.columns[self.index_mapping[1003]],
                    &self.row.columns[self.index_mapping[1004]],
                    &self.row.columns[self.index_mapping[1005]],
                    &self.row.columns[self.index_mapping[1006]],
                    &self.row.columns[self.index_mapping[1007]],
                    &self.row.columns[self.index_mapping[1008]],
                    &self.row.columns[self.index_mapping[1009]],
                    &self.row.columns[self.index_mapping[1010]],
                    &self.row.columns[self.index_mapping[1011]],
                    &self.row.columns[self.index_mapping[1012]],
                    &self.row.columns[self.index_mapping[1013]],
                    &self.row.columns[self.index_mapping[1014]],
                    &self.row.columns[self.index_mapping[1015]],
                    &self.row.columns[self.index_mapping[1016]],
                    &self.row.columns[self.index_mapping[1017]],
                    &self.row.columns[self.index_mapping[1018]],
                    &self.row.columns[self.index_mapping[1019]],
                    &self.row.columns[self.index_mapping[1020]],
                    &self.row.columns[self.index_mapping[1021]],
                    &self.row.columns[self.index_mapping[1022]],
                    &self.row.columns[self.index_mapping[1023]],
                    &self.row.columns[self.index_mapping[1024]],
                    &self.row.columns[self.index_mapping[1025]],
                    &self.row.columns[self.index_mapping[1026]],
                    &self.row.columns[self.index_mapping[1027]],
                    &self.row.columns[self.index_mapping[1028]],
                    &self.row.columns[self.index_mapping[1029]],
                    &self.row.columns[self.index_mapping[1030]],
                    &self.row.columns[self.index_mapping[1031]],
                    &self.row.columns[self.index_mapping[1032]],
                    &self.row.columns[self.index_mapping[1033]],
                    &self.row.columns[self.index_mapping[1034]],
                    &self.row.columns[self.index_mapping[1035]],
                    &self.row.columns[self.index_mapping[1036]],
                    &self.row.columns[self.index_mapping[1037]],
                    &self.row.columns[self.index_mapping[1038]],
                    &self.row.columns[self.index_mapping[1039]],
                    &self.row.columns[self.index_mapping[1040]],
                    &self.row.columns[self.index_mapping[1041]],
                    &self.row.columns[self.index_mapping[1042]],
                    &self.row.columns[self.index_mapping[1043]],
                    &self.row.columns[self.index_mapping[1044]],
                    &self.row.columns[self.index_mapping[1045]],
                    &self.row.columns[self.index_mapping[1046]],
                    &self.row.columns[self.index_mapping[1047]],
                    &self.row.columns[self.index_mapping[1048]],
                    &self.row.columns[self.index_mapping[1049]],
                    &self.row.columns[self.index_mapping[1050]],
                    &self.row.columns[self.index_mapping[1051]],
                    &self.row.columns[self.index_mapping[1052]],
                    &self.row.columns[self.index_mapping[1053]],
                    &self.row.columns[self.index_mapping[1054]],
                    &self.row.columns[self.index_mapping[1055]],
                    &self.row.columns[self.index_mapping[1056]],
                    &self.row.columns[self.index_mapping[1057]],
                    &self.row.columns[self.index_mapping[1058]],
                    &self.row.columns[self.index_mapping[1059]],
                    &self.row.columns[self.index_mapping[1060]],
                    &self.row.columns[self.index_mapping[1061]],
                    &self.row.columns[self.index_mapping[1062]],
                    &self.row.columns[self.index_mapping[1063]],
                    &self.row.columns[self.index_mapping[1064]],
                    &self.row.columns[self.index_mapping[1065]],
                    &self.row.columns[self.index_mapping[1066]],
                    &self.row.columns[self.index_mapping[1067]],
                    &self.row.columns[self.index_mapping[1068]],
                    &self.row.columns[self.index_mapping[1069]],
                    &self.row.columns[self.index_mapping[1070]],
                    &self.row.columns[self.index_mapping[1071]],
                    &self.row.columns[self.index_mapping[1072]],
                    &self.row.columns[self.index_mapping[1073]],
                    &self.row.columns[self.index_mapping[1074]],
                    &self.row.columns[self.index_mapping[1075]],
                    &self.row.columns[self.index_mapping[1076]],
                    &self.row.columns[self.index_mapping[1077]],
                    &self.row.columns[self.index_mapping[1078]],
                    &self.row.columns[self.index_mapping[1079]],
                    &self.row.columns[self.index_mapping[1080]],
                    &self.row.columns[self.index_mapping[1081]],
                    &self.row.columns[self.index_mapping[1082]],
                    &self.row.columns[self.index_mapping[1083]],
                    &self.row.columns[self.index_mapping[1084]],
                    &self.row.columns[self.index_mapping[1085]],
                    &self.row.columns[self.index_mapping[1086]],
                ],
                Unknown0: [
                    &self.row.columns[self.index_mapping[1087]],
                    &self.row.columns[self.index_mapping[1088]],
                    &self.row.columns[self.index_mapping[1089]],
                    &self.row.columns[self.index_mapping[1090]],
                    &self.row.columns[self.index_mapping[1091]],
                    &self.row.columns[self.index_mapping[1092]],
                ],
                InitVal: &self.row.columns[self.index_mapping[1093]],
                SubMenuType: &self.row.columns[self.index_mapping[1094]],
                SubMenuNum: &self.row.columns[self.index_mapping[1095]],
                LookAt: &self.row.columns[self.index_mapping[1096]],
                SubMenuGraphic: [
                    &self.row.columns[self.index_mapping[1097]],
                    &self.row.columns[self.index_mapping[1098]],
                    &self.row.columns[self.index_mapping[1099]],
                    &self.row.columns[self.index_mapping[1100]],
                    &self.row.columns[self.index_mapping[1101]],
                    &self.row.columns[self.index_mapping[1102]],
                    &self.row.columns[self.index_mapping[1103]],
                    &self.row.columns[self.index_mapping[1104]],
                    &self.row.columns[self.index_mapping[1105]],
                    &self.row.columns[self.index_mapping[1106]],
                ],
            },
        ]
    }
    pub fn FacialFeatureOption(&'a self) -> [FacialFeatureOptionElement<'a>; 8] {
        [
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1107]],
                Option2: &self.row.columns[self.index_mapping[1108]],
                Option3: &self.row.columns[self.index_mapping[1109]],
                Option4: &self.row.columns[self.index_mapping[1110]],
                Option5: &self.row.columns[self.index_mapping[1111]],
                Option6: &self.row.columns[self.index_mapping[1112]],
                Option7: &self.row.columns[self.index_mapping[1113]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1114]],
                Option2: &self.row.columns[self.index_mapping[1115]],
                Option3: &self.row.columns[self.index_mapping[1116]],
                Option4: &self.row.columns[self.index_mapping[1117]],
                Option5: &self.row.columns[self.index_mapping[1118]],
                Option6: &self.row.columns[self.index_mapping[1119]],
                Option7: &self.row.columns[self.index_mapping[1120]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1121]],
                Option2: &self.row.columns[self.index_mapping[1122]],
                Option3: &self.row.columns[self.index_mapping[1123]],
                Option4: &self.row.columns[self.index_mapping[1124]],
                Option5: &self.row.columns[self.index_mapping[1125]],
                Option6: &self.row.columns[self.index_mapping[1126]],
                Option7: &self.row.columns[self.index_mapping[1127]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1128]],
                Option2: &self.row.columns[self.index_mapping[1129]],
                Option3: &self.row.columns[self.index_mapping[1130]],
                Option4: &self.row.columns[self.index_mapping[1131]],
                Option5: &self.row.columns[self.index_mapping[1132]],
                Option6: &self.row.columns[self.index_mapping[1133]],
                Option7: &self.row.columns[self.index_mapping[1134]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1135]],
                Option2: &self.row.columns[self.index_mapping[1136]],
                Option3: &self.row.columns[self.index_mapping[1137]],
                Option4: &self.row.columns[self.index_mapping[1138]],
                Option5: &self.row.columns[self.index_mapping[1139]],
                Option6: &self.row.columns[self.index_mapping[1140]],
                Option7: &self.row.columns[self.index_mapping[1141]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1142]],
                Option2: &self.row.columns[self.index_mapping[1143]],
                Option3: &self.row.columns[self.index_mapping[1144]],
                Option4: &self.row.columns[self.index_mapping[1145]],
                Option5: &self.row.columns[self.index_mapping[1146]],
                Option6: &self.row.columns[self.index_mapping[1147]],
                Option7: &self.row.columns[self.index_mapping[1148]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1149]],
                Option2: &self.row.columns[self.index_mapping[1150]],
                Option3: &self.row.columns[self.index_mapping[1151]],
                Option4: &self.row.columns[self.index_mapping[1152]],
                Option5: &self.row.columns[self.index_mapping[1153]],
                Option6: &self.row.columns[self.index_mapping[1154]],
                Option7: &self.row.columns[self.index_mapping[1155]],
            },
            FacialFeatureOptionElement {
                Option1: &self.row.columns[self.index_mapping[1156]],
                Option2: &self.row.columns[self.index_mapping[1157]],
                Option3: &self.row.columns[self.index_mapping[1158]],
                Option4: &self.row.columns[self.index_mapping[1159]],
                Option5: &self.row.columns[self.index_mapping[1160]],
                Option6: &self.row.columns[self.index_mapping[1161]],
                Option7: &self.row.columns[self.index_mapping[1162]],
            },
        ]
    }
    pub fn Race(&'a self) -> &'a Field {
        &self.row.columns[self.index_mapping[1163]]
    }
    pub fn Tribe(&'a self) -> &'a Field {
        &self.row.columns[self.index_mapping[1164]]
    }
    pub fn Gender(&'a self) -> &'a Field {
        &self.row.columns[self.index_mapping[1165]]
    }
}
