#![allow(warnings)]
/// This file is auto-generated! It is generated from schema from https://github.com/xivdev/EXDSchema.
use physis::{resource::{Resource, read_excel_sheet_header, read_excel_sheet}, exd::{EXD, ColumnData, ExcelRowKind, ExcelSingleRow}, exh::{EXH, ExcelColumnDefinition}, common::Language};
pub struct HWDGathererInspectionDataElement<'a> {
RequiredItem: &'a ColumnData,
FishParameter: &'a ColumnData,
ItemReceived: &'a ColumnData,
Reward: &'a ColumnData,
AmountRequired: &'a ColumnData,
Phase: &'a ColumnData,
}
pub struct HWDGathererInspectionSheet {
pages: Vec<EXD>,
exh: EXH,
row_count: u32,
}
impl HWDGathererInspectionSheet {
pub fn read_from<T: Resource>(resource: &mut T, language: Language) -> Option<Self> {
let exh = read_excel_sheet_header(resource, "HWDGathererInspection")?;
let mut pages = Vec::new();
for (i, _) in exh.pages.iter().enumerate() {
pages.push(read_excel_sheet(resource, "HWDGathererInspection", &exh, language, i)?);
}let row_count = exh.header.row_count;
Some(Self {
exh,
pages,
row_count,
})
}
fn read_row(&self, row: &ExcelSingleRow) -> Option<HWDGathererInspectionRow> {
let column_defs = &self.exh.column_definitions;
let mut zipped: Vec<_> = row.columns.clone().into_iter().zip(column_defs).collect();
zipped.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
let (columns, _): (Vec<ColumnData>, Vec<ExcelColumnDefinition> ) = zipped.into_iter().unzip();
Some(HWDGathererInspectionRow { columns })
}
/// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
pub fn get_row(&self, row_id: u32) -> Option<HWDGathererInspectionRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => row,
ExcelRowKind::SubRows(rows) => &rows.first()?.1,
};
return self.read_row(row);
}
None
}
/// Fetches the specified subrow from the sheet.
pub fn get_subrow(&self, row_id: u32, subrow_id: u16) -> Option<HWDGathererInspectionRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => return None,
ExcelRowKind::SubRows(subrows) => &subrows.iter().filter(|(id, _)| *id == subrow_id).next()?.1,
};
return self.read_row(row);
}
None
}
/// Returns the number of rows in this sheet.
pub fn row_count(&self) -> u32 {
self.row_count
}
}
pub struct HWDGathererInspectionRow {
columns: Vec<ColumnData>,
}
impl HWDGathererInspectionRow {
pub fn HWDGathererInspectionData<'a>(&'a self) -> [HWDGathererInspectionDataElement<'a>; 79] {
[HWDGathererInspectionDataElement {RequiredItem: &self.columns[0],
FishParameter: &self.columns[1],
ItemReceived: &self.columns[2],
Reward: &self.columns[3],
AmountRequired: &self.columns[4],
Phase: &self.columns[5],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[6],
FishParameter: &self.columns[7],
ItemReceived: &self.columns[8],
Reward: &self.columns[9],
AmountRequired: &self.columns[10],
Phase: &self.columns[11],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[12],
FishParameter: &self.columns[13],
ItemReceived: &self.columns[14],
Reward: &self.columns[15],
AmountRequired: &self.columns[16],
Phase: &self.columns[17],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[18],
FishParameter: &self.columns[19],
ItemReceived: &self.columns[20],
Reward: &self.columns[21],
AmountRequired: &self.columns[22],
Phase: &self.columns[23],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[24],
FishParameter: &self.columns[25],
ItemReceived: &self.columns[26],
Reward: &self.columns[27],
AmountRequired: &self.columns[28],
Phase: &self.columns[29],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[30],
FishParameter: &self.columns[31],
ItemReceived: &self.columns[32],
Reward: &self.columns[33],
AmountRequired: &self.columns[34],
Phase: &self.columns[35],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[36],
FishParameter: &self.columns[37],
ItemReceived: &self.columns[38],
Reward: &self.columns[39],
AmountRequired: &self.columns[40],
Phase: &self.columns[41],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[42],
FishParameter: &self.columns[43],
ItemReceived: &self.columns[44],
Reward: &self.columns[45],
AmountRequired: &self.columns[46],
Phase: &self.columns[47],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[48],
FishParameter: &self.columns[49],
ItemReceived: &self.columns[50],
Reward: &self.columns[51],
AmountRequired: &self.columns[52],
Phase: &self.columns[53],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[54],
FishParameter: &self.columns[55],
ItemReceived: &self.columns[56],
Reward: &self.columns[57],
AmountRequired: &self.columns[58],
Phase: &self.columns[59],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[60],
FishParameter: &self.columns[61],
ItemReceived: &self.columns[62],
Reward: &self.columns[63],
AmountRequired: &self.columns[64],
Phase: &self.columns[65],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[66],
FishParameter: &self.columns[67],
ItemReceived: &self.columns[68],
Reward: &self.columns[69],
AmountRequired: &self.columns[70],
Phase: &self.columns[71],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[72],
FishParameter: &self.columns[73],
ItemReceived: &self.columns[74],
Reward: &self.columns[75],
AmountRequired: &self.columns[76],
Phase: &self.columns[77],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[78],
FishParameter: &self.columns[79],
ItemReceived: &self.columns[80],
Reward: &self.columns[81],
AmountRequired: &self.columns[82],
Phase: &self.columns[83],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[84],
FishParameter: &self.columns[85],
ItemReceived: &self.columns[86],
Reward: &self.columns[87],
AmountRequired: &self.columns[88],
Phase: &self.columns[89],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[90],
FishParameter: &self.columns[91],
ItemReceived: &self.columns[92],
Reward: &self.columns[93],
AmountRequired: &self.columns[94],
Phase: &self.columns[95],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[96],
FishParameter: &self.columns[97],
ItemReceived: &self.columns[98],
Reward: &self.columns[99],
AmountRequired: &self.columns[100],
Phase: &self.columns[101],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[102],
FishParameter: &self.columns[103],
ItemReceived: &self.columns[104],
Reward: &self.columns[105],
AmountRequired: &self.columns[106],
Phase: &self.columns[107],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[108],
FishParameter: &self.columns[109],
ItemReceived: &self.columns[110],
Reward: &self.columns[111],
AmountRequired: &self.columns[112],
Phase: &self.columns[113],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[114],
FishParameter: &self.columns[115],
ItemReceived: &self.columns[116],
Reward: &self.columns[117],
AmountRequired: &self.columns[118],
Phase: &self.columns[119],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[120],
FishParameter: &self.columns[121],
ItemReceived: &self.columns[122],
Reward: &self.columns[123],
AmountRequired: &self.columns[124],
Phase: &self.columns[125],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[126],
FishParameter: &self.columns[127],
ItemReceived: &self.columns[128],
Reward: &self.columns[129],
AmountRequired: &self.columns[130],
Phase: &self.columns[131],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[132],
FishParameter: &self.columns[133],
ItemReceived: &self.columns[134],
Reward: &self.columns[135],
AmountRequired: &self.columns[136],
Phase: &self.columns[137],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[138],
FishParameter: &self.columns[139],
ItemReceived: &self.columns[140],
Reward: &self.columns[141],
AmountRequired: &self.columns[142],
Phase: &self.columns[143],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[144],
FishParameter: &self.columns[145],
ItemReceived: &self.columns[146],
Reward: &self.columns[147],
AmountRequired: &self.columns[148],
Phase: &self.columns[149],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[150],
FishParameter: &self.columns[151],
ItemReceived: &self.columns[152],
Reward: &self.columns[153],
AmountRequired: &self.columns[154],
Phase: &self.columns[155],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[156],
FishParameter: &self.columns[157],
ItemReceived: &self.columns[158],
Reward: &self.columns[159],
AmountRequired: &self.columns[160],
Phase: &self.columns[161],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[162],
FishParameter: &self.columns[163],
ItemReceived: &self.columns[164],
Reward: &self.columns[165],
AmountRequired: &self.columns[166],
Phase: &self.columns[167],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[168],
FishParameter: &self.columns[169],
ItemReceived: &self.columns[170],
Reward: &self.columns[171],
AmountRequired: &self.columns[172],
Phase: &self.columns[173],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[174],
FishParameter: &self.columns[175],
ItemReceived: &self.columns[176],
Reward: &self.columns[177],
AmountRequired: &self.columns[178],
Phase: &self.columns[179],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[180],
FishParameter: &self.columns[181],
ItemReceived: &self.columns[182],
Reward: &self.columns[183],
AmountRequired: &self.columns[184],
Phase: &self.columns[185],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[186],
FishParameter: &self.columns[187],
ItemReceived: &self.columns[188],
Reward: &self.columns[189],
AmountRequired: &self.columns[190],
Phase: &self.columns[191],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[192],
FishParameter: &self.columns[193],
ItemReceived: &self.columns[194],
Reward: &self.columns[195],
AmountRequired: &self.columns[196],
Phase: &self.columns[197],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[198],
FishParameter: &self.columns[199],
ItemReceived: &self.columns[200],
Reward: &self.columns[201],
AmountRequired: &self.columns[202],
Phase: &self.columns[203],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[204],
FishParameter: &self.columns[205],
ItemReceived: &self.columns[206],
Reward: &self.columns[207],
AmountRequired: &self.columns[208],
Phase: &self.columns[209],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[210],
FishParameter: &self.columns[211],
ItemReceived: &self.columns[212],
Reward: &self.columns[213],
AmountRequired: &self.columns[214],
Phase: &self.columns[215],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[216],
FishParameter: &self.columns[217],
ItemReceived: &self.columns[218],
Reward: &self.columns[219],
AmountRequired: &self.columns[220],
Phase: &self.columns[221],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[222],
FishParameter: &self.columns[223],
ItemReceived: &self.columns[224],
Reward: &self.columns[225],
AmountRequired: &self.columns[226],
Phase: &self.columns[227],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[228],
FishParameter: &self.columns[229],
ItemReceived: &self.columns[230],
Reward: &self.columns[231],
AmountRequired: &self.columns[232],
Phase: &self.columns[233],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[234],
FishParameter: &self.columns[235],
ItemReceived: &self.columns[236],
Reward: &self.columns[237],
AmountRequired: &self.columns[238],
Phase: &self.columns[239],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[240],
FishParameter: &self.columns[241],
ItemReceived: &self.columns[242],
Reward: &self.columns[243],
AmountRequired: &self.columns[244],
Phase: &self.columns[245],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[246],
FishParameter: &self.columns[247],
ItemReceived: &self.columns[248],
Reward: &self.columns[249],
AmountRequired: &self.columns[250],
Phase: &self.columns[251],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[252],
FishParameter: &self.columns[253],
ItemReceived: &self.columns[254],
Reward: &self.columns[255],
AmountRequired: &self.columns[256],
Phase: &self.columns[257],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[258],
FishParameter: &self.columns[259],
ItemReceived: &self.columns[260],
Reward: &self.columns[261],
AmountRequired: &self.columns[262],
Phase: &self.columns[263],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[264],
FishParameter: &self.columns[265],
ItemReceived: &self.columns[266],
Reward: &self.columns[267],
AmountRequired: &self.columns[268],
Phase: &self.columns[269],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[270],
FishParameter: &self.columns[271],
ItemReceived: &self.columns[272],
Reward: &self.columns[273],
AmountRequired: &self.columns[274],
Phase: &self.columns[275],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[276],
FishParameter: &self.columns[277],
ItemReceived: &self.columns[278],
Reward: &self.columns[279],
AmountRequired: &self.columns[280],
Phase: &self.columns[281],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[282],
FishParameter: &self.columns[283],
ItemReceived: &self.columns[284],
Reward: &self.columns[285],
AmountRequired: &self.columns[286],
Phase: &self.columns[287],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[288],
FishParameter: &self.columns[289],
ItemReceived: &self.columns[290],
Reward: &self.columns[291],
AmountRequired: &self.columns[292],
Phase: &self.columns[293],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[294],
FishParameter: &self.columns[295],
ItemReceived: &self.columns[296],
Reward: &self.columns[297],
AmountRequired: &self.columns[298],
Phase: &self.columns[299],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[300],
FishParameter: &self.columns[301],
ItemReceived: &self.columns[302],
Reward: &self.columns[303],
AmountRequired: &self.columns[304],
Phase: &self.columns[305],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[306],
FishParameter: &self.columns[307],
ItemReceived: &self.columns[308],
Reward: &self.columns[309],
AmountRequired: &self.columns[310],
Phase: &self.columns[311],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[312],
FishParameter: &self.columns[313],
ItemReceived: &self.columns[314],
Reward: &self.columns[315],
AmountRequired: &self.columns[316],
Phase: &self.columns[317],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[318],
FishParameter: &self.columns[319],
ItemReceived: &self.columns[320],
Reward: &self.columns[321],
AmountRequired: &self.columns[322],
Phase: &self.columns[323],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[324],
FishParameter: &self.columns[325],
ItemReceived: &self.columns[326],
Reward: &self.columns[327],
AmountRequired: &self.columns[328],
Phase: &self.columns[329],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[330],
FishParameter: &self.columns[331],
ItemReceived: &self.columns[332],
Reward: &self.columns[333],
AmountRequired: &self.columns[334],
Phase: &self.columns[335],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[336],
FishParameter: &self.columns[337],
ItemReceived: &self.columns[338],
Reward: &self.columns[339],
AmountRequired: &self.columns[340],
Phase: &self.columns[341],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[342],
FishParameter: &self.columns[343],
ItemReceived: &self.columns[344],
Reward: &self.columns[345],
AmountRequired: &self.columns[346],
Phase: &self.columns[347],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[348],
FishParameter: &self.columns[349],
ItemReceived: &self.columns[350],
Reward: &self.columns[351],
AmountRequired: &self.columns[352],
Phase: &self.columns[353],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[354],
FishParameter: &self.columns[355],
ItemReceived: &self.columns[356],
Reward: &self.columns[357],
AmountRequired: &self.columns[358],
Phase: &self.columns[359],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[360],
FishParameter: &self.columns[361],
ItemReceived: &self.columns[362],
Reward: &self.columns[363],
AmountRequired: &self.columns[364],
Phase: &self.columns[365],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[366],
FishParameter: &self.columns[367],
ItemReceived: &self.columns[368],
Reward: &self.columns[369],
AmountRequired: &self.columns[370],
Phase: &self.columns[371],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[372],
FishParameter: &self.columns[373],
ItemReceived: &self.columns[374],
Reward: &self.columns[375],
AmountRequired: &self.columns[376],
Phase: &self.columns[377],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[378],
FishParameter: &self.columns[379],
ItemReceived: &self.columns[380],
Reward: &self.columns[381],
AmountRequired: &self.columns[382],
Phase: &self.columns[383],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[384],
FishParameter: &self.columns[385],
ItemReceived: &self.columns[386],
Reward: &self.columns[387],
AmountRequired: &self.columns[388],
Phase: &self.columns[389],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[390],
FishParameter: &self.columns[391],
ItemReceived: &self.columns[392],
Reward: &self.columns[393],
AmountRequired: &self.columns[394],
Phase: &self.columns[395],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[396],
FishParameter: &self.columns[397],
ItemReceived: &self.columns[398],
Reward: &self.columns[399],
AmountRequired: &self.columns[400],
Phase: &self.columns[401],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[402],
FishParameter: &self.columns[403],
ItemReceived: &self.columns[404],
Reward: &self.columns[405],
AmountRequired: &self.columns[406],
Phase: &self.columns[407],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[408],
FishParameter: &self.columns[409],
ItemReceived: &self.columns[410],
Reward: &self.columns[411],
AmountRequired: &self.columns[412],
Phase: &self.columns[413],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[414],
FishParameter: &self.columns[415],
ItemReceived: &self.columns[416],
Reward: &self.columns[417],
AmountRequired: &self.columns[418],
Phase: &self.columns[419],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[420],
FishParameter: &self.columns[421],
ItemReceived: &self.columns[422],
Reward: &self.columns[423],
AmountRequired: &self.columns[424],
Phase: &self.columns[425],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[426],
FishParameter: &self.columns[427],
ItemReceived: &self.columns[428],
Reward: &self.columns[429],
AmountRequired: &self.columns[430],
Phase: &self.columns[431],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[432],
FishParameter: &self.columns[433],
ItemReceived: &self.columns[434],
Reward: &self.columns[435],
AmountRequired: &self.columns[436],
Phase: &self.columns[437],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[438],
FishParameter: &self.columns[439],
ItemReceived: &self.columns[440],
Reward: &self.columns[441],
AmountRequired: &self.columns[442],
Phase: &self.columns[443],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[444],
FishParameter: &self.columns[445],
ItemReceived: &self.columns[446],
Reward: &self.columns[447],
AmountRequired: &self.columns[448],
Phase: &self.columns[449],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[450],
FishParameter: &self.columns[451],
ItemReceived: &self.columns[452],
Reward: &self.columns[453],
AmountRequired: &self.columns[454],
Phase: &self.columns[455],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[456],
FishParameter: &self.columns[457],
ItemReceived: &self.columns[458],
Reward: &self.columns[459],
AmountRequired: &self.columns[460],
Phase: &self.columns[461],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[462],
FishParameter: &self.columns[463],
ItemReceived: &self.columns[464],
Reward: &self.columns[465],
AmountRequired: &self.columns[466],
Phase: &self.columns[467],
},
HWDGathererInspectionDataElement {RequiredItem: &self.columns[468],
FishParameter: &self.columns[469],
ItemReceived: &self.columns[470],
Reward: &self.columns[471],
AmountRequired: &self.columns[472],
Phase: &self.columns[473],
},
]
}
}
