//! This file is auto-generated, do not edit it manually! This is generated based on the schema from https://github.com/xivdev/EXDSchema.
#![allow(warnings)]
use physis::{
    Error, resource::{Resource, ResourceResolver},
    exd::EXD, exh::{EXH, ExcelColumnDefinition},
    excel::{ExcelSheet, ColumnData, ExcelRowKind, ExcelSingleRow},
    common::Language,
};
pub struct ItemElement<'a> {
    pub ReceiveCount: [&'a ColumnData; 2],
    pub CurrencyCost: [&'a ColumnData; 3],
    pub Item: [&'a ColumnData; 2],
    pub Category: [&'a ColumnData; 2],
    pub ItemCost: [&'a ColumnData; 3],
    pub Quest: &'a ColumnData,
    pub Unknown0: [&'a ColumnData; 4],
    pub AchievementUnlock: &'a ColumnData,
    pub Unknown2: &'a ColumnData,
    pub CollectabilityCost: [&'a ColumnData; 3],
    pub PatchNumber: &'a ColumnData,
    pub HqCost: [&'a ColumnData; 3],
    pub Unknown1: [&'a ColumnData; 5],
    pub Order: &'a ColumnData,
    pub ReceiveHq: [&'a ColumnData; 2],
}
#[derive(Debug, Clone)]
pub struct SpecialShopSheet {
    sheet: ExcelSheet,
}
impl SpecialShopSheet {
    /// Read the sheet from a `ResourceResolver`.
    pub fn read_from(
        resolver: &mut ResourceResolver,
        language: Language,
    ) -> Result<Self, Error> {
        let exh = resolver.read_excel_sheet_header("SpecialShop")?;
        let sheet = resolver.read_excel_sheet(exh, "SpecialShop", language)?;
        Ok(Self { sheet })
    }
    fn read_row(&self, row: &ExcelSingleRow) -> Option<SpecialShopRow> {
        let column_defs = &self.sheet.exh.column_definitions;
        let mut zipped: Vec<_> = row
            .columns
            .clone()
            .into_iter()
            .zip(column_defs)
            .collect();
        zipped.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
        let (columns, _): (Vec<ColumnData>, Vec<ExcelColumnDefinition>) = zipped
            .into_iter()
            .unzip();
        Some(SpecialShopRow { columns })
    }
    /// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
    pub fn get_row(&self, row_id: u32) -> Option<SpecialShopRow> {
        let row = &self.sheet.get_row(row_id)?;
        let row = match row {
            ExcelRowKind::SingleRow(row) => row,
            ExcelRowKind::SubRows(rows) => &rows.first()?.1,
        };
        self.read_row(row)
    }
    /// Fetches the specified subrow from the sheet.
    pub fn get_subrow(&self, row_id: u32, subrow_id: u16) -> Option<SpecialShopRow> {
        let row = &self.sheet.get_row(row_id)?;
        let row = match row {
            ExcelRowKind::SingleRow(row) => return None,
            ExcelRowKind::SubRows(subrows) => {
                &subrows.iter().filter(|(id, _)| *id == subrow_id).next()?.1
            }
        };
        self.read_row(row)
    }
    /// Returns the number of rows in this sheet.
    pub fn row_count(&self) -> u32 {
        self.sheet.exh.header.row_count
    }
}
pub struct SpecialShopRow {
    columns: Vec<ColumnData>,
}
impl SpecialShopRow {
    pub fn Name<'a>(&'a self) -> &'a ColumnData {
        &self.columns[0]
    }
    pub fn Item<'a>(&'a self) -> [ItemElement<'a>; 60] {
        [
            ItemElement {
                ReceiveCount: [&self.columns[1], &self.columns[2]],
                CurrencyCost: [&self.columns[3], &self.columns[4], &self.columns[5]],
                Item: [&self.columns[6], &self.columns[7]],
                Category: [&self.columns[8], &self.columns[9]],
                ItemCost: [&self.columns[10], &self.columns[11], &self.columns[12]],
                Quest: &self.columns[13],
                Unknown0: [
                    &self.columns[14],
                    &self.columns[15],
                    &self.columns[16],
                    &self.columns[17],
                ],
                AchievementUnlock: &self.columns[18],
                Unknown2: &self.columns[19],
                CollectabilityCost: [
                    &self.columns[20],
                    &self.columns[21],
                    &self.columns[22],
                ],
                PatchNumber: &self.columns[23],
                HqCost: [&self.columns[24], &self.columns[25], &self.columns[26]],
                Unknown1: [
                    &self.columns[27],
                    &self.columns[28],
                    &self.columns[29],
                    &self.columns[30],
                    &self.columns[31],
                ],
                Order: &self.columns[32],
                ReceiveHq: [&self.columns[33], &self.columns[34]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[35], &self.columns[36]],
                CurrencyCost: [&self.columns[37], &self.columns[38], &self.columns[39]],
                Item: [&self.columns[40], &self.columns[41]],
                Category: [&self.columns[42], &self.columns[43]],
                ItemCost: [&self.columns[44], &self.columns[45], &self.columns[46]],
                Quest: &self.columns[47],
                Unknown0: [
                    &self.columns[48],
                    &self.columns[49],
                    &self.columns[50],
                    &self.columns[51],
                ],
                AchievementUnlock: &self.columns[52],
                Unknown2: &self.columns[53],
                CollectabilityCost: [
                    &self.columns[54],
                    &self.columns[55],
                    &self.columns[56],
                ],
                PatchNumber: &self.columns[57],
                HqCost: [&self.columns[58], &self.columns[59], &self.columns[60]],
                Unknown1: [
                    &self.columns[61],
                    &self.columns[62],
                    &self.columns[63],
                    &self.columns[64],
                    &self.columns[65],
                ],
                Order: &self.columns[66],
                ReceiveHq: [&self.columns[67], &self.columns[68]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[69], &self.columns[70]],
                CurrencyCost: [&self.columns[71], &self.columns[72], &self.columns[73]],
                Item: [&self.columns[74], &self.columns[75]],
                Category: [&self.columns[76], &self.columns[77]],
                ItemCost: [&self.columns[78], &self.columns[79], &self.columns[80]],
                Quest: &self.columns[81],
                Unknown0: [
                    &self.columns[82],
                    &self.columns[83],
                    &self.columns[84],
                    &self.columns[85],
                ],
                AchievementUnlock: &self.columns[86],
                Unknown2: &self.columns[87],
                CollectabilityCost: [
                    &self.columns[88],
                    &self.columns[89],
                    &self.columns[90],
                ],
                PatchNumber: &self.columns[91],
                HqCost: [&self.columns[92], &self.columns[93], &self.columns[94]],
                Unknown1: [
                    &self.columns[95],
                    &self.columns[96],
                    &self.columns[97],
                    &self.columns[98],
                    &self.columns[99],
                ],
                Order: &self.columns[100],
                ReceiveHq: [&self.columns[101], &self.columns[102]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[103], &self.columns[104]],
                CurrencyCost: [
                    &self.columns[105],
                    &self.columns[106],
                    &self.columns[107],
                ],
                Item: [&self.columns[108], &self.columns[109]],
                Category: [&self.columns[110], &self.columns[111]],
                ItemCost: [&self.columns[112], &self.columns[113], &self.columns[114]],
                Quest: &self.columns[115],
                Unknown0: [
                    &self.columns[116],
                    &self.columns[117],
                    &self.columns[118],
                    &self.columns[119],
                ],
                AchievementUnlock: &self.columns[120],
                Unknown2: &self.columns[121],
                CollectabilityCost: [
                    &self.columns[122],
                    &self.columns[123],
                    &self.columns[124],
                ],
                PatchNumber: &self.columns[125],
                HqCost: [&self.columns[126], &self.columns[127], &self.columns[128]],
                Unknown1: [
                    &self.columns[129],
                    &self.columns[130],
                    &self.columns[131],
                    &self.columns[132],
                    &self.columns[133],
                ],
                Order: &self.columns[134],
                ReceiveHq: [&self.columns[135], &self.columns[136]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[137], &self.columns[138]],
                CurrencyCost: [
                    &self.columns[139],
                    &self.columns[140],
                    &self.columns[141],
                ],
                Item: [&self.columns[142], &self.columns[143]],
                Category: [&self.columns[144], &self.columns[145]],
                ItemCost: [&self.columns[146], &self.columns[147], &self.columns[148]],
                Quest: &self.columns[149],
                Unknown0: [
                    &self.columns[150],
                    &self.columns[151],
                    &self.columns[152],
                    &self.columns[153],
                ],
                AchievementUnlock: &self.columns[154],
                Unknown2: &self.columns[155],
                CollectabilityCost: [
                    &self.columns[156],
                    &self.columns[157],
                    &self.columns[158],
                ],
                PatchNumber: &self.columns[159],
                HqCost: [&self.columns[160], &self.columns[161], &self.columns[162]],
                Unknown1: [
                    &self.columns[163],
                    &self.columns[164],
                    &self.columns[165],
                    &self.columns[166],
                    &self.columns[167],
                ],
                Order: &self.columns[168],
                ReceiveHq: [&self.columns[169], &self.columns[170]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[171], &self.columns[172]],
                CurrencyCost: [
                    &self.columns[173],
                    &self.columns[174],
                    &self.columns[175],
                ],
                Item: [&self.columns[176], &self.columns[177]],
                Category: [&self.columns[178], &self.columns[179]],
                ItemCost: [&self.columns[180], &self.columns[181], &self.columns[182]],
                Quest: &self.columns[183],
                Unknown0: [
                    &self.columns[184],
                    &self.columns[185],
                    &self.columns[186],
                    &self.columns[187],
                ],
                AchievementUnlock: &self.columns[188],
                Unknown2: &self.columns[189],
                CollectabilityCost: [
                    &self.columns[190],
                    &self.columns[191],
                    &self.columns[192],
                ],
                PatchNumber: &self.columns[193],
                HqCost: [&self.columns[194], &self.columns[195], &self.columns[196]],
                Unknown1: [
                    &self.columns[197],
                    &self.columns[198],
                    &self.columns[199],
                    &self.columns[200],
                    &self.columns[201],
                ],
                Order: &self.columns[202],
                ReceiveHq: [&self.columns[203], &self.columns[204]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[205], &self.columns[206]],
                CurrencyCost: [
                    &self.columns[207],
                    &self.columns[208],
                    &self.columns[209],
                ],
                Item: [&self.columns[210], &self.columns[211]],
                Category: [&self.columns[212], &self.columns[213]],
                ItemCost: [&self.columns[214], &self.columns[215], &self.columns[216]],
                Quest: &self.columns[217],
                Unknown0: [
                    &self.columns[218],
                    &self.columns[219],
                    &self.columns[220],
                    &self.columns[221],
                ],
                AchievementUnlock: &self.columns[222],
                Unknown2: &self.columns[223],
                CollectabilityCost: [
                    &self.columns[224],
                    &self.columns[225],
                    &self.columns[226],
                ],
                PatchNumber: &self.columns[227],
                HqCost: [&self.columns[228], &self.columns[229], &self.columns[230]],
                Unknown1: [
                    &self.columns[231],
                    &self.columns[232],
                    &self.columns[233],
                    &self.columns[234],
                    &self.columns[235],
                ],
                Order: &self.columns[236],
                ReceiveHq: [&self.columns[237], &self.columns[238]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[239], &self.columns[240]],
                CurrencyCost: [
                    &self.columns[241],
                    &self.columns[242],
                    &self.columns[243],
                ],
                Item: [&self.columns[244], &self.columns[245]],
                Category: [&self.columns[246], &self.columns[247]],
                ItemCost: [&self.columns[248], &self.columns[249], &self.columns[250]],
                Quest: &self.columns[251],
                Unknown0: [
                    &self.columns[252],
                    &self.columns[253],
                    &self.columns[254],
                    &self.columns[255],
                ],
                AchievementUnlock: &self.columns[256],
                Unknown2: &self.columns[257],
                CollectabilityCost: [
                    &self.columns[258],
                    &self.columns[259],
                    &self.columns[260],
                ],
                PatchNumber: &self.columns[261],
                HqCost: [&self.columns[262], &self.columns[263], &self.columns[264]],
                Unknown1: [
                    &self.columns[265],
                    &self.columns[266],
                    &self.columns[267],
                    &self.columns[268],
                    &self.columns[269],
                ],
                Order: &self.columns[270],
                ReceiveHq: [&self.columns[271], &self.columns[272]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[273], &self.columns[274]],
                CurrencyCost: [
                    &self.columns[275],
                    &self.columns[276],
                    &self.columns[277],
                ],
                Item: [&self.columns[278], &self.columns[279]],
                Category: [&self.columns[280], &self.columns[281]],
                ItemCost: [&self.columns[282], &self.columns[283], &self.columns[284]],
                Quest: &self.columns[285],
                Unknown0: [
                    &self.columns[286],
                    &self.columns[287],
                    &self.columns[288],
                    &self.columns[289],
                ],
                AchievementUnlock: &self.columns[290],
                Unknown2: &self.columns[291],
                CollectabilityCost: [
                    &self.columns[292],
                    &self.columns[293],
                    &self.columns[294],
                ],
                PatchNumber: &self.columns[295],
                HqCost: [&self.columns[296], &self.columns[297], &self.columns[298]],
                Unknown1: [
                    &self.columns[299],
                    &self.columns[300],
                    &self.columns[301],
                    &self.columns[302],
                    &self.columns[303],
                ],
                Order: &self.columns[304],
                ReceiveHq: [&self.columns[305], &self.columns[306]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[307], &self.columns[308]],
                CurrencyCost: [
                    &self.columns[309],
                    &self.columns[310],
                    &self.columns[311],
                ],
                Item: [&self.columns[312], &self.columns[313]],
                Category: [&self.columns[314], &self.columns[315]],
                ItemCost: [&self.columns[316], &self.columns[317], &self.columns[318]],
                Quest: &self.columns[319],
                Unknown0: [
                    &self.columns[320],
                    &self.columns[321],
                    &self.columns[322],
                    &self.columns[323],
                ],
                AchievementUnlock: &self.columns[324],
                Unknown2: &self.columns[325],
                CollectabilityCost: [
                    &self.columns[326],
                    &self.columns[327],
                    &self.columns[328],
                ],
                PatchNumber: &self.columns[329],
                HqCost: [&self.columns[330], &self.columns[331], &self.columns[332]],
                Unknown1: [
                    &self.columns[333],
                    &self.columns[334],
                    &self.columns[335],
                    &self.columns[336],
                    &self.columns[337],
                ],
                Order: &self.columns[338],
                ReceiveHq: [&self.columns[339], &self.columns[340]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[341], &self.columns[342]],
                CurrencyCost: [
                    &self.columns[343],
                    &self.columns[344],
                    &self.columns[345],
                ],
                Item: [&self.columns[346], &self.columns[347]],
                Category: [&self.columns[348], &self.columns[349]],
                ItemCost: [&self.columns[350], &self.columns[351], &self.columns[352]],
                Quest: &self.columns[353],
                Unknown0: [
                    &self.columns[354],
                    &self.columns[355],
                    &self.columns[356],
                    &self.columns[357],
                ],
                AchievementUnlock: &self.columns[358],
                Unknown2: &self.columns[359],
                CollectabilityCost: [
                    &self.columns[360],
                    &self.columns[361],
                    &self.columns[362],
                ],
                PatchNumber: &self.columns[363],
                HqCost: [&self.columns[364], &self.columns[365], &self.columns[366]],
                Unknown1: [
                    &self.columns[367],
                    &self.columns[368],
                    &self.columns[369],
                    &self.columns[370],
                    &self.columns[371],
                ],
                Order: &self.columns[372],
                ReceiveHq: [&self.columns[373], &self.columns[374]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[375], &self.columns[376]],
                CurrencyCost: [
                    &self.columns[377],
                    &self.columns[378],
                    &self.columns[379],
                ],
                Item: [&self.columns[380], &self.columns[381]],
                Category: [&self.columns[382], &self.columns[383]],
                ItemCost: [&self.columns[384], &self.columns[385], &self.columns[386]],
                Quest: &self.columns[387],
                Unknown0: [
                    &self.columns[388],
                    &self.columns[389],
                    &self.columns[390],
                    &self.columns[391],
                ],
                AchievementUnlock: &self.columns[392],
                Unknown2: &self.columns[393],
                CollectabilityCost: [
                    &self.columns[394],
                    &self.columns[395],
                    &self.columns[396],
                ],
                PatchNumber: &self.columns[397],
                HqCost: [&self.columns[398], &self.columns[399], &self.columns[400]],
                Unknown1: [
                    &self.columns[401],
                    &self.columns[402],
                    &self.columns[403],
                    &self.columns[404],
                    &self.columns[405],
                ],
                Order: &self.columns[406],
                ReceiveHq: [&self.columns[407], &self.columns[408]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[409], &self.columns[410]],
                CurrencyCost: [
                    &self.columns[411],
                    &self.columns[412],
                    &self.columns[413],
                ],
                Item: [&self.columns[414], &self.columns[415]],
                Category: [&self.columns[416], &self.columns[417]],
                ItemCost: [&self.columns[418], &self.columns[419], &self.columns[420]],
                Quest: &self.columns[421],
                Unknown0: [
                    &self.columns[422],
                    &self.columns[423],
                    &self.columns[424],
                    &self.columns[425],
                ],
                AchievementUnlock: &self.columns[426],
                Unknown2: &self.columns[427],
                CollectabilityCost: [
                    &self.columns[428],
                    &self.columns[429],
                    &self.columns[430],
                ],
                PatchNumber: &self.columns[431],
                HqCost: [&self.columns[432], &self.columns[433], &self.columns[434]],
                Unknown1: [
                    &self.columns[435],
                    &self.columns[436],
                    &self.columns[437],
                    &self.columns[438],
                    &self.columns[439],
                ],
                Order: &self.columns[440],
                ReceiveHq: [&self.columns[441], &self.columns[442]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[443], &self.columns[444]],
                CurrencyCost: [
                    &self.columns[445],
                    &self.columns[446],
                    &self.columns[447],
                ],
                Item: [&self.columns[448], &self.columns[449]],
                Category: [&self.columns[450], &self.columns[451]],
                ItemCost: [&self.columns[452], &self.columns[453], &self.columns[454]],
                Quest: &self.columns[455],
                Unknown0: [
                    &self.columns[456],
                    &self.columns[457],
                    &self.columns[458],
                    &self.columns[459],
                ],
                AchievementUnlock: &self.columns[460],
                Unknown2: &self.columns[461],
                CollectabilityCost: [
                    &self.columns[462],
                    &self.columns[463],
                    &self.columns[464],
                ],
                PatchNumber: &self.columns[465],
                HqCost: [&self.columns[466], &self.columns[467], &self.columns[468]],
                Unknown1: [
                    &self.columns[469],
                    &self.columns[470],
                    &self.columns[471],
                    &self.columns[472],
                    &self.columns[473],
                ],
                Order: &self.columns[474],
                ReceiveHq: [&self.columns[475], &self.columns[476]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[477], &self.columns[478]],
                CurrencyCost: [
                    &self.columns[479],
                    &self.columns[480],
                    &self.columns[481],
                ],
                Item: [&self.columns[482], &self.columns[483]],
                Category: [&self.columns[484], &self.columns[485]],
                ItemCost: [&self.columns[486], &self.columns[487], &self.columns[488]],
                Quest: &self.columns[489],
                Unknown0: [
                    &self.columns[490],
                    &self.columns[491],
                    &self.columns[492],
                    &self.columns[493],
                ],
                AchievementUnlock: &self.columns[494],
                Unknown2: &self.columns[495],
                CollectabilityCost: [
                    &self.columns[496],
                    &self.columns[497],
                    &self.columns[498],
                ],
                PatchNumber: &self.columns[499],
                HqCost: [&self.columns[500], &self.columns[501], &self.columns[502]],
                Unknown1: [
                    &self.columns[503],
                    &self.columns[504],
                    &self.columns[505],
                    &self.columns[506],
                    &self.columns[507],
                ],
                Order: &self.columns[508],
                ReceiveHq: [&self.columns[509], &self.columns[510]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[511], &self.columns[512]],
                CurrencyCost: [
                    &self.columns[513],
                    &self.columns[514],
                    &self.columns[515],
                ],
                Item: [&self.columns[516], &self.columns[517]],
                Category: [&self.columns[518], &self.columns[519]],
                ItemCost: [&self.columns[520], &self.columns[521], &self.columns[522]],
                Quest: &self.columns[523],
                Unknown0: [
                    &self.columns[524],
                    &self.columns[525],
                    &self.columns[526],
                    &self.columns[527],
                ],
                AchievementUnlock: &self.columns[528],
                Unknown2: &self.columns[529],
                CollectabilityCost: [
                    &self.columns[530],
                    &self.columns[531],
                    &self.columns[532],
                ],
                PatchNumber: &self.columns[533],
                HqCost: [&self.columns[534], &self.columns[535], &self.columns[536]],
                Unknown1: [
                    &self.columns[537],
                    &self.columns[538],
                    &self.columns[539],
                    &self.columns[540],
                    &self.columns[541],
                ],
                Order: &self.columns[542],
                ReceiveHq: [&self.columns[543], &self.columns[544]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[545], &self.columns[546]],
                CurrencyCost: [
                    &self.columns[547],
                    &self.columns[548],
                    &self.columns[549],
                ],
                Item: [&self.columns[550], &self.columns[551]],
                Category: [&self.columns[552], &self.columns[553]],
                ItemCost: [&self.columns[554], &self.columns[555], &self.columns[556]],
                Quest: &self.columns[557],
                Unknown0: [
                    &self.columns[558],
                    &self.columns[559],
                    &self.columns[560],
                    &self.columns[561],
                ],
                AchievementUnlock: &self.columns[562],
                Unknown2: &self.columns[563],
                CollectabilityCost: [
                    &self.columns[564],
                    &self.columns[565],
                    &self.columns[566],
                ],
                PatchNumber: &self.columns[567],
                HqCost: [&self.columns[568], &self.columns[569], &self.columns[570]],
                Unknown1: [
                    &self.columns[571],
                    &self.columns[572],
                    &self.columns[573],
                    &self.columns[574],
                    &self.columns[575],
                ],
                Order: &self.columns[576],
                ReceiveHq: [&self.columns[577], &self.columns[578]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[579], &self.columns[580]],
                CurrencyCost: [
                    &self.columns[581],
                    &self.columns[582],
                    &self.columns[583],
                ],
                Item: [&self.columns[584], &self.columns[585]],
                Category: [&self.columns[586], &self.columns[587]],
                ItemCost: [&self.columns[588], &self.columns[589], &self.columns[590]],
                Quest: &self.columns[591],
                Unknown0: [
                    &self.columns[592],
                    &self.columns[593],
                    &self.columns[594],
                    &self.columns[595],
                ],
                AchievementUnlock: &self.columns[596],
                Unknown2: &self.columns[597],
                CollectabilityCost: [
                    &self.columns[598],
                    &self.columns[599],
                    &self.columns[600],
                ],
                PatchNumber: &self.columns[601],
                HqCost: [&self.columns[602], &self.columns[603], &self.columns[604]],
                Unknown1: [
                    &self.columns[605],
                    &self.columns[606],
                    &self.columns[607],
                    &self.columns[608],
                    &self.columns[609],
                ],
                Order: &self.columns[610],
                ReceiveHq: [&self.columns[611], &self.columns[612]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[613], &self.columns[614]],
                CurrencyCost: [
                    &self.columns[615],
                    &self.columns[616],
                    &self.columns[617],
                ],
                Item: [&self.columns[618], &self.columns[619]],
                Category: [&self.columns[620], &self.columns[621]],
                ItemCost: [&self.columns[622], &self.columns[623], &self.columns[624]],
                Quest: &self.columns[625],
                Unknown0: [
                    &self.columns[626],
                    &self.columns[627],
                    &self.columns[628],
                    &self.columns[629],
                ],
                AchievementUnlock: &self.columns[630],
                Unknown2: &self.columns[631],
                CollectabilityCost: [
                    &self.columns[632],
                    &self.columns[633],
                    &self.columns[634],
                ],
                PatchNumber: &self.columns[635],
                HqCost: [&self.columns[636], &self.columns[637], &self.columns[638]],
                Unknown1: [
                    &self.columns[639],
                    &self.columns[640],
                    &self.columns[641],
                    &self.columns[642],
                    &self.columns[643],
                ],
                Order: &self.columns[644],
                ReceiveHq: [&self.columns[645], &self.columns[646]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[647], &self.columns[648]],
                CurrencyCost: [
                    &self.columns[649],
                    &self.columns[650],
                    &self.columns[651],
                ],
                Item: [&self.columns[652], &self.columns[653]],
                Category: [&self.columns[654], &self.columns[655]],
                ItemCost: [&self.columns[656], &self.columns[657], &self.columns[658]],
                Quest: &self.columns[659],
                Unknown0: [
                    &self.columns[660],
                    &self.columns[661],
                    &self.columns[662],
                    &self.columns[663],
                ],
                AchievementUnlock: &self.columns[664],
                Unknown2: &self.columns[665],
                CollectabilityCost: [
                    &self.columns[666],
                    &self.columns[667],
                    &self.columns[668],
                ],
                PatchNumber: &self.columns[669],
                HqCost: [&self.columns[670], &self.columns[671], &self.columns[672]],
                Unknown1: [
                    &self.columns[673],
                    &self.columns[674],
                    &self.columns[675],
                    &self.columns[676],
                    &self.columns[677],
                ],
                Order: &self.columns[678],
                ReceiveHq: [&self.columns[679], &self.columns[680]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[681], &self.columns[682]],
                CurrencyCost: [
                    &self.columns[683],
                    &self.columns[684],
                    &self.columns[685],
                ],
                Item: [&self.columns[686], &self.columns[687]],
                Category: [&self.columns[688], &self.columns[689]],
                ItemCost: [&self.columns[690], &self.columns[691], &self.columns[692]],
                Quest: &self.columns[693],
                Unknown0: [
                    &self.columns[694],
                    &self.columns[695],
                    &self.columns[696],
                    &self.columns[697],
                ],
                AchievementUnlock: &self.columns[698],
                Unknown2: &self.columns[699],
                CollectabilityCost: [
                    &self.columns[700],
                    &self.columns[701],
                    &self.columns[702],
                ],
                PatchNumber: &self.columns[703],
                HqCost: [&self.columns[704], &self.columns[705], &self.columns[706]],
                Unknown1: [
                    &self.columns[707],
                    &self.columns[708],
                    &self.columns[709],
                    &self.columns[710],
                    &self.columns[711],
                ],
                Order: &self.columns[712],
                ReceiveHq: [&self.columns[713], &self.columns[714]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[715], &self.columns[716]],
                CurrencyCost: [
                    &self.columns[717],
                    &self.columns[718],
                    &self.columns[719],
                ],
                Item: [&self.columns[720], &self.columns[721]],
                Category: [&self.columns[722], &self.columns[723]],
                ItemCost: [&self.columns[724], &self.columns[725], &self.columns[726]],
                Quest: &self.columns[727],
                Unknown0: [
                    &self.columns[728],
                    &self.columns[729],
                    &self.columns[730],
                    &self.columns[731],
                ],
                AchievementUnlock: &self.columns[732],
                Unknown2: &self.columns[733],
                CollectabilityCost: [
                    &self.columns[734],
                    &self.columns[735],
                    &self.columns[736],
                ],
                PatchNumber: &self.columns[737],
                HqCost: [&self.columns[738], &self.columns[739], &self.columns[740]],
                Unknown1: [
                    &self.columns[741],
                    &self.columns[742],
                    &self.columns[743],
                    &self.columns[744],
                    &self.columns[745],
                ],
                Order: &self.columns[746],
                ReceiveHq: [&self.columns[747], &self.columns[748]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[749], &self.columns[750]],
                CurrencyCost: [
                    &self.columns[751],
                    &self.columns[752],
                    &self.columns[753],
                ],
                Item: [&self.columns[754], &self.columns[755]],
                Category: [&self.columns[756], &self.columns[757]],
                ItemCost: [&self.columns[758], &self.columns[759], &self.columns[760]],
                Quest: &self.columns[761],
                Unknown0: [
                    &self.columns[762],
                    &self.columns[763],
                    &self.columns[764],
                    &self.columns[765],
                ],
                AchievementUnlock: &self.columns[766],
                Unknown2: &self.columns[767],
                CollectabilityCost: [
                    &self.columns[768],
                    &self.columns[769],
                    &self.columns[770],
                ],
                PatchNumber: &self.columns[771],
                HqCost: [&self.columns[772], &self.columns[773], &self.columns[774]],
                Unknown1: [
                    &self.columns[775],
                    &self.columns[776],
                    &self.columns[777],
                    &self.columns[778],
                    &self.columns[779],
                ],
                Order: &self.columns[780],
                ReceiveHq: [&self.columns[781], &self.columns[782]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[783], &self.columns[784]],
                CurrencyCost: [
                    &self.columns[785],
                    &self.columns[786],
                    &self.columns[787],
                ],
                Item: [&self.columns[788], &self.columns[789]],
                Category: [&self.columns[790], &self.columns[791]],
                ItemCost: [&self.columns[792], &self.columns[793], &self.columns[794]],
                Quest: &self.columns[795],
                Unknown0: [
                    &self.columns[796],
                    &self.columns[797],
                    &self.columns[798],
                    &self.columns[799],
                ],
                AchievementUnlock: &self.columns[800],
                Unknown2: &self.columns[801],
                CollectabilityCost: [
                    &self.columns[802],
                    &self.columns[803],
                    &self.columns[804],
                ],
                PatchNumber: &self.columns[805],
                HqCost: [&self.columns[806], &self.columns[807], &self.columns[808]],
                Unknown1: [
                    &self.columns[809],
                    &self.columns[810],
                    &self.columns[811],
                    &self.columns[812],
                    &self.columns[813],
                ],
                Order: &self.columns[814],
                ReceiveHq: [&self.columns[815], &self.columns[816]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[817], &self.columns[818]],
                CurrencyCost: [
                    &self.columns[819],
                    &self.columns[820],
                    &self.columns[821],
                ],
                Item: [&self.columns[822], &self.columns[823]],
                Category: [&self.columns[824], &self.columns[825]],
                ItemCost: [&self.columns[826], &self.columns[827], &self.columns[828]],
                Quest: &self.columns[829],
                Unknown0: [
                    &self.columns[830],
                    &self.columns[831],
                    &self.columns[832],
                    &self.columns[833],
                ],
                AchievementUnlock: &self.columns[834],
                Unknown2: &self.columns[835],
                CollectabilityCost: [
                    &self.columns[836],
                    &self.columns[837],
                    &self.columns[838],
                ],
                PatchNumber: &self.columns[839],
                HqCost: [&self.columns[840], &self.columns[841], &self.columns[842]],
                Unknown1: [
                    &self.columns[843],
                    &self.columns[844],
                    &self.columns[845],
                    &self.columns[846],
                    &self.columns[847],
                ],
                Order: &self.columns[848],
                ReceiveHq: [&self.columns[849], &self.columns[850]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[851], &self.columns[852]],
                CurrencyCost: [
                    &self.columns[853],
                    &self.columns[854],
                    &self.columns[855],
                ],
                Item: [&self.columns[856], &self.columns[857]],
                Category: [&self.columns[858], &self.columns[859]],
                ItemCost: [&self.columns[860], &self.columns[861], &self.columns[862]],
                Quest: &self.columns[863],
                Unknown0: [
                    &self.columns[864],
                    &self.columns[865],
                    &self.columns[866],
                    &self.columns[867],
                ],
                AchievementUnlock: &self.columns[868],
                Unknown2: &self.columns[869],
                CollectabilityCost: [
                    &self.columns[870],
                    &self.columns[871],
                    &self.columns[872],
                ],
                PatchNumber: &self.columns[873],
                HqCost: [&self.columns[874], &self.columns[875], &self.columns[876]],
                Unknown1: [
                    &self.columns[877],
                    &self.columns[878],
                    &self.columns[879],
                    &self.columns[880],
                    &self.columns[881],
                ],
                Order: &self.columns[882],
                ReceiveHq: [&self.columns[883], &self.columns[884]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[885], &self.columns[886]],
                CurrencyCost: [
                    &self.columns[887],
                    &self.columns[888],
                    &self.columns[889],
                ],
                Item: [&self.columns[890], &self.columns[891]],
                Category: [&self.columns[892], &self.columns[893]],
                ItemCost: [&self.columns[894], &self.columns[895], &self.columns[896]],
                Quest: &self.columns[897],
                Unknown0: [
                    &self.columns[898],
                    &self.columns[899],
                    &self.columns[900],
                    &self.columns[901],
                ],
                AchievementUnlock: &self.columns[902],
                Unknown2: &self.columns[903],
                CollectabilityCost: [
                    &self.columns[904],
                    &self.columns[905],
                    &self.columns[906],
                ],
                PatchNumber: &self.columns[907],
                HqCost: [&self.columns[908], &self.columns[909], &self.columns[910]],
                Unknown1: [
                    &self.columns[911],
                    &self.columns[912],
                    &self.columns[913],
                    &self.columns[914],
                    &self.columns[915],
                ],
                Order: &self.columns[916],
                ReceiveHq: [&self.columns[917], &self.columns[918]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[919], &self.columns[920]],
                CurrencyCost: [
                    &self.columns[921],
                    &self.columns[922],
                    &self.columns[923],
                ],
                Item: [&self.columns[924], &self.columns[925]],
                Category: [&self.columns[926], &self.columns[927]],
                ItemCost: [&self.columns[928], &self.columns[929], &self.columns[930]],
                Quest: &self.columns[931],
                Unknown0: [
                    &self.columns[932],
                    &self.columns[933],
                    &self.columns[934],
                    &self.columns[935],
                ],
                AchievementUnlock: &self.columns[936],
                Unknown2: &self.columns[937],
                CollectabilityCost: [
                    &self.columns[938],
                    &self.columns[939],
                    &self.columns[940],
                ],
                PatchNumber: &self.columns[941],
                HqCost: [&self.columns[942], &self.columns[943], &self.columns[944]],
                Unknown1: [
                    &self.columns[945],
                    &self.columns[946],
                    &self.columns[947],
                    &self.columns[948],
                    &self.columns[949],
                ],
                Order: &self.columns[950],
                ReceiveHq: [&self.columns[951], &self.columns[952]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[953], &self.columns[954]],
                CurrencyCost: [
                    &self.columns[955],
                    &self.columns[956],
                    &self.columns[957],
                ],
                Item: [&self.columns[958], &self.columns[959]],
                Category: [&self.columns[960], &self.columns[961]],
                ItemCost: [&self.columns[962], &self.columns[963], &self.columns[964]],
                Quest: &self.columns[965],
                Unknown0: [
                    &self.columns[966],
                    &self.columns[967],
                    &self.columns[968],
                    &self.columns[969],
                ],
                AchievementUnlock: &self.columns[970],
                Unknown2: &self.columns[971],
                CollectabilityCost: [
                    &self.columns[972],
                    &self.columns[973],
                    &self.columns[974],
                ],
                PatchNumber: &self.columns[975],
                HqCost: [&self.columns[976], &self.columns[977], &self.columns[978]],
                Unknown1: [
                    &self.columns[979],
                    &self.columns[980],
                    &self.columns[981],
                    &self.columns[982],
                    &self.columns[983],
                ],
                Order: &self.columns[984],
                ReceiveHq: [&self.columns[985], &self.columns[986]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[987], &self.columns[988]],
                CurrencyCost: [
                    &self.columns[989],
                    &self.columns[990],
                    &self.columns[991],
                ],
                Item: [&self.columns[992], &self.columns[993]],
                Category: [&self.columns[994], &self.columns[995]],
                ItemCost: [&self.columns[996], &self.columns[997], &self.columns[998]],
                Quest: &self.columns[999],
                Unknown0: [
                    &self.columns[1000],
                    &self.columns[1001],
                    &self.columns[1002],
                    &self.columns[1003],
                ],
                AchievementUnlock: &self.columns[1004],
                Unknown2: &self.columns[1005],
                CollectabilityCost: [
                    &self.columns[1006],
                    &self.columns[1007],
                    &self.columns[1008],
                ],
                PatchNumber: &self.columns[1009],
                HqCost: [&self.columns[1010], &self.columns[1011], &self.columns[1012]],
                Unknown1: [
                    &self.columns[1013],
                    &self.columns[1014],
                    &self.columns[1015],
                    &self.columns[1016],
                    &self.columns[1017],
                ],
                Order: &self.columns[1018],
                ReceiveHq: [&self.columns[1019], &self.columns[1020]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1021], &self.columns[1022]],
                CurrencyCost: [
                    &self.columns[1023],
                    &self.columns[1024],
                    &self.columns[1025],
                ],
                Item: [&self.columns[1026], &self.columns[1027]],
                Category: [&self.columns[1028], &self.columns[1029]],
                ItemCost: [
                    &self.columns[1030],
                    &self.columns[1031],
                    &self.columns[1032],
                ],
                Quest: &self.columns[1033],
                Unknown0: [
                    &self.columns[1034],
                    &self.columns[1035],
                    &self.columns[1036],
                    &self.columns[1037],
                ],
                AchievementUnlock: &self.columns[1038],
                Unknown2: &self.columns[1039],
                CollectabilityCost: [
                    &self.columns[1040],
                    &self.columns[1041],
                    &self.columns[1042],
                ],
                PatchNumber: &self.columns[1043],
                HqCost: [&self.columns[1044], &self.columns[1045], &self.columns[1046]],
                Unknown1: [
                    &self.columns[1047],
                    &self.columns[1048],
                    &self.columns[1049],
                    &self.columns[1050],
                    &self.columns[1051],
                ],
                Order: &self.columns[1052],
                ReceiveHq: [&self.columns[1053], &self.columns[1054]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1055], &self.columns[1056]],
                CurrencyCost: [
                    &self.columns[1057],
                    &self.columns[1058],
                    &self.columns[1059],
                ],
                Item: [&self.columns[1060], &self.columns[1061]],
                Category: [&self.columns[1062], &self.columns[1063]],
                ItemCost: [
                    &self.columns[1064],
                    &self.columns[1065],
                    &self.columns[1066],
                ],
                Quest: &self.columns[1067],
                Unknown0: [
                    &self.columns[1068],
                    &self.columns[1069],
                    &self.columns[1070],
                    &self.columns[1071],
                ],
                AchievementUnlock: &self.columns[1072],
                Unknown2: &self.columns[1073],
                CollectabilityCost: [
                    &self.columns[1074],
                    &self.columns[1075],
                    &self.columns[1076],
                ],
                PatchNumber: &self.columns[1077],
                HqCost: [&self.columns[1078], &self.columns[1079], &self.columns[1080]],
                Unknown1: [
                    &self.columns[1081],
                    &self.columns[1082],
                    &self.columns[1083],
                    &self.columns[1084],
                    &self.columns[1085],
                ],
                Order: &self.columns[1086],
                ReceiveHq: [&self.columns[1087], &self.columns[1088]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1089], &self.columns[1090]],
                CurrencyCost: [
                    &self.columns[1091],
                    &self.columns[1092],
                    &self.columns[1093],
                ],
                Item: [&self.columns[1094], &self.columns[1095]],
                Category: [&self.columns[1096], &self.columns[1097]],
                ItemCost: [
                    &self.columns[1098],
                    &self.columns[1099],
                    &self.columns[1100],
                ],
                Quest: &self.columns[1101],
                Unknown0: [
                    &self.columns[1102],
                    &self.columns[1103],
                    &self.columns[1104],
                    &self.columns[1105],
                ],
                AchievementUnlock: &self.columns[1106],
                Unknown2: &self.columns[1107],
                CollectabilityCost: [
                    &self.columns[1108],
                    &self.columns[1109],
                    &self.columns[1110],
                ],
                PatchNumber: &self.columns[1111],
                HqCost: [&self.columns[1112], &self.columns[1113], &self.columns[1114]],
                Unknown1: [
                    &self.columns[1115],
                    &self.columns[1116],
                    &self.columns[1117],
                    &self.columns[1118],
                    &self.columns[1119],
                ],
                Order: &self.columns[1120],
                ReceiveHq: [&self.columns[1121], &self.columns[1122]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1123], &self.columns[1124]],
                CurrencyCost: [
                    &self.columns[1125],
                    &self.columns[1126],
                    &self.columns[1127],
                ],
                Item: [&self.columns[1128], &self.columns[1129]],
                Category: [&self.columns[1130], &self.columns[1131]],
                ItemCost: [
                    &self.columns[1132],
                    &self.columns[1133],
                    &self.columns[1134],
                ],
                Quest: &self.columns[1135],
                Unknown0: [
                    &self.columns[1136],
                    &self.columns[1137],
                    &self.columns[1138],
                    &self.columns[1139],
                ],
                AchievementUnlock: &self.columns[1140],
                Unknown2: &self.columns[1141],
                CollectabilityCost: [
                    &self.columns[1142],
                    &self.columns[1143],
                    &self.columns[1144],
                ],
                PatchNumber: &self.columns[1145],
                HqCost: [&self.columns[1146], &self.columns[1147], &self.columns[1148]],
                Unknown1: [
                    &self.columns[1149],
                    &self.columns[1150],
                    &self.columns[1151],
                    &self.columns[1152],
                    &self.columns[1153],
                ],
                Order: &self.columns[1154],
                ReceiveHq: [&self.columns[1155], &self.columns[1156]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1157], &self.columns[1158]],
                CurrencyCost: [
                    &self.columns[1159],
                    &self.columns[1160],
                    &self.columns[1161],
                ],
                Item: [&self.columns[1162], &self.columns[1163]],
                Category: [&self.columns[1164], &self.columns[1165]],
                ItemCost: [
                    &self.columns[1166],
                    &self.columns[1167],
                    &self.columns[1168],
                ],
                Quest: &self.columns[1169],
                Unknown0: [
                    &self.columns[1170],
                    &self.columns[1171],
                    &self.columns[1172],
                    &self.columns[1173],
                ],
                AchievementUnlock: &self.columns[1174],
                Unknown2: &self.columns[1175],
                CollectabilityCost: [
                    &self.columns[1176],
                    &self.columns[1177],
                    &self.columns[1178],
                ],
                PatchNumber: &self.columns[1179],
                HqCost: [&self.columns[1180], &self.columns[1181], &self.columns[1182]],
                Unknown1: [
                    &self.columns[1183],
                    &self.columns[1184],
                    &self.columns[1185],
                    &self.columns[1186],
                    &self.columns[1187],
                ],
                Order: &self.columns[1188],
                ReceiveHq: [&self.columns[1189], &self.columns[1190]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1191], &self.columns[1192]],
                CurrencyCost: [
                    &self.columns[1193],
                    &self.columns[1194],
                    &self.columns[1195],
                ],
                Item: [&self.columns[1196], &self.columns[1197]],
                Category: [&self.columns[1198], &self.columns[1199]],
                ItemCost: [
                    &self.columns[1200],
                    &self.columns[1201],
                    &self.columns[1202],
                ],
                Quest: &self.columns[1203],
                Unknown0: [
                    &self.columns[1204],
                    &self.columns[1205],
                    &self.columns[1206],
                    &self.columns[1207],
                ],
                AchievementUnlock: &self.columns[1208],
                Unknown2: &self.columns[1209],
                CollectabilityCost: [
                    &self.columns[1210],
                    &self.columns[1211],
                    &self.columns[1212],
                ],
                PatchNumber: &self.columns[1213],
                HqCost: [&self.columns[1214], &self.columns[1215], &self.columns[1216]],
                Unknown1: [
                    &self.columns[1217],
                    &self.columns[1218],
                    &self.columns[1219],
                    &self.columns[1220],
                    &self.columns[1221],
                ],
                Order: &self.columns[1222],
                ReceiveHq: [&self.columns[1223], &self.columns[1224]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1225], &self.columns[1226]],
                CurrencyCost: [
                    &self.columns[1227],
                    &self.columns[1228],
                    &self.columns[1229],
                ],
                Item: [&self.columns[1230], &self.columns[1231]],
                Category: [&self.columns[1232], &self.columns[1233]],
                ItemCost: [
                    &self.columns[1234],
                    &self.columns[1235],
                    &self.columns[1236],
                ],
                Quest: &self.columns[1237],
                Unknown0: [
                    &self.columns[1238],
                    &self.columns[1239],
                    &self.columns[1240],
                    &self.columns[1241],
                ],
                AchievementUnlock: &self.columns[1242],
                Unknown2: &self.columns[1243],
                CollectabilityCost: [
                    &self.columns[1244],
                    &self.columns[1245],
                    &self.columns[1246],
                ],
                PatchNumber: &self.columns[1247],
                HqCost: [&self.columns[1248], &self.columns[1249], &self.columns[1250]],
                Unknown1: [
                    &self.columns[1251],
                    &self.columns[1252],
                    &self.columns[1253],
                    &self.columns[1254],
                    &self.columns[1255],
                ],
                Order: &self.columns[1256],
                ReceiveHq: [&self.columns[1257], &self.columns[1258]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1259], &self.columns[1260]],
                CurrencyCost: [
                    &self.columns[1261],
                    &self.columns[1262],
                    &self.columns[1263],
                ],
                Item: [&self.columns[1264], &self.columns[1265]],
                Category: [&self.columns[1266], &self.columns[1267]],
                ItemCost: [
                    &self.columns[1268],
                    &self.columns[1269],
                    &self.columns[1270],
                ],
                Quest: &self.columns[1271],
                Unknown0: [
                    &self.columns[1272],
                    &self.columns[1273],
                    &self.columns[1274],
                    &self.columns[1275],
                ],
                AchievementUnlock: &self.columns[1276],
                Unknown2: &self.columns[1277],
                CollectabilityCost: [
                    &self.columns[1278],
                    &self.columns[1279],
                    &self.columns[1280],
                ],
                PatchNumber: &self.columns[1281],
                HqCost: [&self.columns[1282], &self.columns[1283], &self.columns[1284]],
                Unknown1: [
                    &self.columns[1285],
                    &self.columns[1286],
                    &self.columns[1287],
                    &self.columns[1288],
                    &self.columns[1289],
                ],
                Order: &self.columns[1290],
                ReceiveHq: [&self.columns[1291], &self.columns[1292]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1293], &self.columns[1294]],
                CurrencyCost: [
                    &self.columns[1295],
                    &self.columns[1296],
                    &self.columns[1297],
                ],
                Item: [&self.columns[1298], &self.columns[1299]],
                Category: [&self.columns[1300], &self.columns[1301]],
                ItemCost: [
                    &self.columns[1302],
                    &self.columns[1303],
                    &self.columns[1304],
                ],
                Quest: &self.columns[1305],
                Unknown0: [
                    &self.columns[1306],
                    &self.columns[1307],
                    &self.columns[1308],
                    &self.columns[1309],
                ],
                AchievementUnlock: &self.columns[1310],
                Unknown2: &self.columns[1311],
                CollectabilityCost: [
                    &self.columns[1312],
                    &self.columns[1313],
                    &self.columns[1314],
                ],
                PatchNumber: &self.columns[1315],
                HqCost: [&self.columns[1316], &self.columns[1317], &self.columns[1318]],
                Unknown1: [
                    &self.columns[1319],
                    &self.columns[1320],
                    &self.columns[1321],
                    &self.columns[1322],
                    &self.columns[1323],
                ],
                Order: &self.columns[1324],
                ReceiveHq: [&self.columns[1325], &self.columns[1326]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1327], &self.columns[1328]],
                CurrencyCost: [
                    &self.columns[1329],
                    &self.columns[1330],
                    &self.columns[1331],
                ],
                Item: [&self.columns[1332], &self.columns[1333]],
                Category: [&self.columns[1334], &self.columns[1335]],
                ItemCost: [
                    &self.columns[1336],
                    &self.columns[1337],
                    &self.columns[1338],
                ],
                Quest: &self.columns[1339],
                Unknown0: [
                    &self.columns[1340],
                    &self.columns[1341],
                    &self.columns[1342],
                    &self.columns[1343],
                ],
                AchievementUnlock: &self.columns[1344],
                Unknown2: &self.columns[1345],
                CollectabilityCost: [
                    &self.columns[1346],
                    &self.columns[1347],
                    &self.columns[1348],
                ],
                PatchNumber: &self.columns[1349],
                HqCost: [&self.columns[1350], &self.columns[1351], &self.columns[1352]],
                Unknown1: [
                    &self.columns[1353],
                    &self.columns[1354],
                    &self.columns[1355],
                    &self.columns[1356],
                    &self.columns[1357],
                ],
                Order: &self.columns[1358],
                ReceiveHq: [&self.columns[1359], &self.columns[1360]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1361], &self.columns[1362]],
                CurrencyCost: [
                    &self.columns[1363],
                    &self.columns[1364],
                    &self.columns[1365],
                ],
                Item: [&self.columns[1366], &self.columns[1367]],
                Category: [&self.columns[1368], &self.columns[1369]],
                ItemCost: [
                    &self.columns[1370],
                    &self.columns[1371],
                    &self.columns[1372],
                ],
                Quest: &self.columns[1373],
                Unknown0: [
                    &self.columns[1374],
                    &self.columns[1375],
                    &self.columns[1376],
                    &self.columns[1377],
                ],
                AchievementUnlock: &self.columns[1378],
                Unknown2: &self.columns[1379],
                CollectabilityCost: [
                    &self.columns[1380],
                    &self.columns[1381],
                    &self.columns[1382],
                ],
                PatchNumber: &self.columns[1383],
                HqCost: [&self.columns[1384], &self.columns[1385], &self.columns[1386]],
                Unknown1: [
                    &self.columns[1387],
                    &self.columns[1388],
                    &self.columns[1389],
                    &self.columns[1390],
                    &self.columns[1391],
                ],
                Order: &self.columns[1392],
                ReceiveHq: [&self.columns[1393], &self.columns[1394]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1395], &self.columns[1396]],
                CurrencyCost: [
                    &self.columns[1397],
                    &self.columns[1398],
                    &self.columns[1399],
                ],
                Item: [&self.columns[1400], &self.columns[1401]],
                Category: [&self.columns[1402], &self.columns[1403]],
                ItemCost: [
                    &self.columns[1404],
                    &self.columns[1405],
                    &self.columns[1406],
                ],
                Quest: &self.columns[1407],
                Unknown0: [
                    &self.columns[1408],
                    &self.columns[1409],
                    &self.columns[1410],
                    &self.columns[1411],
                ],
                AchievementUnlock: &self.columns[1412],
                Unknown2: &self.columns[1413],
                CollectabilityCost: [
                    &self.columns[1414],
                    &self.columns[1415],
                    &self.columns[1416],
                ],
                PatchNumber: &self.columns[1417],
                HqCost: [&self.columns[1418], &self.columns[1419], &self.columns[1420]],
                Unknown1: [
                    &self.columns[1421],
                    &self.columns[1422],
                    &self.columns[1423],
                    &self.columns[1424],
                    &self.columns[1425],
                ],
                Order: &self.columns[1426],
                ReceiveHq: [&self.columns[1427], &self.columns[1428]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1429], &self.columns[1430]],
                CurrencyCost: [
                    &self.columns[1431],
                    &self.columns[1432],
                    &self.columns[1433],
                ],
                Item: [&self.columns[1434], &self.columns[1435]],
                Category: [&self.columns[1436], &self.columns[1437]],
                ItemCost: [
                    &self.columns[1438],
                    &self.columns[1439],
                    &self.columns[1440],
                ],
                Quest: &self.columns[1441],
                Unknown0: [
                    &self.columns[1442],
                    &self.columns[1443],
                    &self.columns[1444],
                    &self.columns[1445],
                ],
                AchievementUnlock: &self.columns[1446],
                Unknown2: &self.columns[1447],
                CollectabilityCost: [
                    &self.columns[1448],
                    &self.columns[1449],
                    &self.columns[1450],
                ],
                PatchNumber: &self.columns[1451],
                HqCost: [&self.columns[1452], &self.columns[1453], &self.columns[1454]],
                Unknown1: [
                    &self.columns[1455],
                    &self.columns[1456],
                    &self.columns[1457],
                    &self.columns[1458],
                    &self.columns[1459],
                ],
                Order: &self.columns[1460],
                ReceiveHq: [&self.columns[1461], &self.columns[1462]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1463], &self.columns[1464]],
                CurrencyCost: [
                    &self.columns[1465],
                    &self.columns[1466],
                    &self.columns[1467],
                ],
                Item: [&self.columns[1468], &self.columns[1469]],
                Category: [&self.columns[1470], &self.columns[1471]],
                ItemCost: [
                    &self.columns[1472],
                    &self.columns[1473],
                    &self.columns[1474],
                ],
                Quest: &self.columns[1475],
                Unknown0: [
                    &self.columns[1476],
                    &self.columns[1477],
                    &self.columns[1478],
                    &self.columns[1479],
                ],
                AchievementUnlock: &self.columns[1480],
                Unknown2: &self.columns[1481],
                CollectabilityCost: [
                    &self.columns[1482],
                    &self.columns[1483],
                    &self.columns[1484],
                ],
                PatchNumber: &self.columns[1485],
                HqCost: [&self.columns[1486], &self.columns[1487], &self.columns[1488]],
                Unknown1: [
                    &self.columns[1489],
                    &self.columns[1490],
                    &self.columns[1491],
                    &self.columns[1492],
                    &self.columns[1493],
                ],
                Order: &self.columns[1494],
                ReceiveHq: [&self.columns[1495], &self.columns[1496]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1497], &self.columns[1498]],
                CurrencyCost: [
                    &self.columns[1499],
                    &self.columns[1500],
                    &self.columns[1501],
                ],
                Item: [&self.columns[1502], &self.columns[1503]],
                Category: [&self.columns[1504], &self.columns[1505]],
                ItemCost: [
                    &self.columns[1506],
                    &self.columns[1507],
                    &self.columns[1508],
                ],
                Quest: &self.columns[1509],
                Unknown0: [
                    &self.columns[1510],
                    &self.columns[1511],
                    &self.columns[1512],
                    &self.columns[1513],
                ],
                AchievementUnlock: &self.columns[1514],
                Unknown2: &self.columns[1515],
                CollectabilityCost: [
                    &self.columns[1516],
                    &self.columns[1517],
                    &self.columns[1518],
                ],
                PatchNumber: &self.columns[1519],
                HqCost: [&self.columns[1520], &self.columns[1521], &self.columns[1522]],
                Unknown1: [
                    &self.columns[1523],
                    &self.columns[1524],
                    &self.columns[1525],
                    &self.columns[1526],
                    &self.columns[1527],
                ],
                Order: &self.columns[1528],
                ReceiveHq: [&self.columns[1529], &self.columns[1530]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1531], &self.columns[1532]],
                CurrencyCost: [
                    &self.columns[1533],
                    &self.columns[1534],
                    &self.columns[1535],
                ],
                Item: [&self.columns[1536], &self.columns[1537]],
                Category: [&self.columns[1538], &self.columns[1539]],
                ItemCost: [
                    &self.columns[1540],
                    &self.columns[1541],
                    &self.columns[1542],
                ],
                Quest: &self.columns[1543],
                Unknown0: [
                    &self.columns[1544],
                    &self.columns[1545],
                    &self.columns[1546],
                    &self.columns[1547],
                ],
                AchievementUnlock: &self.columns[1548],
                Unknown2: &self.columns[1549],
                CollectabilityCost: [
                    &self.columns[1550],
                    &self.columns[1551],
                    &self.columns[1552],
                ],
                PatchNumber: &self.columns[1553],
                HqCost: [&self.columns[1554], &self.columns[1555], &self.columns[1556]],
                Unknown1: [
                    &self.columns[1557],
                    &self.columns[1558],
                    &self.columns[1559],
                    &self.columns[1560],
                    &self.columns[1561],
                ],
                Order: &self.columns[1562],
                ReceiveHq: [&self.columns[1563], &self.columns[1564]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1565], &self.columns[1566]],
                CurrencyCost: [
                    &self.columns[1567],
                    &self.columns[1568],
                    &self.columns[1569],
                ],
                Item: [&self.columns[1570], &self.columns[1571]],
                Category: [&self.columns[1572], &self.columns[1573]],
                ItemCost: [
                    &self.columns[1574],
                    &self.columns[1575],
                    &self.columns[1576],
                ],
                Quest: &self.columns[1577],
                Unknown0: [
                    &self.columns[1578],
                    &self.columns[1579],
                    &self.columns[1580],
                    &self.columns[1581],
                ],
                AchievementUnlock: &self.columns[1582],
                Unknown2: &self.columns[1583],
                CollectabilityCost: [
                    &self.columns[1584],
                    &self.columns[1585],
                    &self.columns[1586],
                ],
                PatchNumber: &self.columns[1587],
                HqCost: [&self.columns[1588], &self.columns[1589], &self.columns[1590]],
                Unknown1: [
                    &self.columns[1591],
                    &self.columns[1592],
                    &self.columns[1593],
                    &self.columns[1594],
                    &self.columns[1595],
                ],
                Order: &self.columns[1596],
                ReceiveHq: [&self.columns[1597], &self.columns[1598]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1599], &self.columns[1600]],
                CurrencyCost: [
                    &self.columns[1601],
                    &self.columns[1602],
                    &self.columns[1603],
                ],
                Item: [&self.columns[1604], &self.columns[1605]],
                Category: [&self.columns[1606], &self.columns[1607]],
                ItemCost: [
                    &self.columns[1608],
                    &self.columns[1609],
                    &self.columns[1610],
                ],
                Quest: &self.columns[1611],
                Unknown0: [
                    &self.columns[1612],
                    &self.columns[1613],
                    &self.columns[1614],
                    &self.columns[1615],
                ],
                AchievementUnlock: &self.columns[1616],
                Unknown2: &self.columns[1617],
                CollectabilityCost: [
                    &self.columns[1618],
                    &self.columns[1619],
                    &self.columns[1620],
                ],
                PatchNumber: &self.columns[1621],
                HqCost: [&self.columns[1622], &self.columns[1623], &self.columns[1624]],
                Unknown1: [
                    &self.columns[1625],
                    &self.columns[1626],
                    &self.columns[1627],
                    &self.columns[1628],
                    &self.columns[1629],
                ],
                Order: &self.columns[1630],
                ReceiveHq: [&self.columns[1631], &self.columns[1632]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1633], &self.columns[1634]],
                CurrencyCost: [
                    &self.columns[1635],
                    &self.columns[1636],
                    &self.columns[1637],
                ],
                Item: [&self.columns[1638], &self.columns[1639]],
                Category: [&self.columns[1640], &self.columns[1641]],
                ItemCost: [
                    &self.columns[1642],
                    &self.columns[1643],
                    &self.columns[1644],
                ],
                Quest: &self.columns[1645],
                Unknown0: [
                    &self.columns[1646],
                    &self.columns[1647],
                    &self.columns[1648],
                    &self.columns[1649],
                ],
                AchievementUnlock: &self.columns[1650],
                Unknown2: &self.columns[1651],
                CollectabilityCost: [
                    &self.columns[1652],
                    &self.columns[1653],
                    &self.columns[1654],
                ],
                PatchNumber: &self.columns[1655],
                HqCost: [&self.columns[1656], &self.columns[1657], &self.columns[1658]],
                Unknown1: [
                    &self.columns[1659],
                    &self.columns[1660],
                    &self.columns[1661],
                    &self.columns[1662],
                    &self.columns[1663],
                ],
                Order: &self.columns[1664],
                ReceiveHq: [&self.columns[1665], &self.columns[1666]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1667], &self.columns[1668]],
                CurrencyCost: [
                    &self.columns[1669],
                    &self.columns[1670],
                    &self.columns[1671],
                ],
                Item: [&self.columns[1672], &self.columns[1673]],
                Category: [&self.columns[1674], &self.columns[1675]],
                ItemCost: [
                    &self.columns[1676],
                    &self.columns[1677],
                    &self.columns[1678],
                ],
                Quest: &self.columns[1679],
                Unknown0: [
                    &self.columns[1680],
                    &self.columns[1681],
                    &self.columns[1682],
                    &self.columns[1683],
                ],
                AchievementUnlock: &self.columns[1684],
                Unknown2: &self.columns[1685],
                CollectabilityCost: [
                    &self.columns[1686],
                    &self.columns[1687],
                    &self.columns[1688],
                ],
                PatchNumber: &self.columns[1689],
                HqCost: [&self.columns[1690], &self.columns[1691], &self.columns[1692]],
                Unknown1: [
                    &self.columns[1693],
                    &self.columns[1694],
                    &self.columns[1695],
                    &self.columns[1696],
                    &self.columns[1697],
                ],
                Order: &self.columns[1698],
                ReceiveHq: [&self.columns[1699], &self.columns[1700]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1701], &self.columns[1702]],
                CurrencyCost: [
                    &self.columns[1703],
                    &self.columns[1704],
                    &self.columns[1705],
                ],
                Item: [&self.columns[1706], &self.columns[1707]],
                Category: [&self.columns[1708], &self.columns[1709]],
                ItemCost: [
                    &self.columns[1710],
                    &self.columns[1711],
                    &self.columns[1712],
                ],
                Quest: &self.columns[1713],
                Unknown0: [
                    &self.columns[1714],
                    &self.columns[1715],
                    &self.columns[1716],
                    &self.columns[1717],
                ],
                AchievementUnlock: &self.columns[1718],
                Unknown2: &self.columns[1719],
                CollectabilityCost: [
                    &self.columns[1720],
                    &self.columns[1721],
                    &self.columns[1722],
                ],
                PatchNumber: &self.columns[1723],
                HqCost: [&self.columns[1724], &self.columns[1725], &self.columns[1726]],
                Unknown1: [
                    &self.columns[1727],
                    &self.columns[1728],
                    &self.columns[1729],
                    &self.columns[1730],
                    &self.columns[1731],
                ],
                Order: &self.columns[1732],
                ReceiveHq: [&self.columns[1733], &self.columns[1734]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1735], &self.columns[1736]],
                CurrencyCost: [
                    &self.columns[1737],
                    &self.columns[1738],
                    &self.columns[1739],
                ],
                Item: [&self.columns[1740], &self.columns[1741]],
                Category: [&self.columns[1742], &self.columns[1743]],
                ItemCost: [
                    &self.columns[1744],
                    &self.columns[1745],
                    &self.columns[1746],
                ],
                Quest: &self.columns[1747],
                Unknown0: [
                    &self.columns[1748],
                    &self.columns[1749],
                    &self.columns[1750],
                    &self.columns[1751],
                ],
                AchievementUnlock: &self.columns[1752],
                Unknown2: &self.columns[1753],
                CollectabilityCost: [
                    &self.columns[1754],
                    &self.columns[1755],
                    &self.columns[1756],
                ],
                PatchNumber: &self.columns[1757],
                HqCost: [&self.columns[1758], &self.columns[1759], &self.columns[1760]],
                Unknown1: [
                    &self.columns[1761],
                    &self.columns[1762],
                    &self.columns[1763],
                    &self.columns[1764],
                    &self.columns[1765],
                ],
                Order: &self.columns[1766],
                ReceiveHq: [&self.columns[1767], &self.columns[1768]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1769], &self.columns[1770]],
                CurrencyCost: [
                    &self.columns[1771],
                    &self.columns[1772],
                    &self.columns[1773],
                ],
                Item: [&self.columns[1774], &self.columns[1775]],
                Category: [&self.columns[1776], &self.columns[1777]],
                ItemCost: [
                    &self.columns[1778],
                    &self.columns[1779],
                    &self.columns[1780],
                ],
                Quest: &self.columns[1781],
                Unknown0: [
                    &self.columns[1782],
                    &self.columns[1783],
                    &self.columns[1784],
                    &self.columns[1785],
                ],
                AchievementUnlock: &self.columns[1786],
                Unknown2: &self.columns[1787],
                CollectabilityCost: [
                    &self.columns[1788],
                    &self.columns[1789],
                    &self.columns[1790],
                ],
                PatchNumber: &self.columns[1791],
                HqCost: [&self.columns[1792], &self.columns[1793], &self.columns[1794]],
                Unknown1: [
                    &self.columns[1795],
                    &self.columns[1796],
                    &self.columns[1797],
                    &self.columns[1798],
                    &self.columns[1799],
                ],
                Order: &self.columns[1800],
                ReceiveHq: [&self.columns[1801], &self.columns[1802]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1803], &self.columns[1804]],
                CurrencyCost: [
                    &self.columns[1805],
                    &self.columns[1806],
                    &self.columns[1807],
                ],
                Item: [&self.columns[1808], &self.columns[1809]],
                Category: [&self.columns[1810], &self.columns[1811]],
                ItemCost: [
                    &self.columns[1812],
                    &self.columns[1813],
                    &self.columns[1814],
                ],
                Quest: &self.columns[1815],
                Unknown0: [
                    &self.columns[1816],
                    &self.columns[1817],
                    &self.columns[1818],
                    &self.columns[1819],
                ],
                AchievementUnlock: &self.columns[1820],
                Unknown2: &self.columns[1821],
                CollectabilityCost: [
                    &self.columns[1822],
                    &self.columns[1823],
                    &self.columns[1824],
                ],
                PatchNumber: &self.columns[1825],
                HqCost: [&self.columns[1826], &self.columns[1827], &self.columns[1828]],
                Unknown1: [
                    &self.columns[1829],
                    &self.columns[1830],
                    &self.columns[1831],
                    &self.columns[1832],
                    &self.columns[1833],
                ],
                Order: &self.columns[1834],
                ReceiveHq: [&self.columns[1835], &self.columns[1836]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1837], &self.columns[1838]],
                CurrencyCost: [
                    &self.columns[1839],
                    &self.columns[1840],
                    &self.columns[1841],
                ],
                Item: [&self.columns[1842], &self.columns[1843]],
                Category: [&self.columns[1844], &self.columns[1845]],
                ItemCost: [
                    &self.columns[1846],
                    &self.columns[1847],
                    &self.columns[1848],
                ],
                Quest: &self.columns[1849],
                Unknown0: [
                    &self.columns[1850],
                    &self.columns[1851],
                    &self.columns[1852],
                    &self.columns[1853],
                ],
                AchievementUnlock: &self.columns[1854],
                Unknown2: &self.columns[1855],
                CollectabilityCost: [
                    &self.columns[1856],
                    &self.columns[1857],
                    &self.columns[1858],
                ],
                PatchNumber: &self.columns[1859],
                HqCost: [&self.columns[1860], &self.columns[1861], &self.columns[1862]],
                Unknown1: [
                    &self.columns[1863],
                    &self.columns[1864],
                    &self.columns[1865],
                    &self.columns[1866],
                    &self.columns[1867],
                ],
                Order: &self.columns[1868],
                ReceiveHq: [&self.columns[1869], &self.columns[1870]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1871], &self.columns[1872]],
                CurrencyCost: [
                    &self.columns[1873],
                    &self.columns[1874],
                    &self.columns[1875],
                ],
                Item: [&self.columns[1876], &self.columns[1877]],
                Category: [&self.columns[1878], &self.columns[1879]],
                ItemCost: [
                    &self.columns[1880],
                    &self.columns[1881],
                    &self.columns[1882],
                ],
                Quest: &self.columns[1883],
                Unknown0: [
                    &self.columns[1884],
                    &self.columns[1885],
                    &self.columns[1886],
                    &self.columns[1887],
                ],
                AchievementUnlock: &self.columns[1888],
                Unknown2: &self.columns[1889],
                CollectabilityCost: [
                    &self.columns[1890],
                    &self.columns[1891],
                    &self.columns[1892],
                ],
                PatchNumber: &self.columns[1893],
                HqCost: [&self.columns[1894], &self.columns[1895], &self.columns[1896]],
                Unknown1: [
                    &self.columns[1897],
                    &self.columns[1898],
                    &self.columns[1899],
                    &self.columns[1900],
                    &self.columns[1901],
                ],
                Order: &self.columns[1902],
                ReceiveHq: [&self.columns[1903], &self.columns[1904]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1905], &self.columns[1906]],
                CurrencyCost: [
                    &self.columns[1907],
                    &self.columns[1908],
                    &self.columns[1909],
                ],
                Item: [&self.columns[1910], &self.columns[1911]],
                Category: [&self.columns[1912], &self.columns[1913]],
                ItemCost: [
                    &self.columns[1914],
                    &self.columns[1915],
                    &self.columns[1916],
                ],
                Quest: &self.columns[1917],
                Unknown0: [
                    &self.columns[1918],
                    &self.columns[1919],
                    &self.columns[1920],
                    &self.columns[1921],
                ],
                AchievementUnlock: &self.columns[1922],
                Unknown2: &self.columns[1923],
                CollectabilityCost: [
                    &self.columns[1924],
                    &self.columns[1925],
                    &self.columns[1926],
                ],
                PatchNumber: &self.columns[1927],
                HqCost: [&self.columns[1928], &self.columns[1929], &self.columns[1930]],
                Unknown1: [
                    &self.columns[1931],
                    &self.columns[1932],
                    &self.columns[1933],
                    &self.columns[1934],
                    &self.columns[1935],
                ],
                Order: &self.columns[1936],
                ReceiveHq: [&self.columns[1937], &self.columns[1938]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1939], &self.columns[1940]],
                CurrencyCost: [
                    &self.columns[1941],
                    &self.columns[1942],
                    &self.columns[1943],
                ],
                Item: [&self.columns[1944], &self.columns[1945]],
                Category: [&self.columns[1946], &self.columns[1947]],
                ItemCost: [
                    &self.columns[1948],
                    &self.columns[1949],
                    &self.columns[1950],
                ],
                Quest: &self.columns[1951],
                Unknown0: [
                    &self.columns[1952],
                    &self.columns[1953],
                    &self.columns[1954],
                    &self.columns[1955],
                ],
                AchievementUnlock: &self.columns[1956],
                Unknown2: &self.columns[1957],
                CollectabilityCost: [
                    &self.columns[1958],
                    &self.columns[1959],
                    &self.columns[1960],
                ],
                PatchNumber: &self.columns[1961],
                HqCost: [&self.columns[1962], &self.columns[1963], &self.columns[1964]],
                Unknown1: [
                    &self.columns[1965],
                    &self.columns[1966],
                    &self.columns[1967],
                    &self.columns[1968],
                    &self.columns[1969],
                ],
                Order: &self.columns[1970],
                ReceiveHq: [&self.columns[1971], &self.columns[1972]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[1973], &self.columns[1974]],
                CurrencyCost: [
                    &self.columns[1975],
                    &self.columns[1976],
                    &self.columns[1977],
                ],
                Item: [&self.columns[1978], &self.columns[1979]],
                Category: [&self.columns[1980], &self.columns[1981]],
                ItemCost: [
                    &self.columns[1982],
                    &self.columns[1983],
                    &self.columns[1984],
                ],
                Quest: &self.columns[1985],
                Unknown0: [
                    &self.columns[1986],
                    &self.columns[1987],
                    &self.columns[1988],
                    &self.columns[1989],
                ],
                AchievementUnlock: &self.columns[1990],
                Unknown2: &self.columns[1991],
                CollectabilityCost: [
                    &self.columns[1992],
                    &self.columns[1993],
                    &self.columns[1994],
                ],
                PatchNumber: &self.columns[1995],
                HqCost: [&self.columns[1996], &self.columns[1997], &self.columns[1998]],
                Unknown1: [
                    &self.columns[1999],
                    &self.columns[2000],
                    &self.columns[2001],
                    &self.columns[2002],
                    &self.columns[2003],
                ],
                Order: &self.columns[2004],
                ReceiveHq: [&self.columns[2005], &self.columns[2006]],
            },
            ItemElement {
                ReceiveCount: [&self.columns[2007], &self.columns[2008]],
                CurrencyCost: [
                    &self.columns[2009],
                    &self.columns[2010],
                    &self.columns[2011],
                ],
                Item: [&self.columns[2012], &self.columns[2013]],
                Category: [&self.columns[2014], &self.columns[2015]],
                ItemCost: [
                    &self.columns[2016],
                    &self.columns[2017],
                    &self.columns[2018],
                ],
                Quest: &self.columns[2019],
                Unknown0: [
                    &self.columns[2020],
                    &self.columns[2021],
                    &self.columns[2022],
                    &self.columns[2023],
                ],
                AchievementUnlock: &self.columns[2024],
                Unknown2: &self.columns[2025],
                CollectabilityCost: [
                    &self.columns[2026],
                    &self.columns[2027],
                    &self.columns[2028],
                ],
                PatchNumber: &self.columns[2029],
                HqCost: [&self.columns[2030], &self.columns[2031], &self.columns[2032]],
                Unknown1: [
                    &self.columns[2033],
                    &self.columns[2034],
                    &self.columns[2035],
                    &self.columns[2036],
                    &self.columns[2037],
                ],
                Order: &self.columns[2038],
                ReceiveHq: [&self.columns[2039], &self.columns[2040]],
            },
        ]
    }
    pub fn Quest<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2041]
    }
    pub fn Unknown0<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2042]
    }
    pub fn RequiredContentFinderCondition<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2043]
    }
    pub fn CompleteText<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2044]
    }
    pub fn NotCompleteText<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2045]
    }
    pub fn RequiredFestival<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2046]
    }
    pub fn RequiredFestivalPhase<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2047]
    }
    pub fn UseCurrencyType<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2048]
    }
    pub fn Unknown3<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2049]
    }
    /// If this is true, then the CFC needs to be completed; If this is false, then the CFC just needs to be unlocked
    pub fn RequiredContentFinderConditionComplete<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2050]
    }
    pub fn Unknown4<'a>(&'a self) -> &'a ColumnData {
        &self.columns[2051]
    }
}
