#![allow(warnings)]
/// This file is auto-generated! It is generated from schema from https://github.com/xivdev/EXDSchema.
use physis::{resource::{Resource, read_excel_sheet_header, read_excel_sheet}, exd::{EXD, ColumnData, ExcelRowKind, ExcelSingleRow}, exh::{EXH, ExcelColumnDefinition}, common::Language};
pub struct ItemElement<'a> {
ReceiveCount: &'a ColumnData,
CurrencyCost: &'a ColumnData,
Item: &'a ColumnData,
Category: &'a ColumnData,
ItemCost: &'a ColumnData,
Quest: &'a ColumnData,
Unknown0: &'a ColumnData,
AchievementUnlock: &'a ColumnData,
Unknown2: &'a ColumnData,
CollectabilityCost: &'a ColumnData,
PatchNumber: &'a ColumnData,
HqCost: &'a ColumnData,
Unknown1: &'a ColumnData,
Order: &'a ColumnData,
ReceiveHq: &'a ColumnData,
}
pub struct SpecialShopSheet {
pages: Vec<EXD>,
exh: EXH,
row_count: u32,
}
impl SpecialShopSheet {
pub fn read_from<T: Resource>(resource: &mut T, language: Language) -> Option<Self> {
let exh = read_excel_sheet_header(resource, "SpecialShop")?;
let mut pages = Vec::new();
for (i, _) in exh.pages.iter().enumerate() {
pages.push(read_excel_sheet(resource, "SpecialShop", &exh, language, i)?);
}let row_count = exh.header.row_count;
Some(Self {
exh,
pages,
row_count,
})
}
fn read_row(&self, row: &ExcelSingleRow) -> Option<SpecialShopRow> {
let column_defs = &self.exh.column_definitions;
let mut zipped: Vec<_> = row.columns.clone().into_iter().zip(column_defs).collect();
zipped.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
let (columns, _): (Vec<ColumnData>, Vec<ExcelColumnDefinition> ) = zipped.into_iter().unzip();
Some(SpecialShopRow { columns })
}
/// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
pub fn get_row(&self, row_id: u32) -> Option<SpecialShopRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => row,
ExcelRowKind::SubRows(rows) => &rows.first()?.1,
};
return self.read_row(row);
}
None
}
/// Fetches the specified subrow from the sheet.
pub fn get_subrow(&self, row_id: u32, subrow_id: u16) -> Option<SpecialShopRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => return None,
ExcelRowKind::SubRows(subrows) => &subrows.iter().filter(|(id, _)| *id == subrow_id).next()?.1,
};
return self.read_row(row);
}
None
}
/// Returns the number of rows in this sheet.
pub fn row_count(&self) -> u32 {
self.row_count
}
}
pub struct SpecialShopRow {
columns: Vec<ColumnData>,
}
impl SpecialShopRow {
pub fn Name(&self) -> &ColumnData {
&self.columns[0]
}
pub fn Item<'a>(&'a self) -> [ItemElement<'a>; 60] {
[ItemElement {ReceiveCount: &self.columns[1],
CurrencyCost: &self.columns[2],
Item: &self.columns[3],
Category: &self.columns[4],
ItemCost: &self.columns[5],
Quest: &self.columns[6],
Unknown0: &self.columns[7],
AchievementUnlock: &self.columns[8],
Unknown2: &self.columns[9],
CollectabilityCost: &self.columns[10],
PatchNumber: &self.columns[11],
HqCost: &self.columns[12],
Unknown1: &self.columns[13],
Order: &self.columns[14],
ReceiveHq: &self.columns[15],
},
ItemElement {ReceiveCount: &self.columns[16],
CurrencyCost: &self.columns[17],
Item: &self.columns[18],
Category: &self.columns[19],
ItemCost: &self.columns[20],
Quest: &self.columns[21],
Unknown0: &self.columns[22],
AchievementUnlock: &self.columns[23],
Unknown2: &self.columns[24],
CollectabilityCost: &self.columns[25],
PatchNumber: &self.columns[26],
HqCost: &self.columns[27],
Unknown1: &self.columns[28],
Order: &self.columns[29],
ReceiveHq: &self.columns[30],
},
ItemElement {ReceiveCount: &self.columns[31],
CurrencyCost: &self.columns[32],
Item: &self.columns[33],
Category: &self.columns[34],
ItemCost: &self.columns[35],
Quest: &self.columns[36],
Unknown0: &self.columns[37],
AchievementUnlock: &self.columns[38],
Unknown2: &self.columns[39],
CollectabilityCost: &self.columns[40],
PatchNumber: &self.columns[41],
HqCost: &self.columns[42],
Unknown1: &self.columns[43],
Order: &self.columns[44],
ReceiveHq: &self.columns[45],
},
ItemElement {ReceiveCount: &self.columns[46],
CurrencyCost: &self.columns[47],
Item: &self.columns[48],
Category: &self.columns[49],
ItemCost: &self.columns[50],
Quest: &self.columns[51],
Unknown0: &self.columns[52],
AchievementUnlock: &self.columns[53],
Unknown2: &self.columns[54],
CollectabilityCost: &self.columns[55],
PatchNumber: &self.columns[56],
HqCost: &self.columns[57],
Unknown1: &self.columns[58],
Order: &self.columns[59],
ReceiveHq: &self.columns[60],
},
ItemElement {ReceiveCount: &self.columns[61],
CurrencyCost: &self.columns[62],
Item: &self.columns[63],
Category: &self.columns[64],
ItemCost: &self.columns[65],
Quest: &self.columns[66],
Unknown0: &self.columns[67],
AchievementUnlock: &self.columns[68],
Unknown2: &self.columns[69],
CollectabilityCost: &self.columns[70],
PatchNumber: &self.columns[71],
HqCost: &self.columns[72],
Unknown1: &self.columns[73],
Order: &self.columns[74],
ReceiveHq: &self.columns[75],
},
ItemElement {ReceiveCount: &self.columns[76],
CurrencyCost: &self.columns[77],
Item: &self.columns[78],
Category: &self.columns[79],
ItemCost: &self.columns[80],
Quest: &self.columns[81],
Unknown0: &self.columns[82],
AchievementUnlock: &self.columns[83],
Unknown2: &self.columns[84],
CollectabilityCost: &self.columns[85],
PatchNumber: &self.columns[86],
HqCost: &self.columns[87],
Unknown1: &self.columns[88],
Order: &self.columns[89],
ReceiveHq: &self.columns[90],
},
ItemElement {ReceiveCount: &self.columns[91],
CurrencyCost: &self.columns[92],
Item: &self.columns[93],
Category: &self.columns[94],
ItemCost: &self.columns[95],
Quest: &self.columns[96],
Unknown0: &self.columns[97],
AchievementUnlock: &self.columns[98],
Unknown2: &self.columns[99],
CollectabilityCost: &self.columns[100],
PatchNumber: &self.columns[101],
HqCost: &self.columns[102],
Unknown1: &self.columns[103],
Order: &self.columns[104],
ReceiveHq: &self.columns[105],
},
ItemElement {ReceiveCount: &self.columns[106],
CurrencyCost: &self.columns[107],
Item: &self.columns[108],
Category: &self.columns[109],
ItemCost: &self.columns[110],
Quest: &self.columns[111],
Unknown0: &self.columns[112],
AchievementUnlock: &self.columns[113],
Unknown2: &self.columns[114],
CollectabilityCost: &self.columns[115],
PatchNumber: &self.columns[116],
HqCost: &self.columns[117],
Unknown1: &self.columns[118],
Order: &self.columns[119],
ReceiveHq: &self.columns[120],
},
ItemElement {ReceiveCount: &self.columns[121],
CurrencyCost: &self.columns[122],
Item: &self.columns[123],
Category: &self.columns[124],
ItemCost: &self.columns[125],
Quest: &self.columns[126],
Unknown0: &self.columns[127],
AchievementUnlock: &self.columns[128],
Unknown2: &self.columns[129],
CollectabilityCost: &self.columns[130],
PatchNumber: &self.columns[131],
HqCost: &self.columns[132],
Unknown1: &self.columns[133],
Order: &self.columns[134],
ReceiveHq: &self.columns[135],
},
ItemElement {ReceiveCount: &self.columns[136],
CurrencyCost: &self.columns[137],
Item: &self.columns[138],
Category: &self.columns[139],
ItemCost: &self.columns[140],
Quest: &self.columns[141],
Unknown0: &self.columns[142],
AchievementUnlock: &self.columns[143],
Unknown2: &self.columns[144],
CollectabilityCost: &self.columns[145],
PatchNumber: &self.columns[146],
HqCost: &self.columns[147],
Unknown1: &self.columns[148],
Order: &self.columns[149],
ReceiveHq: &self.columns[150],
},
ItemElement {ReceiveCount: &self.columns[151],
CurrencyCost: &self.columns[152],
Item: &self.columns[153],
Category: &self.columns[154],
ItemCost: &self.columns[155],
Quest: &self.columns[156],
Unknown0: &self.columns[157],
AchievementUnlock: &self.columns[158],
Unknown2: &self.columns[159],
CollectabilityCost: &self.columns[160],
PatchNumber: &self.columns[161],
HqCost: &self.columns[162],
Unknown1: &self.columns[163],
Order: &self.columns[164],
ReceiveHq: &self.columns[165],
},
ItemElement {ReceiveCount: &self.columns[166],
CurrencyCost: &self.columns[167],
Item: &self.columns[168],
Category: &self.columns[169],
ItemCost: &self.columns[170],
Quest: &self.columns[171],
Unknown0: &self.columns[172],
AchievementUnlock: &self.columns[173],
Unknown2: &self.columns[174],
CollectabilityCost: &self.columns[175],
PatchNumber: &self.columns[176],
HqCost: &self.columns[177],
Unknown1: &self.columns[178],
Order: &self.columns[179],
ReceiveHq: &self.columns[180],
},
ItemElement {ReceiveCount: &self.columns[181],
CurrencyCost: &self.columns[182],
Item: &self.columns[183],
Category: &self.columns[184],
ItemCost: &self.columns[185],
Quest: &self.columns[186],
Unknown0: &self.columns[187],
AchievementUnlock: &self.columns[188],
Unknown2: &self.columns[189],
CollectabilityCost: &self.columns[190],
PatchNumber: &self.columns[191],
HqCost: &self.columns[192],
Unknown1: &self.columns[193],
Order: &self.columns[194],
ReceiveHq: &self.columns[195],
},
ItemElement {ReceiveCount: &self.columns[196],
CurrencyCost: &self.columns[197],
Item: &self.columns[198],
Category: &self.columns[199],
ItemCost: &self.columns[200],
Quest: &self.columns[201],
Unknown0: &self.columns[202],
AchievementUnlock: &self.columns[203],
Unknown2: &self.columns[204],
CollectabilityCost: &self.columns[205],
PatchNumber: &self.columns[206],
HqCost: &self.columns[207],
Unknown1: &self.columns[208],
Order: &self.columns[209],
ReceiveHq: &self.columns[210],
},
ItemElement {ReceiveCount: &self.columns[211],
CurrencyCost: &self.columns[212],
Item: &self.columns[213],
Category: &self.columns[214],
ItemCost: &self.columns[215],
Quest: &self.columns[216],
Unknown0: &self.columns[217],
AchievementUnlock: &self.columns[218],
Unknown2: &self.columns[219],
CollectabilityCost: &self.columns[220],
PatchNumber: &self.columns[221],
HqCost: &self.columns[222],
Unknown1: &self.columns[223],
Order: &self.columns[224],
ReceiveHq: &self.columns[225],
},
ItemElement {ReceiveCount: &self.columns[226],
CurrencyCost: &self.columns[227],
Item: &self.columns[228],
Category: &self.columns[229],
ItemCost: &self.columns[230],
Quest: &self.columns[231],
Unknown0: &self.columns[232],
AchievementUnlock: &self.columns[233],
Unknown2: &self.columns[234],
CollectabilityCost: &self.columns[235],
PatchNumber: &self.columns[236],
HqCost: &self.columns[237],
Unknown1: &self.columns[238],
Order: &self.columns[239],
ReceiveHq: &self.columns[240],
},
ItemElement {ReceiveCount: &self.columns[241],
CurrencyCost: &self.columns[242],
Item: &self.columns[243],
Category: &self.columns[244],
ItemCost: &self.columns[245],
Quest: &self.columns[246],
Unknown0: &self.columns[247],
AchievementUnlock: &self.columns[248],
Unknown2: &self.columns[249],
CollectabilityCost: &self.columns[250],
PatchNumber: &self.columns[251],
HqCost: &self.columns[252],
Unknown1: &self.columns[253],
Order: &self.columns[254],
ReceiveHq: &self.columns[255],
},
ItemElement {ReceiveCount: &self.columns[256],
CurrencyCost: &self.columns[257],
Item: &self.columns[258],
Category: &self.columns[259],
ItemCost: &self.columns[260],
Quest: &self.columns[261],
Unknown0: &self.columns[262],
AchievementUnlock: &self.columns[263],
Unknown2: &self.columns[264],
CollectabilityCost: &self.columns[265],
PatchNumber: &self.columns[266],
HqCost: &self.columns[267],
Unknown1: &self.columns[268],
Order: &self.columns[269],
ReceiveHq: &self.columns[270],
},
ItemElement {ReceiveCount: &self.columns[271],
CurrencyCost: &self.columns[272],
Item: &self.columns[273],
Category: &self.columns[274],
ItemCost: &self.columns[275],
Quest: &self.columns[276],
Unknown0: &self.columns[277],
AchievementUnlock: &self.columns[278],
Unknown2: &self.columns[279],
CollectabilityCost: &self.columns[280],
PatchNumber: &self.columns[281],
HqCost: &self.columns[282],
Unknown1: &self.columns[283],
Order: &self.columns[284],
ReceiveHq: &self.columns[285],
},
ItemElement {ReceiveCount: &self.columns[286],
CurrencyCost: &self.columns[287],
Item: &self.columns[288],
Category: &self.columns[289],
ItemCost: &self.columns[290],
Quest: &self.columns[291],
Unknown0: &self.columns[292],
AchievementUnlock: &self.columns[293],
Unknown2: &self.columns[294],
CollectabilityCost: &self.columns[295],
PatchNumber: &self.columns[296],
HqCost: &self.columns[297],
Unknown1: &self.columns[298],
Order: &self.columns[299],
ReceiveHq: &self.columns[300],
},
ItemElement {ReceiveCount: &self.columns[301],
CurrencyCost: &self.columns[302],
Item: &self.columns[303],
Category: &self.columns[304],
ItemCost: &self.columns[305],
Quest: &self.columns[306],
Unknown0: &self.columns[307],
AchievementUnlock: &self.columns[308],
Unknown2: &self.columns[309],
CollectabilityCost: &self.columns[310],
PatchNumber: &self.columns[311],
HqCost: &self.columns[312],
Unknown1: &self.columns[313],
Order: &self.columns[314],
ReceiveHq: &self.columns[315],
},
ItemElement {ReceiveCount: &self.columns[316],
CurrencyCost: &self.columns[317],
Item: &self.columns[318],
Category: &self.columns[319],
ItemCost: &self.columns[320],
Quest: &self.columns[321],
Unknown0: &self.columns[322],
AchievementUnlock: &self.columns[323],
Unknown2: &self.columns[324],
CollectabilityCost: &self.columns[325],
PatchNumber: &self.columns[326],
HqCost: &self.columns[327],
Unknown1: &self.columns[328],
Order: &self.columns[329],
ReceiveHq: &self.columns[330],
},
ItemElement {ReceiveCount: &self.columns[331],
CurrencyCost: &self.columns[332],
Item: &self.columns[333],
Category: &self.columns[334],
ItemCost: &self.columns[335],
Quest: &self.columns[336],
Unknown0: &self.columns[337],
AchievementUnlock: &self.columns[338],
Unknown2: &self.columns[339],
CollectabilityCost: &self.columns[340],
PatchNumber: &self.columns[341],
HqCost: &self.columns[342],
Unknown1: &self.columns[343],
Order: &self.columns[344],
ReceiveHq: &self.columns[345],
},
ItemElement {ReceiveCount: &self.columns[346],
CurrencyCost: &self.columns[347],
Item: &self.columns[348],
Category: &self.columns[349],
ItemCost: &self.columns[350],
Quest: &self.columns[351],
Unknown0: &self.columns[352],
AchievementUnlock: &self.columns[353],
Unknown2: &self.columns[354],
CollectabilityCost: &self.columns[355],
PatchNumber: &self.columns[356],
HqCost: &self.columns[357],
Unknown1: &self.columns[358],
Order: &self.columns[359],
ReceiveHq: &self.columns[360],
},
ItemElement {ReceiveCount: &self.columns[361],
CurrencyCost: &self.columns[362],
Item: &self.columns[363],
Category: &self.columns[364],
ItemCost: &self.columns[365],
Quest: &self.columns[366],
Unknown0: &self.columns[367],
AchievementUnlock: &self.columns[368],
Unknown2: &self.columns[369],
CollectabilityCost: &self.columns[370],
PatchNumber: &self.columns[371],
HqCost: &self.columns[372],
Unknown1: &self.columns[373],
Order: &self.columns[374],
ReceiveHq: &self.columns[375],
},
ItemElement {ReceiveCount: &self.columns[376],
CurrencyCost: &self.columns[377],
Item: &self.columns[378],
Category: &self.columns[379],
ItemCost: &self.columns[380],
Quest: &self.columns[381],
Unknown0: &self.columns[382],
AchievementUnlock: &self.columns[383],
Unknown2: &self.columns[384],
CollectabilityCost: &self.columns[385],
PatchNumber: &self.columns[386],
HqCost: &self.columns[387],
Unknown1: &self.columns[388],
Order: &self.columns[389],
ReceiveHq: &self.columns[390],
},
ItemElement {ReceiveCount: &self.columns[391],
CurrencyCost: &self.columns[392],
Item: &self.columns[393],
Category: &self.columns[394],
ItemCost: &self.columns[395],
Quest: &self.columns[396],
Unknown0: &self.columns[397],
AchievementUnlock: &self.columns[398],
Unknown2: &self.columns[399],
CollectabilityCost: &self.columns[400],
PatchNumber: &self.columns[401],
HqCost: &self.columns[402],
Unknown1: &self.columns[403],
Order: &self.columns[404],
ReceiveHq: &self.columns[405],
},
ItemElement {ReceiveCount: &self.columns[406],
CurrencyCost: &self.columns[407],
Item: &self.columns[408],
Category: &self.columns[409],
ItemCost: &self.columns[410],
Quest: &self.columns[411],
Unknown0: &self.columns[412],
AchievementUnlock: &self.columns[413],
Unknown2: &self.columns[414],
CollectabilityCost: &self.columns[415],
PatchNumber: &self.columns[416],
HqCost: &self.columns[417],
Unknown1: &self.columns[418],
Order: &self.columns[419],
ReceiveHq: &self.columns[420],
},
ItemElement {ReceiveCount: &self.columns[421],
CurrencyCost: &self.columns[422],
Item: &self.columns[423],
Category: &self.columns[424],
ItemCost: &self.columns[425],
Quest: &self.columns[426],
Unknown0: &self.columns[427],
AchievementUnlock: &self.columns[428],
Unknown2: &self.columns[429],
CollectabilityCost: &self.columns[430],
PatchNumber: &self.columns[431],
HqCost: &self.columns[432],
Unknown1: &self.columns[433],
Order: &self.columns[434],
ReceiveHq: &self.columns[435],
},
ItemElement {ReceiveCount: &self.columns[436],
CurrencyCost: &self.columns[437],
Item: &self.columns[438],
Category: &self.columns[439],
ItemCost: &self.columns[440],
Quest: &self.columns[441],
Unknown0: &self.columns[442],
AchievementUnlock: &self.columns[443],
Unknown2: &self.columns[444],
CollectabilityCost: &self.columns[445],
PatchNumber: &self.columns[446],
HqCost: &self.columns[447],
Unknown1: &self.columns[448],
Order: &self.columns[449],
ReceiveHq: &self.columns[450],
},
ItemElement {ReceiveCount: &self.columns[451],
CurrencyCost: &self.columns[452],
Item: &self.columns[453],
Category: &self.columns[454],
ItemCost: &self.columns[455],
Quest: &self.columns[456],
Unknown0: &self.columns[457],
AchievementUnlock: &self.columns[458],
Unknown2: &self.columns[459],
CollectabilityCost: &self.columns[460],
PatchNumber: &self.columns[461],
HqCost: &self.columns[462],
Unknown1: &self.columns[463],
Order: &self.columns[464],
ReceiveHq: &self.columns[465],
},
ItemElement {ReceiveCount: &self.columns[466],
CurrencyCost: &self.columns[467],
Item: &self.columns[468],
Category: &self.columns[469],
ItemCost: &self.columns[470],
Quest: &self.columns[471],
Unknown0: &self.columns[472],
AchievementUnlock: &self.columns[473],
Unknown2: &self.columns[474],
CollectabilityCost: &self.columns[475],
PatchNumber: &self.columns[476],
HqCost: &self.columns[477],
Unknown1: &self.columns[478],
Order: &self.columns[479],
ReceiveHq: &self.columns[480],
},
ItemElement {ReceiveCount: &self.columns[481],
CurrencyCost: &self.columns[482],
Item: &self.columns[483],
Category: &self.columns[484],
ItemCost: &self.columns[485],
Quest: &self.columns[486],
Unknown0: &self.columns[487],
AchievementUnlock: &self.columns[488],
Unknown2: &self.columns[489],
CollectabilityCost: &self.columns[490],
PatchNumber: &self.columns[491],
HqCost: &self.columns[492],
Unknown1: &self.columns[493],
Order: &self.columns[494],
ReceiveHq: &self.columns[495],
},
ItemElement {ReceiveCount: &self.columns[496],
CurrencyCost: &self.columns[497],
Item: &self.columns[498],
Category: &self.columns[499],
ItemCost: &self.columns[500],
Quest: &self.columns[501],
Unknown0: &self.columns[502],
AchievementUnlock: &self.columns[503],
Unknown2: &self.columns[504],
CollectabilityCost: &self.columns[505],
PatchNumber: &self.columns[506],
HqCost: &self.columns[507],
Unknown1: &self.columns[508],
Order: &self.columns[509],
ReceiveHq: &self.columns[510],
},
ItemElement {ReceiveCount: &self.columns[511],
CurrencyCost: &self.columns[512],
Item: &self.columns[513],
Category: &self.columns[514],
ItemCost: &self.columns[515],
Quest: &self.columns[516],
Unknown0: &self.columns[517],
AchievementUnlock: &self.columns[518],
Unknown2: &self.columns[519],
CollectabilityCost: &self.columns[520],
PatchNumber: &self.columns[521],
HqCost: &self.columns[522],
Unknown1: &self.columns[523],
Order: &self.columns[524],
ReceiveHq: &self.columns[525],
},
ItemElement {ReceiveCount: &self.columns[526],
CurrencyCost: &self.columns[527],
Item: &self.columns[528],
Category: &self.columns[529],
ItemCost: &self.columns[530],
Quest: &self.columns[531],
Unknown0: &self.columns[532],
AchievementUnlock: &self.columns[533],
Unknown2: &self.columns[534],
CollectabilityCost: &self.columns[535],
PatchNumber: &self.columns[536],
HqCost: &self.columns[537],
Unknown1: &self.columns[538],
Order: &self.columns[539],
ReceiveHq: &self.columns[540],
},
ItemElement {ReceiveCount: &self.columns[541],
CurrencyCost: &self.columns[542],
Item: &self.columns[543],
Category: &self.columns[544],
ItemCost: &self.columns[545],
Quest: &self.columns[546],
Unknown0: &self.columns[547],
AchievementUnlock: &self.columns[548],
Unknown2: &self.columns[549],
CollectabilityCost: &self.columns[550],
PatchNumber: &self.columns[551],
HqCost: &self.columns[552],
Unknown1: &self.columns[553],
Order: &self.columns[554],
ReceiveHq: &self.columns[555],
},
ItemElement {ReceiveCount: &self.columns[556],
CurrencyCost: &self.columns[557],
Item: &self.columns[558],
Category: &self.columns[559],
ItemCost: &self.columns[560],
Quest: &self.columns[561],
Unknown0: &self.columns[562],
AchievementUnlock: &self.columns[563],
Unknown2: &self.columns[564],
CollectabilityCost: &self.columns[565],
PatchNumber: &self.columns[566],
HqCost: &self.columns[567],
Unknown1: &self.columns[568],
Order: &self.columns[569],
ReceiveHq: &self.columns[570],
},
ItemElement {ReceiveCount: &self.columns[571],
CurrencyCost: &self.columns[572],
Item: &self.columns[573],
Category: &self.columns[574],
ItemCost: &self.columns[575],
Quest: &self.columns[576],
Unknown0: &self.columns[577],
AchievementUnlock: &self.columns[578],
Unknown2: &self.columns[579],
CollectabilityCost: &self.columns[580],
PatchNumber: &self.columns[581],
HqCost: &self.columns[582],
Unknown1: &self.columns[583],
Order: &self.columns[584],
ReceiveHq: &self.columns[585],
},
ItemElement {ReceiveCount: &self.columns[586],
CurrencyCost: &self.columns[587],
Item: &self.columns[588],
Category: &self.columns[589],
ItemCost: &self.columns[590],
Quest: &self.columns[591],
Unknown0: &self.columns[592],
AchievementUnlock: &self.columns[593],
Unknown2: &self.columns[594],
CollectabilityCost: &self.columns[595],
PatchNumber: &self.columns[596],
HqCost: &self.columns[597],
Unknown1: &self.columns[598],
Order: &self.columns[599],
ReceiveHq: &self.columns[600],
},
ItemElement {ReceiveCount: &self.columns[601],
CurrencyCost: &self.columns[602],
Item: &self.columns[603],
Category: &self.columns[604],
ItemCost: &self.columns[605],
Quest: &self.columns[606],
Unknown0: &self.columns[607],
AchievementUnlock: &self.columns[608],
Unknown2: &self.columns[609],
CollectabilityCost: &self.columns[610],
PatchNumber: &self.columns[611],
HqCost: &self.columns[612],
Unknown1: &self.columns[613],
Order: &self.columns[614],
ReceiveHq: &self.columns[615],
},
ItemElement {ReceiveCount: &self.columns[616],
CurrencyCost: &self.columns[617],
Item: &self.columns[618],
Category: &self.columns[619],
ItemCost: &self.columns[620],
Quest: &self.columns[621],
Unknown0: &self.columns[622],
AchievementUnlock: &self.columns[623],
Unknown2: &self.columns[624],
CollectabilityCost: &self.columns[625],
PatchNumber: &self.columns[626],
HqCost: &self.columns[627],
Unknown1: &self.columns[628],
Order: &self.columns[629],
ReceiveHq: &self.columns[630],
},
ItemElement {ReceiveCount: &self.columns[631],
CurrencyCost: &self.columns[632],
Item: &self.columns[633],
Category: &self.columns[634],
ItemCost: &self.columns[635],
Quest: &self.columns[636],
Unknown0: &self.columns[637],
AchievementUnlock: &self.columns[638],
Unknown2: &self.columns[639],
CollectabilityCost: &self.columns[640],
PatchNumber: &self.columns[641],
HqCost: &self.columns[642],
Unknown1: &self.columns[643],
Order: &self.columns[644],
ReceiveHq: &self.columns[645],
},
ItemElement {ReceiveCount: &self.columns[646],
CurrencyCost: &self.columns[647],
Item: &self.columns[648],
Category: &self.columns[649],
ItemCost: &self.columns[650],
Quest: &self.columns[651],
Unknown0: &self.columns[652],
AchievementUnlock: &self.columns[653],
Unknown2: &self.columns[654],
CollectabilityCost: &self.columns[655],
PatchNumber: &self.columns[656],
HqCost: &self.columns[657],
Unknown1: &self.columns[658],
Order: &self.columns[659],
ReceiveHq: &self.columns[660],
},
ItemElement {ReceiveCount: &self.columns[661],
CurrencyCost: &self.columns[662],
Item: &self.columns[663],
Category: &self.columns[664],
ItemCost: &self.columns[665],
Quest: &self.columns[666],
Unknown0: &self.columns[667],
AchievementUnlock: &self.columns[668],
Unknown2: &self.columns[669],
CollectabilityCost: &self.columns[670],
PatchNumber: &self.columns[671],
HqCost: &self.columns[672],
Unknown1: &self.columns[673],
Order: &self.columns[674],
ReceiveHq: &self.columns[675],
},
ItemElement {ReceiveCount: &self.columns[676],
CurrencyCost: &self.columns[677],
Item: &self.columns[678],
Category: &self.columns[679],
ItemCost: &self.columns[680],
Quest: &self.columns[681],
Unknown0: &self.columns[682],
AchievementUnlock: &self.columns[683],
Unknown2: &self.columns[684],
CollectabilityCost: &self.columns[685],
PatchNumber: &self.columns[686],
HqCost: &self.columns[687],
Unknown1: &self.columns[688],
Order: &self.columns[689],
ReceiveHq: &self.columns[690],
},
ItemElement {ReceiveCount: &self.columns[691],
CurrencyCost: &self.columns[692],
Item: &self.columns[693],
Category: &self.columns[694],
ItemCost: &self.columns[695],
Quest: &self.columns[696],
Unknown0: &self.columns[697],
AchievementUnlock: &self.columns[698],
Unknown2: &self.columns[699],
CollectabilityCost: &self.columns[700],
PatchNumber: &self.columns[701],
HqCost: &self.columns[702],
Unknown1: &self.columns[703],
Order: &self.columns[704],
ReceiveHq: &self.columns[705],
},
ItemElement {ReceiveCount: &self.columns[706],
CurrencyCost: &self.columns[707],
Item: &self.columns[708],
Category: &self.columns[709],
ItemCost: &self.columns[710],
Quest: &self.columns[711],
Unknown0: &self.columns[712],
AchievementUnlock: &self.columns[713],
Unknown2: &self.columns[714],
CollectabilityCost: &self.columns[715],
PatchNumber: &self.columns[716],
HqCost: &self.columns[717],
Unknown1: &self.columns[718],
Order: &self.columns[719],
ReceiveHq: &self.columns[720],
},
ItemElement {ReceiveCount: &self.columns[721],
CurrencyCost: &self.columns[722],
Item: &self.columns[723],
Category: &self.columns[724],
ItemCost: &self.columns[725],
Quest: &self.columns[726],
Unknown0: &self.columns[727],
AchievementUnlock: &self.columns[728],
Unknown2: &self.columns[729],
CollectabilityCost: &self.columns[730],
PatchNumber: &self.columns[731],
HqCost: &self.columns[732],
Unknown1: &self.columns[733],
Order: &self.columns[734],
ReceiveHq: &self.columns[735],
},
ItemElement {ReceiveCount: &self.columns[736],
CurrencyCost: &self.columns[737],
Item: &self.columns[738],
Category: &self.columns[739],
ItemCost: &self.columns[740],
Quest: &self.columns[741],
Unknown0: &self.columns[742],
AchievementUnlock: &self.columns[743],
Unknown2: &self.columns[744],
CollectabilityCost: &self.columns[745],
PatchNumber: &self.columns[746],
HqCost: &self.columns[747],
Unknown1: &self.columns[748],
Order: &self.columns[749],
ReceiveHq: &self.columns[750],
},
ItemElement {ReceiveCount: &self.columns[751],
CurrencyCost: &self.columns[752],
Item: &self.columns[753],
Category: &self.columns[754],
ItemCost: &self.columns[755],
Quest: &self.columns[756],
Unknown0: &self.columns[757],
AchievementUnlock: &self.columns[758],
Unknown2: &self.columns[759],
CollectabilityCost: &self.columns[760],
PatchNumber: &self.columns[761],
HqCost: &self.columns[762],
Unknown1: &self.columns[763],
Order: &self.columns[764],
ReceiveHq: &self.columns[765],
},
ItemElement {ReceiveCount: &self.columns[766],
CurrencyCost: &self.columns[767],
Item: &self.columns[768],
Category: &self.columns[769],
ItemCost: &self.columns[770],
Quest: &self.columns[771],
Unknown0: &self.columns[772],
AchievementUnlock: &self.columns[773],
Unknown2: &self.columns[774],
CollectabilityCost: &self.columns[775],
PatchNumber: &self.columns[776],
HqCost: &self.columns[777],
Unknown1: &self.columns[778],
Order: &self.columns[779],
ReceiveHq: &self.columns[780],
},
ItemElement {ReceiveCount: &self.columns[781],
CurrencyCost: &self.columns[782],
Item: &self.columns[783],
Category: &self.columns[784],
ItemCost: &self.columns[785],
Quest: &self.columns[786],
Unknown0: &self.columns[787],
AchievementUnlock: &self.columns[788],
Unknown2: &self.columns[789],
CollectabilityCost: &self.columns[790],
PatchNumber: &self.columns[791],
HqCost: &self.columns[792],
Unknown1: &self.columns[793],
Order: &self.columns[794],
ReceiveHq: &self.columns[795],
},
ItemElement {ReceiveCount: &self.columns[796],
CurrencyCost: &self.columns[797],
Item: &self.columns[798],
Category: &self.columns[799],
ItemCost: &self.columns[800],
Quest: &self.columns[801],
Unknown0: &self.columns[802],
AchievementUnlock: &self.columns[803],
Unknown2: &self.columns[804],
CollectabilityCost: &self.columns[805],
PatchNumber: &self.columns[806],
HqCost: &self.columns[807],
Unknown1: &self.columns[808],
Order: &self.columns[809],
ReceiveHq: &self.columns[810],
},
ItemElement {ReceiveCount: &self.columns[811],
CurrencyCost: &self.columns[812],
Item: &self.columns[813],
Category: &self.columns[814],
ItemCost: &self.columns[815],
Quest: &self.columns[816],
Unknown0: &self.columns[817],
AchievementUnlock: &self.columns[818],
Unknown2: &self.columns[819],
CollectabilityCost: &self.columns[820],
PatchNumber: &self.columns[821],
HqCost: &self.columns[822],
Unknown1: &self.columns[823],
Order: &self.columns[824],
ReceiveHq: &self.columns[825],
},
ItemElement {ReceiveCount: &self.columns[826],
CurrencyCost: &self.columns[827],
Item: &self.columns[828],
Category: &self.columns[829],
ItemCost: &self.columns[830],
Quest: &self.columns[831],
Unknown0: &self.columns[832],
AchievementUnlock: &self.columns[833],
Unknown2: &self.columns[834],
CollectabilityCost: &self.columns[835],
PatchNumber: &self.columns[836],
HqCost: &self.columns[837],
Unknown1: &self.columns[838],
Order: &self.columns[839],
ReceiveHq: &self.columns[840],
},
ItemElement {ReceiveCount: &self.columns[841],
CurrencyCost: &self.columns[842],
Item: &self.columns[843],
Category: &self.columns[844],
ItemCost: &self.columns[845],
Quest: &self.columns[846],
Unknown0: &self.columns[847],
AchievementUnlock: &self.columns[848],
Unknown2: &self.columns[849],
CollectabilityCost: &self.columns[850],
PatchNumber: &self.columns[851],
HqCost: &self.columns[852],
Unknown1: &self.columns[853],
Order: &self.columns[854],
ReceiveHq: &self.columns[855],
},
ItemElement {ReceiveCount: &self.columns[856],
CurrencyCost: &self.columns[857],
Item: &self.columns[858],
Category: &self.columns[859],
ItemCost: &self.columns[860],
Quest: &self.columns[861],
Unknown0: &self.columns[862],
AchievementUnlock: &self.columns[863],
Unknown2: &self.columns[864],
CollectabilityCost: &self.columns[865],
PatchNumber: &self.columns[866],
HqCost: &self.columns[867],
Unknown1: &self.columns[868],
Order: &self.columns[869],
ReceiveHq: &self.columns[870],
},
ItemElement {ReceiveCount: &self.columns[871],
CurrencyCost: &self.columns[872],
Item: &self.columns[873],
Category: &self.columns[874],
ItemCost: &self.columns[875],
Quest: &self.columns[876],
Unknown0: &self.columns[877],
AchievementUnlock: &self.columns[878],
Unknown2: &self.columns[879],
CollectabilityCost: &self.columns[880],
PatchNumber: &self.columns[881],
HqCost: &self.columns[882],
Unknown1: &self.columns[883],
Order: &self.columns[884],
ReceiveHq: &self.columns[885],
},
ItemElement {ReceiveCount: &self.columns[886],
CurrencyCost: &self.columns[887],
Item: &self.columns[888],
Category: &self.columns[889],
ItemCost: &self.columns[890],
Quest: &self.columns[891],
Unknown0: &self.columns[892],
AchievementUnlock: &self.columns[893],
Unknown2: &self.columns[894],
CollectabilityCost: &self.columns[895],
PatchNumber: &self.columns[896],
HqCost: &self.columns[897],
Unknown1: &self.columns[898],
Order: &self.columns[899],
ReceiveHq: &self.columns[900],
},
]
}
pub fn Quest(&self) -> &ColumnData {
&self.columns[901]
}
pub fn Unknown0(&self) -> &ColumnData {
&self.columns[902]
}
pub fn RequiredContentFinderCondition(&self) -> &ColumnData {
&self.columns[903]
}
pub fn CompleteText(&self) -> &ColumnData {
&self.columns[904]
}
pub fn NotCompleteText(&self) -> &ColumnData {
&self.columns[905]
}
pub fn RequiredFestival(&self) -> &ColumnData {
&self.columns[906]
}
pub fn RequiredFestivalPhase(&self) -> &ColumnData {
&self.columns[907]
}
pub fn UseCurrencyType(&self) -> &ColumnData {
&self.columns[908]
}
pub fn Unknown3(&self) -> &ColumnData {
&self.columns[909]
}
/// If this is true, then the CFC needs to be completed; If this is false, then the CFC just needs to be unlocked
pub fn RequiredContentFinderConditionComplete(&self) -> &ColumnData {
&self.columns[910]
}
}
