#![allow(warnings)]
/// This file is auto-generated! It is generated from schema from https://github.com/xivdev/EXDSchema.
use physis::{resource::{Resource, read_excel_sheet_header, read_excel_sheet}, exd::{EXD, ColumnData, ExcelRowKind, ExcelSingleRow}, exh::{EXH, ExcelColumnDefinition}, common::Language};
pub struct StoryParamsElement<'a> {
Instruction: &'a ColumnData,
Argument: &'a ColumnData,
}
pub struct StoryDefineElement<'a> {
CompletedQuest: &'a ColumnData,
AcceptedQuest: &'a ColumnData,
LayerSet: &'a ColumnData,
Sequence: &'a ColumnData,
CompletedQuestOperator: &'a ColumnData,
AcceptedQuestOperator: &'a ColumnData,
AcceptedQuestSequence: &'a ColumnData,
}
pub struct StoryListenerElement<'a> {
Listener: &'a ColumnData,
SequenceBegin: &'a ColumnData,
SequenceEnd: &'a ColumnData,
}
pub struct StorySheet {
pages: Vec<EXD>,
exh: EXH,
row_count: u32,
}
impl StorySheet {
pub fn read_from<T: Resource>(resource: &mut T, language: Language) -> Option<Self> {
let exh = read_excel_sheet_header(resource, "Story")?;
let mut pages = Vec::new();
for (i, _) in exh.pages.iter().enumerate() {
pages.push(read_excel_sheet(resource, "Story", &exh, language, i)?);
}let row_count = exh.header.row_count;
Some(Self {
exh,
pages,
row_count,
})
}
fn read_row(&self, row: &ExcelSingleRow) -> Option<StoryRow> {
let column_defs = &self.exh.column_definitions;
let mut zipped: Vec<_> = row.columns.clone().into_iter().zip(column_defs).collect();
zipped.sort_by(|(_, a_col), (_, b_col)| a_col.offset.cmp(&b_col.offset));
let (columns, _): (Vec<ColumnData>, Vec<ExcelColumnDefinition> ) = zipped.into_iter().unzip();
Some(StoryRow { columns })
}
/// Fetches a single row from the sheet. If the row contains subrows, it returns the first one.
pub fn get_row(&self, row_id: u32) -> Option<StoryRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => row,
ExcelRowKind::SubRows(rows) => &rows.first()?.1,
};
return self.read_row(row);
}
None
}
/// Fetches the specified subrow from the sheet.
pub fn get_subrow(&self, row_id: u32, subrow_id: u16) -> Option<StoryRow> {
for page in &self.pages {
let Some(row) = &page.get_row(row_id) else { continue; };
let row = match row {
ExcelRowKind::SingleRow(row) => return None,
ExcelRowKind::SubRows(subrows) => &subrows.iter().filter(|(id, _)| *id == subrow_id).next()?.1,
};
return self.read_row(row);
}
None
}
/// Returns the number of rows in this sheet.
pub fn row_count(&self) -> u32 {
self.row_count
}
}
pub struct StoryRow {
columns: Vec<ColumnData>,
}
impl StoryRow {
pub fn StoryParams<'a>(&'a self) -> [StoryParamsElement<'a>; 40] {
[StoryParamsElement {Instruction: &self.columns[0],
Argument: &self.columns[1],
},
StoryParamsElement {Instruction: &self.columns[2],
Argument: &self.columns[3],
},
StoryParamsElement {Instruction: &self.columns[4],
Argument: &self.columns[5],
},
StoryParamsElement {Instruction: &self.columns[6],
Argument: &self.columns[7],
},
StoryParamsElement {Instruction: &self.columns[8],
Argument: &self.columns[9],
},
StoryParamsElement {Instruction: &self.columns[10],
Argument: &self.columns[11],
},
StoryParamsElement {Instruction: &self.columns[12],
Argument: &self.columns[13],
},
StoryParamsElement {Instruction: &self.columns[14],
Argument: &self.columns[15],
},
StoryParamsElement {Instruction: &self.columns[16],
Argument: &self.columns[17],
},
StoryParamsElement {Instruction: &self.columns[18],
Argument: &self.columns[19],
},
StoryParamsElement {Instruction: &self.columns[20],
Argument: &self.columns[21],
},
StoryParamsElement {Instruction: &self.columns[22],
Argument: &self.columns[23],
},
StoryParamsElement {Instruction: &self.columns[24],
Argument: &self.columns[25],
},
StoryParamsElement {Instruction: &self.columns[26],
Argument: &self.columns[27],
},
StoryParamsElement {Instruction: &self.columns[28],
Argument: &self.columns[29],
},
StoryParamsElement {Instruction: &self.columns[30],
Argument: &self.columns[31],
},
StoryParamsElement {Instruction: &self.columns[32],
Argument: &self.columns[33],
},
StoryParamsElement {Instruction: &self.columns[34],
Argument: &self.columns[35],
},
StoryParamsElement {Instruction: &self.columns[36],
Argument: &self.columns[37],
},
StoryParamsElement {Instruction: &self.columns[38],
Argument: &self.columns[39],
},
StoryParamsElement {Instruction: &self.columns[40],
Argument: &self.columns[41],
},
StoryParamsElement {Instruction: &self.columns[42],
Argument: &self.columns[43],
},
StoryParamsElement {Instruction: &self.columns[44],
Argument: &self.columns[45],
},
StoryParamsElement {Instruction: &self.columns[46],
Argument: &self.columns[47],
},
StoryParamsElement {Instruction: &self.columns[48],
Argument: &self.columns[49],
},
StoryParamsElement {Instruction: &self.columns[50],
Argument: &self.columns[51],
},
StoryParamsElement {Instruction: &self.columns[52],
Argument: &self.columns[53],
},
StoryParamsElement {Instruction: &self.columns[54],
Argument: &self.columns[55],
},
StoryParamsElement {Instruction: &self.columns[56],
Argument: &self.columns[57],
},
StoryParamsElement {Instruction: &self.columns[58],
Argument: &self.columns[59],
},
StoryParamsElement {Instruction: &self.columns[60],
Argument: &self.columns[61],
},
StoryParamsElement {Instruction: &self.columns[62],
Argument: &self.columns[63],
},
StoryParamsElement {Instruction: &self.columns[64],
Argument: &self.columns[65],
},
StoryParamsElement {Instruction: &self.columns[66],
Argument: &self.columns[67],
},
StoryParamsElement {Instruction: &self.columns[68],
Argument: &self.columns[69],
},
StoryParamsElement {Instruction: &self.columns[70],
Argument: &self.columns[71],
},
StoryParamsElement {Instruction: &self.columns[72],
Argument: &self.columns[73],
},
StoryParamsElement {Instruction: &self.columns[74],
Argument: &self.columns[75],
},
StoryParamsElement {Instruction: &self.columns[76],
Argument: &self.columns[77],
},
StoryParamsElement {Instruction: &self.columns[78],
Argument: &self.columns[79],
},
]
}
pub fn StoryDefine<'a>(&'a self) -> [StoryDefineElement<'a>; 110] {
[StoryDefineElement {CompletedQuest: &self.columns[80],
AcceptedQuest: &self.columns[81],
LayerSet: &self.columns[82],
Sequence: &self.columns[83],
CompletedQuestOperator: &self.columns[84],
AcceptedQuestOperator: &self.columns[85],
AcceptedQuestSequence: &self.columns[86],
},
StoryDefineElement {CompletedQuest: &self.columns[87],
AcceptedQuest: &self.columns[88],
LayerSet: &self.columns[89],
Sequence: &self.columns[90],
CompletedQuestOperator: &self.columns[91],
AcceptedQuestOperator: &self.columns[92],
AcceptedQuestSequence: &self.columns[93],
},
StoryDefineElement {CompletedQuest: &self.columns[94],
AcceptedQuest: &self.columns[95],
LayerSet: &self.columns[96],
Sequence: &self.columns[97],
CompletedQuestOperator: &self.columns[98],
AcceptedQuestOperator: &self.columns[99],
AcceptedQuestSequence: &self.columns[100],
},
StoryDefineElement {CompletedQuest: &self.columns[101],
AcceptedQuest: &self.columns[102],
LayerSet: &self.columns[103],
Sequence: &self.columns[104],
CompletedQuestOperator: &self.columns[105],
AcceptedQuestOperator: &self.columns[106],
AcceptedQuestSequence: &self.columns[107],
},
StoryDefineElement {CompletedQuest: &self.columns[108],
AcceptedQuest: &self.columns[109],
LayerSet: &self.columns[110],
Sequence: &self.columns[111],
CompletedQuestOperator: &self.columns[112],
AcceptedQuestOperator: &self.columns[113],
AcceptedQuestSequence: &self.columns[114],
},
StoryDefineElement {CompletedQuest: &self.columns[115],
AcceptedQuest: &self.columns[116],
LayerSet: &self.columns[117],
Sequence: &self.columns[118],
CompletedQuestOperator: &self.columns[119],
AcceptedQuestOperator: &self.columns[120],
AcceptedQuestSequence: &self.columns[121],
},
StoryDefineElement {CompletedQuest: &self.columns[122],
AcceptedQuest: &self.columns[123],
LayerSet: &self.columns[124],
Sequence: &self.columns[125],
CompletedQuestOperator: &self.columns[126],
AcceptedQuestOperator: &self.columns[127],
AcceptedQuestSequence: &self.columns[128],
},
StoryDefineElement {CompletedQuest: &self.columns[129],
AcceptedQuest: &self.columns[130],
LayerSet: &self.columns[131],
Sequence: &self.columns[132],
CompletedQuestOperator: &self.columns[133],
AcceptedQuestOperator: &self.columns[134],
AcceptedQuestSequence: &self.columns[135],
},
StoryDefineElement {CompletedQuest: &self.columns[136],
AcceptedQuest: &self.columns[137],
LayerSet: &self.columns[138],
Sequence: &self.columns[139],
CompletedQuestOperator: &self.columns[140],
AcceptedQuestOperator: &self.columns[141],
AcceptedQuestSequence: &self.columns[142],
},
StoryDefineElement {CompletedQuest: &self.columns[143],
AcceptedQuest: &self.columns[144],
LayerSet: &self.columns[145],
Sequence: &self.columns[146],
CompletedQuestOperator: &self.columns[147],
AcceptedQuestOperator: &self.columns[148],
AcceptedQuestSequence: &self.columns[149],
},
StoryDefineElement {CompletedQuest: &self.columns[150],
AcceptedQuest: &self.columns[151],
LayerSet: &self.columns[152],
Sequence: &self.columns[153],
CompletedQuestOperator: &self.columns[154],
AcceptedQuestOperator: &self.columns[155],
AcceptedQuestSequence: &self.columns[156],
},
StoryDefineElement {CompletedQuest: &self.columns[157],
AcceptedQuest: &self.columns[158],
LayerSet: &self.columns[159],
Sequence: &self.columns[160],
CompletedQuestOperator: &self.columns[161],
AcceptedQuestOperator: &self.columns[162],
AcceptedQuestSequence: &self.columns[163],
},
StoryDefineElement {CompletedQuest: &self.columns[164],
AcceptedQuest: &self.columns[165],
LayerSet: &self.columns[166],
Sequence: &self.columns[167],
CompletedQuestOperator: &self.columns[168],
AcceptedQuestOperator: &self.columns[169],
AcceptedQuestSequence: &self.columns[170],
},
StoryDefineElement {CompletedQuest: &self.columns[171],
AcceptedQuest: &self.columns[172],
LayerSet: &self.columns[173],
Sequence: &self.columns[174],
CompletedQuestOperator: &self.columns[175],
AcceptedQuestOperator: &self.columns[176],
AcceptedQuestSequence: &self.columns[177],
},
StoryDefineElement {CompletedQuest: &self.columns[178],
AcceptedQuest: &self.columns[179],
LayerSet: &self.columns[180],
Sequence: &self.columns[181],
CompletedQuestOperator: &self.columns[182],
AcceptedQuestOperator: &self.columns[183],
AcceptedQuestSequence: &self.columns[184],
},
StoryDefineElement {CompletedQuest: &self.columns[185],
AcceptedQuest: &self.columns[186],
LayerSet: &self.columns[187],
Sequence: &self.columns[188],
CompletedQuestOperator: &self.columns[189],
AcceptedQuestOperator: &self.columns[190],
AcceptedQuestSequence: &self.columns[191],
},
StoryDefineElement {CompletedQuest: &self.columns[192],
AcceptedQuest: &self.columns[193],
LayerSet: &self.columns[194],
Sequence: &self.columns[195],
CompletedQuestOperator: &self.columns[196],
AcceptedQuestOperator: &self.columns[197],
AcceptedQuestSequence: &self.columns[198],
},
StoryDefineElement {CompletedQuest: &self.columns[199],
AcceptedQuest: &self.columns[200],
LayerSet: &self.columns[201],
Sequence: &self.columns[202],
CompletedQuestOperator: &self.columns[203],
AcceptedQuestOperator: &self.columns[204],
AcceptedQuestSequence: &self.columns[205],
},
StoryDefineElement {CompletedQuest: &self.columns[206],
AcceptedQuest: &self.columns[207],
LayerSet: &self.columns[208],
Sequence: &self.columns[209],
CompletedQuestOperator: &self.columns[210],
AcceptedQuestOperator: &self.columns[211],
AcceptedQuestSequence: &self.columns[212],
},
StoryDefineElement {CompletedQuest: &self.columns[213],
AcceptedQuest: &self.columns[214],
LayerSet: &self.columns[215],
Sequence: &self.columns[216],
CompletedQuestOperator: &self.columns[217],
AcceptedQuestOperator: &self.columns[218],
AcceptedQuestSequence: &self.columns[219],
},
StoryDefineElement {CompletedQuest: &self.columns[220],
AcceptedQuest: &self.columns[221],
LayerSet: &self.columns[222],
Sequence: &self.columns[223],
CompletedQuestOperator: &self.columns[224],
AcceptedQuestOperator: &self.columns[225],
AcceptedQuestSequence: &self.columns[226],
},
StoryDefineElement {CompletedQuest: &self.columns[227],
AcceptedQuest: &self.columns[228],
LayerSet: &self.columns[229],
Sequence: &self.columns[230],
CompletedQuestOperator: &self.columns[231],
AcceptedQuestOperator: &self.columns[232],
AcceptedQuestSequence: &self.columns[233],
},
StoryDefineElement {CompletedQuest: &self.columns[234],
AcceptedQuest: &self.columns[235],
LayerSet: &self.columns[236],
Sequence: &self.columns[237],
CompletedQuestOperator: &self.columns[238],
AcceptedQuestOperator: &self.columns[239],
AcceptedQuestSequence: &self.columns[240],
},
StoryDefineElement {CompletedQuest: &self.columns[241],
AcceptedQuest: &self.columns[242],
LayerSet: &self.columns[243],
Sequence: &self.columns[244],
CompletedQuestOperator: &self.columns[245],
AcceptedQuestOperator: &self.columns[246],
AcceptedQuestSequence: &self.columns[247],
},
StoryDefineElement {CompletedQuest: &self.columns[248],
AcceptedQuest: &self.columns[249],
LayerSet: &self.columns[250],
Sequence: &self.columns[251],
CompletedQuestOperator: &self.columns[252],
AcceptedQuestOperator: &self.columns[253],
AcceptedQuestSequence: &self.columns[254],
},
StoryDefineElement {CompletedQuest: &self.columns[255],
AcceptedQuest: &self.columns[256],
LayerSet: &self.columns[257],
Sequence: &self.columns[258],
CompletedQuestOperator: &self.columns[259],
AcceptedQuestOperator: &self.columns[260],
AcceptedQuestSequence: &self.columns[261],
},
StoryDefineElement {CompletedQuest: &self.columns[262],
AcceptedQuest: &self.columns[263],
LayerSet: &self.columns[264],
Sequence: &self.columns[265],
CompletedQuestOperator: &self.columns[266],
AcceptedQuestOperator: &self.columns[267],
AcceptedQuestSequence: &self.columns[268],
},
StoryDefineElement {CompletedQuest: &self.columns[269],
AcceptedQuest: &self.columns[270],
LayerSet: &self.columns[271],
Sequence: &self.columns[272],
CompletedQuestOperator: &self.columns[273],
AcceptedQuestOperator: &self.columns[274],
AcceptedQuestSequence: &self.columns[275],
},
StoryDefineElement {CompletedQuest: &self.columns[276],
AcceptedQuest: &self.columns[277],
LayerSet: &self.columns[278],
Sequence: &self.columns[279],
CompletedQuestOperator: &self.columns[280],
AcceptedQuestOperator: &self.columns[281],
AcceptedQuestSequence: &self.columns[282],
},
StoryDefineElement {CompletedQuest: &self.columns[283],
AcceptedQuest: &self.columns[284],
LayerSet: &self.columns[285],
Sequence: &self.columns[286],
CompletedQuestOperator: &self.columns[287],
AcceptedQuestOperator: &self.columns[288],
AcceptedQuestSequence: &self.columns[289],
},
StoryDefineElement {CompletedQuest: &self.columns[290],
AcceptedQuest: &self.columns[291],
LayerSet: &self.columns[292],
Sequence: &self.columns[293],
CompletedQuestOperator: &self.columns[294],
AcceptedQuestOperator: &self.columns[295],
AcceptedQuestSequence: &self.columns[296],
},
StoryDefineElement {CompletedQuest: &self.columns[297],
AcceptedQuest: &self.columns[298],
LayerSet: &self.columns[299],
Sequence: &self.columns[300],
CompletedQuestOperator: &self.columns[301],
AcceptedQuestOperator: &self.columns[302],
AcceptedQuestSequence: &self.columns[303],
},
StoryDefineElement {CompletedQuest: &self.columns[304],
AcceptedQuest: &self.columns[305],
LayerSet: &self.columns[306],
Sequence: &self.columns[307],
CompletedQuestOperator: &self.columns[308],
AcceptedQuestOperator: &self.columns[309],
AcceptedQuestSequence: &self.columns[310],
},
StoryDefineElement {CompletedQuest: &self.columns[311],
AcceptedQuest: &self.columns[312],
LayerSet: &self.columns[313],
Sequence: &self.columns[314],
CompletedQuestOperator: &self.columns[315],
AcceptedQuestOperator: &self.columns[316],
AcceptedQuestSequence: &self.columns[317],
},
StoryDefineElement {CompletedQuest: &self.columns[318],
AcceptedQuest: &self.columns[319],
LayerSet: &self.columns[320],
Sequence: &self.columns[321],
CompletedQuestOperator: &self.columns[322],
AcceptedQuestOperator: &self.columns[323],
AcceptedQuestSequence: &self.columns[324],
},
StoryDefineElement {CompletedQuest: &self.columns[325],
AcceptedQuest: &self.columns[326],
LayerSet: &self.columns[327],
Sequence: &self.columns[328],
CompletedQuestOperator: &self.columns[329],
AcceptedQuestOperator: &self.columns[330],
AcceptedQuestSequence: &self.columns[331],
},
StoryDefineElement {CompletedQuest: &self.columns[332],
AcceptedQuest: &self.columns[333],
LayerSet: &self.columns[334],
Sequence: &self.columns[335],
CompletedQuestOperator: &self.columns[336],
AcceptedQuestOperator: &self.columns[337],
AcceptedQuestSequence: &self.columns[338],
},
StoryDefineElement {CompletedQuest: &self.columns[339],
AcceptedQuest: &self.columns[340],
LayerSet: &self.columns[341],
Sequence: &self.columns[342],
CompletedQuestOperator: &self.columns[343],
AcceptedQuestOperator: &self.columns[344],
AcceptedQuestSequence: &self.columns[345],
},
StoryDefineElement {CompletedQuest: &self.columns[346],
AcceptedQuest: &self.columns[347],
LayerSet: &self.columns[348],
Sequence: &self.columns[349],
CompletedQuestOperator: &self.columns[350],
AcceptedQuestOperator: &self.columns[351],
AcceptedQuestSequence: &self.columns[352],
},
StoryDefineElement {CompletedQuest: &self.columns[353],
AcceptedQuest: &self.columns[354],
LayerSet: &self.columns[355],
Sequence: &self.columns[356],
CompletedQuestOperator: &self.columns[357],
AcceptedQuestOperator: &self.columns[358],
AcceptedQuestSequence: &self.columns[359],
},
StoryDefineElement {CompletedQuest: &self.columns[360],
AcceptedQuest: &self.columns[361],
LayerSet: &self.columns[362],
Sequence: &self.columns[363],
CompletedQuestOperator: &self.columns[364],
AcceptedQuestOperator: &self.columns[365],
AcceptedQuestSequence: &self.columns[366],
},
StoryDefineElement {CompletedQuest: &self.columns[367],
AcceptedQuest: &self.columns[368],
LayerSet: &self.columns[369],
Sequence: &self.columns[370],
CompletedQuestOperator: &self.columns[371],
AcceptedQuestOperator: &self.columns[372],
AcceptedQuestSequence: &self.columns[373],
},
StoryDefineElement {CompletedQuest: &self.columns[374],
AcceptedQuest: &self.columns[375],
LayerSet: &self.columns[376],
Sequence: &self.columns[377],
CompletedQuestOperator: &self.columns[378],
AcceptedQuestOperator: &self.columns[379],
AcceptedQuestSequence: &self.columns[380],
},
StoryDefineElement {CompletedQuest: &self.columns[381],
AcceptedQuest: &self.columns[382],
LayerSet: &self.columns[383],
Sequence: &self.columns[384],
CompletedQuestOperator: &self.columns[385],
AcceptedQuestOperator: &self.columns[386],
AcceptedQuestSequence: &self.columns[387],
},
StoryDefineElement {CompletedQuest: &self.columns[388],
AcceptedQuest: &self.columns[389],
LayerSet: &self.columns[390],
Sequence: &self.columns[391],
CompletedQuestOperator: &self.columns[392],
AcceptedQuestOperator: &self.columns[393],
AcceptedQuestSequence: &self.columns[394],
},
StoryDefineElement {CompletedQuest: &self.columns[395],
AcceptedQuest: &self.columns[396],
LayerSet: &self.columns[397],
Sequence: &self.columns[398],
CompletedQuestOperator: &self.columns[399],
AcceptedQuestOperator: &self.columns[400],
AcceptedQuestSequence: &self.columns[401],
},
StoryDefineElement {CompletedQuest: &self.columns[402],
AcceptedQuest: &self.columns[403],
LayerSet: &self.columns[404],
Sequence: &self.columns[405],
CompletedQuestOperator: &self.columns[406],
AcceptedQuestOperator: &self.columns[407],
AcceptedQuestSequence: &self.columns[408],
},
StoryDefineElement {CompletedQuest: &self.columns[409],
AcceptedQuest: &self.columns[410],
LayerSet: &self.columns[411],
Sequence: &self.columns[412],
CompletedQuestOperator: &self.columns[413],
AcceptedQuestOperator: &self.columns[414],
AcceptedQuestSequence: &self.columns[415],
},
StoryDefineElement {CompletedQuest: &self.columns[416],
AcceptedQuest: &self.columns[417],
LayerSet: &self.columns[418],
Sequence: &self.columns[419],
CompletedQuestOperator: &self.columns[420],
AcceptedQuestOperator: &self.columns[421],
AcceptedQuestSequence: &self.columns[422],
},
StoryDefineElement {CompletedQuest: &self.columns[423],
AcceptedQuest: &self.columns[424],
LayerSet: &self.columns[425],
Sequence: &self.columns[426],
CompletedQuestOperator: &self.columns[427],
AcceptedQuestOperator: &self.columns[428],
AcceptedQuestSequence: &self.columns[429],
},
StoryDefineElement {CompletedQuest: &self.columns[430],
AcceptedQuest: &self.columns[431],
LayerSet: &self.columns[432],
Sequence: &self.columns[433],
CompletedQuestOperator: &self.columns[434],
AcceptedQuestOperator: &self.columns[435],
AcceptedQuestSequence: &self.columns[436],
},
StoryDefineElement {CompletedQuest: &self.columns[437],
AcceptedQuest: &self.columns[438],
LayerSet: &self.columns[439],
Sequence: &self.columns[440],
CompletedQuestOperator: &self.columns[441],
AcceptedQuestOperator: &self.columns[442],
AcceptedQuestSequence: &self.columns[443],
},
StoryDefineElement {CompletedQuest: &self.columns[444],
AcceptedQuest: &self.columns[445],
LayerSet: &self.columns[446],
Sequence: &self.columns[447],
CompletedQuestOperator: &self.columns[448],
AcceptedQuestOperator: &self.columns[449],
AcceptedQuestSequence: &self.columns[450],
},
StoryDefineElement {CompletedQuest: &self.columns[451],
AcceptedQuest: &self.columns[452],
LayerSet: &self.columns[453],
Sequence: &self.columns[454],
CompletedQuestOperator: &self.columns[455],
AcceptedQuestOperator: &self.columns[456],
AcceptedQuestSequence: &self.columns[457],
},
StoryDefineElement {CompletedQuest: &self.columns[458],
AcceptedQuest: &self.columns[459],
LayerSet: &self.columns[460],
Sequence: &self.columns[461],
CompletedQuestOperator: &self.columns[462],
AcceptedQuestOperator: &self.columns[463],
AcceptedQuestSequence: &self.columns[464],
},
StoryDefineElement {CompletedQuest: &self.columns[465],
AcceptedQuest: &self.columns[466],
LayerSet: &self.columns[467],
Sequence: &self.columns[468],
CompletedQuestOperator: &self.columns[469],
AcceptedQuestOperator: &self.columns[470],
AcceptedQuestSequence: &self.columns[471],
},
StoryDefineElement {CompletedQuest: &self.columns[472],
AcceptedQuest: &self.columns[473],
LayerSet: &self.columns[474],
Sequence: &self.columns[475],
CompletedQuestOperator: &self.columns[476],
AcceptedQuestOperator: &self.columns[477],
AcceptedQuestSequence: &self.columns[478],
},
StoryDefineElement {CompletedQuest: &self.columns[479],
AcceptedQuest: &self.columns[480],
LayerSet: &self.columns[481],
Sequence: &self.columns[482],
CompletedQuestOperator: &self.columns[483],
AcceptedQuestOperator: &self.columns[484],
AcceptedQuestSequence: &self.columns[485],
},
StoryDefineElement {CompletedQuest: &self.columns[486],
AcceptedQuest: &self.columns[487],
LayerSet: &self.columns[488],
Sequence: &self.columns[489],
CompletedQuestOperator: &self.columns[490],
AcceptedQuestOperator: &self.columns[491],
AcceptedQuestSequence: &self.columns[492],
},
StoryDefineElement {CompletedQuest: &self.columns[493],
AcceptedQuest: &self.columns[494],
LayerSet: &self.columns[495],
Sequence: &self.columns[496],
CompletedQuestOperator: &self.columns[497],
AcceptedQuestOperator: &self.columns[498],
AcceptedQuestSequence: &self.columns[499],
},
StoryDefineElement {CompletedQuest: &self.columns[500],
AcceptedQuest: &self.columns[501],
LayerSet: &self.columns[502],
Sequence: &self.columns[503],
CompletedQuestOperator: &self.columns[504],
AcceptedQuestOperator: &self.columns[505],
AcceptedQuestSequence: &self.columns[506],
},
StoryDefineElement {CompletedQuest: &self.columns[507],
AcceptedQuest: &self.columns[508],
LayerSet: &self.columns[509],
Sequence: &self.columns[510],
CompletedQuestOperator: &self.columns[511],
AcceptedQuestOperator: &self.columns[512],
AcceptedQuestSequence: &self.columns[513],
},
StoryDefineElement {CompletedQuest: &self.columns[514],
AcceptedQuest: &self.columns[515],
LayerSet: &self.columns[516],
Sequence: &self.columns[517],
CompletedQuestOperator: &self.columns[518],
AcceptedQuestOperator: &self.columns[519],
AcceptedQuestSequence: &self.columns[520],
},
StoryDefineElement {CompletedQuest: &self.columns[521],
AcceptedQuest: &self.columns[522],
LayerSet: &self.columns[523],
Sequence: &self.columns[524],
CompletedQuestOperator: &self.columns[525],
AcceptedQuestOperator: &self.columns[526],
AcceptedQuestSequence: &self.columns[527],
},
StoryDefineElement {CompletedQuest: &self.columns[528],
AcceptedQuest: &self.columns[529],
LayerSet: &self.columns[530],
Sequence: &self.columns[531],
CompletedQuestOperator: &self.columns[532],
AcceptedQuestOperator: &self.columns[533],
AcceptedQuestSequence: &self.columns[534],
},
StoryDefineElement {CompletedQuest: &self.columns[535],
AcceptedQuest: &self.columns[536],
LayerSet: &self.columns[537],
Sequence: &self.columns[538],
CompletedQuestOperator: &self.columns[539],
AcceptedQuestOperator: &self.columns[540],
AcceptedQuestSequence: &self.columns[541],
},
StoryDefineElement {CompletedQuest: &self.columns[542],
AcceptedQuest: &self.columns[543],
LayerSet: &self.columns[544],
Sequence: &self.columns[545],
CompletedQuestOperator: &self.columns[546],
AcceptedQuestOperator: &self.columns[547],
AcceptedQuestSequence: &self.columns[548],
},
StoryDefineElement {CompletedQuest: &self.columns[549],
AcceptedQuest: &self.columns[550],
LayerSet: &self.columns[551],
Sequence: &self.columns[552],
CompletedQuestOperator: &self.columns[553],
AcceptedQuestOperator: &self.columns[554],
AcceptedQuestSequence: &self.columns[555],
},
StoryDefineElement {CompletedQuest: &self.columns[556],
AcceptedQuest: &self.columns[557],
LayerSet: &self.columns[558],
Sequence: &self.columns[559],
CompletedQuestOperator: &self.columns[560],
AcceptedQuestOperator: &self.columns[561],
AcceptedQuestSequence: &self.columns[562],
},
StoryDefineElement {CompletedQuest: &self.columns[563],
AcceptedQuest: &self.columns[564],
LayerSet: &self.columns[565],
Sequence: &self.columns[566],
CompletedQuestOperator: &self.columns[567],
AcceptedQuestOperator: &self.columns[568],
AcceptedQuestSequence: &self.columns[569],
},
StoryDefineElement {CompletedQuest: &self.columns[570],
AcceptedQuest: &self.columns[571],
LayerSet: &self.columns[572],
Sequence: &self.columns[573],
CompletedQuestOperator: &self.columns[574],
AcceptedQuestOperator: &self.columns[575],
AcceptedQuestSequence: &self.columns[576],
},
StoryDefineElement {CompletedQuest: &self.columns[577],
AcceptedQuest: &self.columns[578],
LayerSet: &self.columns[579],
Sequence: &self.columns[580],
CompletedQuestOperator: &self.columns[581],
AcceptedQuestOperator: &self.columns[582],
AcceptedQuestSequence: &self.columns[583],
},
StoryDefineElement {CompletedQuest: &self.columns[584],
AcceptedQuest: &self.columns[585],
LayerSet: &self.columns[586],
Sequence: &self.columns[587],
CompletedQuestOperator: &self.columns[588],
AcceptedQuestOperator: &self.columns[589],
AcceptedQuestSequence: &self.columns[590],
},
StoryDefineElement {CompletedQuest: &self.columns[591],
AcceptedQuest: &self.columns[592],
LayerSet: &self.columns[593],
Sequence: &self.columns[594],
CompletedQuestOperator: &self.columns[595],
AcceptedQuestOperator: &self.columns[596],
AcceptedQuestSequence: &self.columns[597],
},
StoryDefineElement {CompletedQuest: &self.columns[598],
AcceptedQuest: &self.columns[599],
LayerSet: &self.columns[600],
Sequence: &self.columns[601],
CompletedQuestOperator: &self.columns[602],
AcceptedQuestOperator: &self.columns[603],
AcceptedQuestSequence: &self.columns[604],
},
StoryDefineElement {CompletedQuest: &self.columns[605],
AcceptedQuest: &self.columns[606],
LayerSet: &self.columns[607],
Sequence: &self.columns[608],
CompletedQuestOperator: &self.columns[609],
AcceptedQuestOperator: &self.columns[610],
AcceptedQuestSequence: &self.columns[611],
},
StoryDefineElement {CompletedQuest: &self.columns[612],
AcceptedQuest: &self.columns[613],
LayerSet: &self.columns[614],
Sequence: &self.columns[615],
CompletedQuestOperator: &self.columns[616],
AcceptedQuestOperator: &self.columns[617],
AcceptedQuestSequence: &self.columns[618],
},
StoryDefineElement {CompletedQuest: &self.columns[619],
AcceptedQuest: &self.columns[620],
LayerSet: &self.columns[621],
Sequence: &self.columns[622],
CompletedQuestOperator: &self.columns[623],
AcceptedQuestOperator: &self.columns[624],
AcceptedQuestSequence: &self.columns[625],
},
StoryDefineElement {CompletedQuest: &self.columns[626],
AcceptedQuest: &self.columns[627],
LayerSet: &self.columns[628],
Sequence: &self.columns[629],
CompletedQuestOperator: &self.columns[630],
AcceptedQuestOperator: &self.columns[631],
AcceptedQuestSequence: &self.columns[632],
},
StoryDefineElement {CompletedQuest: &self.columns[633],
AcceptedQuest: &self.columns[634],
LayerSet: &self.columns[635],
Sequence: &self.columns[636],
CompletedQuestOperator: &self.columns[637],
AcceptedQuestOperator: &self.columns[638],
AcceptedQuestSequence: &self.columns[639],
},
StoryDefineElement {CompletedQuest: &self.columns[640],
AcceptedQuest: &self.columns[641],
LayerSet: &self.columns[642],
Sequence: &self.columns[643],
CompletedQuestOperator: &self.columns[644],
AcceptedQuestOperator: &self.columns[645],
AcceptedQuestSequence: &self.columns[646],
},
StoryDefineElement {CompletedQuest: &self.columns[647],
AcceptedQuest: &self.columns[648],
LayerSet: &self.columns[649],
Sequence: &self.columns[650],
CompletedQuestOperator: &self.columns[651],
AcceptedQuestOperator: &self.columns[652],
AcceptedQuestSequence: &self.columns[653],
},
StoryDefineElement {CompletedQuest: &self.columns[654],
AcceptedQuest: &self.columns[655],
LayerSet: &self.columns[656],
Sequence: &self.columns[657],
CompletedQuestOperator: &self.columns[658],
AcceptedQuestOperator: &self.columns[659],
AcceptedQuestSequence: &self.columns[660],
},
StoryDefineElement {CompletedQuest: &self.columns[661],
AcceptedQuest: &self.columns[662],
LayerSet: &self.columns[663],
Sequence: &self.columns[664],
CompletedQuestOperator: &self.columns[665],
AcceptedQuestOperator: &self.columns[666],
AcceptedQuestSequence: &self.columns[667],
},
StoryDefineElement {CompletedQuest: &self.columns[668],
AcceptedQuest: &self.columns[669],
LayerSet: &self.columns[670],
Sequence: &self.columns[671],
CompletedQuestOperator: &self.columns[672],
AcceptedQuestOperator: &self.columns[673],
AcceptedQuestSequence: &self.columns[674],
},
StoryDefineElement {CompletedQuest: &self.columns[675],
AcceptedQuest: &self.columns[676],
LayerSet: &self.columns[677],
Sequence: &self.columns[678],
CompletedQuestOperator: &self.columns[679],
AcceptedQuestOperator: &self.columns[680],
AcceptedQuestSequence: &self.columns[681],
},
StoryDefineElement {CompletedQuest: &self.columns[682],
AcceptedQuest: &self.columns[683],
LayerSet: &self.columns[684],
Sequence: &self.columns[685],
CompletedQuestOperator: &self.columns[686],
AcceptedQuestOperator: &self.columns[687],
AcceptedQuestSequence: &self.columns[688],
},
StoryDefineElement {CompletedQuest: &self.columns[689],
AcceptedQuest: &self.columns[690],
LayerSet: &self.columns[691],
Sequence: &self.columns[692],
CompletedQuestOperator: &self.columns[693],
AcceptedQuestOperator: &self.columns[694],
AcceptedQuestSequence: &self.columns[695],
},
StoryDefineElement {CompletedQuest: &self.columns[696],
AcceptedQuest: &self.columns[697],
LayerSet: &self.columns[698],
Sequence: &self.columns[699],
CompletedQuestOperator: &self.columns[700],
AcceptedQuestOperator: &self.columns[701],
AcceptedQuestSequence: &self.columns[702],
},
StoryDefineElement {CompletedQuest: &self.columns[703],
AcceptedQuest: &self.columns[704],
LayerSet: &self.columns[705],
Sequence: &self.columns[706],
CompletedQuestOperator: &self.columns[707],
AcceptedQuestOperator: &self.columns[708],
AcceptedQuestSequence: &self.columns[709],
},
StoryDefineElement {CompletedQuest: &self.columns[710],
AcceptedQuest: &self.columns[711],
LayerSet: &self.columns[712],
Sequence: &self.columns[713],
CompletedQuestOperator: &self.columns[714],
AcceptedQuestOperator: &self.columns[715],
AcceptedQuestSequence: &self.columns[716],
},
StoryDefineElement {CompletedQuest: &self.columns[717],
AcceptedQuest: &self.columns[718],
LayerSet: &self.columns[719],
Sequence: &self.columns[720],
CompletedQuestOperator: &self.columns[721],
AcceptedQuestOperator: &self.columns[722],
AcceptedQuestSequence: &self.columns[723],
},
StoryDefineElement {CompletedQuest: &self.columns[724],
AcceptedQuest: &self.columns[725],
LayerSet: &self.columns[726],
Sequence: &self.columns[727],
CompletedQuestOperator: &self.columns[728],
AcceptedQuestOperator: &self.columns[729],
AcceptedQuestSequence: &self.columns[730],
},
StoryDefineElement {CompletedQuest: &self.columns[731],
AcceptedQuest: &self.columns[732],
LayerSet: &self.columns[733],
Sequence: &self.columns[734],
CompletedQuestOperator: &self.columns[735],
AcceptedQuestOperator: &self.columns[736],
AcceptedQuestSequence: &self.columns[737],
},
StoryDefineElement {CompletedQuest: &self.columns[738],
AcceptedQuest: &self.columns[739],
LayerSet: &self.columns[740],
Sequence: &self.columns[741],
CompletedQuestOperator: &self.columns[742],
AcceptedQuestOperator: &self.columns[743],
AcceptedQuestSequence: &self.columns[744],
},
StoryDefineElement {CompletedQuest: &self.columns[745],
AcceptedQuest: &self.columns[746],
LayerSet: &self.columns[747],
Sequence: &self.columns[748],
CompletedQuestOperator: &self.columns[749],
AcceptedQuestOperator: &self.columns[750],
AcceptedQuestSequence: &self.columns[751],
},
StoryDefineElement {CompletedQuest: &self.columns[752],
AcceptedQuest: &self.columns[753],
LayerSet: &self.columns[754],
Sequence: &self.columns[755],
CompletedQuestOperator: &self.columns[756],
AcceptedQuestOperator: &self.columns[757],
AcceptedQuestSequence: &self.columns[758],
},
StoryDefineElement {CompletedQuest: &self.columns[759],
AcceptedQuest: &self.columns[760],
LayerSet: &self.columns[761],
Sequence: &self.columns[762],
CompletedQuestOperator: &self.columns[763],
AcceptedQuestOperator: &self.columns[764],
AcceptedQuestSequence: &self.columns[765],
},
StoryDefineElement {CompletedQuest: &self.columns[766],
AcceptedQuest: &self.columns[767],
LayerSet: &self.columns[768],
Sequence: &self.columns[769],
CompletedQuestOperator: &self.columns[770],
AcceptedQuestOperator: &self.columns[771],
AcceptedQuestSequence: &self.columns[772],
},
StoryDefineElement {CompletedQuest: &self.columns[773],
AcceptedQuest: &self.columns[774],
LayerSet: &self.columns[775],
Sequence: &self.columns[776],
CompletedQuestOperator: &self.columns[777],
AcceptedQuestOperator: &self.columns[778],
AcceptedQuestSequence: &self.columns[779],
},
StoryDefineElement {CompletedQuest: &self.columns[780],
AcceptedQuest: &self.columns[781],
LayerSet: &self.columns[782],
Sequence: &self.columns[783],
CompletedQuestOperator: &self.columns[784],
AcceptedQuestOperator: &self.columns[785],
AcceptedQuestSequence: &self.columns[786],
},
StoryDefineElement {CompletedQuest: &self.columns[787],
AcceptedQuest: &self.columns[788],
LayerSet: &self.columns[789],
Sequence: &self.columns[790],
CompletedQuestOperator: &self.columns[791],
AcceptedQuestOperator: &self.columns[792],
AcceptedQuestSequence: &self.columns[793],
},
StoryDefineElement {CompletedQuest: &self.columns[794],
AcceptedQuest: &self.columns[795],
LayerSet: &self.columns[796],
Sequence: &self.columns[797],
CompletedQuestOperator: &self.columns[798],
AcceptedQuestOperator: &self.columns[799],
AcceptedQuestSequence: &self.columns[800],
},
StoryDefineElement {CompletedQuest: &self.columns[801],
AcceptedQuest: &self.columns[802],
LayerSet: &self.columns[803],
Sequence: &self.columns[804],
CompletedQuestOperator: &self.columns[805],
AcceptedQuestOperator: &self.columns[806],
AcceptedQuestSequence: &self.columns[807],
},
StoryDefineElement {CompletedQuest: &self.columns[808],
AcceptedQuest: &self.columns[809],
LayerSet: &self.columns[810],
Sequence: &self.columns[811],
CompletedQuestOperator: &self.columns[812],
AcceptedQuestOperator: &self.columns[813],
AcceptedQuestSequence: &self.columns[814],
},
StoryDefineElement {CompletedQuest: &self.columns[815],
AcceptedQuest: &self.columns[816],
LayerSet: &self.columns[817],
Sequence: &self.columns[818],
CompletedQuestOperator: &self.columns[819],
AcceptedQuestOperator: &self.columns[820],
AcceptedQuestSequence: &self.columns[821],
},
StoryDefineElement {CompletedQuest: &self.columns[822],
AcceptedQuest: &self.columns[823],
LayerSet: &self.columns[824],
Sequence: &self.columns[825],
CompletedQuestOperator: &self.columns[826],
AcceptedQuestOperator: &self.columns[827],
AcceptedQuestSequence: &self.columns[828],
},
StoryDefineElement {CompletedQuest: &self.columns[829],
AcceptedQuest: &self.columns[830],
LayerSet: &self.columns[831],
Sequence: &self.columns[832],
CompletedQuestOperator: &self.columns[833],
AcceptedQuestOperator: &self.columns[834],
AcceptedQuestSequence: &self.columns[835],
},
StoryDefineElement {CompletedQuest: &self.columns[836],
AcceptedQuest: &self.columns[837],
LayerSet: &self.columns[838],
Sequence: &self.columns[839],
CompletedQuestOperator: &self.columns[840],
AcceptedQuestOperator: &self.columns[841],
AcceptedQuestSequence: &self.columns[842],
},
StoryDefineElement {CompletedQuest: &self.columns[843],
AcceptedQuest: &self.columns[844],
LayerSet: &self.columns[845],
Sequence: &self.columns[846],
CompletedQuestOperator: &self.columns[847],
AcceptedQuestOperator: &self.columns[848],
AcceptedQuestSequence: &self.columns[849],
},
]
}
pub fn StoryListener<'a>(&'a self) -> [StoryListenerElement<'a>; 80] {
[StoryListenerElement {Listener: &self.columns[850],
SequenceBegin: &self.columns[851],
SequenceEnd: &self.columns[852],
},
StoryListenerElement {Listener: &self.columns[853],
SequenceBegin: &self.columns[854],
SequenceEnd: &self.columns[855],
},
StoryListenerElement {Listener: &self.columns[856],
SequenceBegin: &self.columns[857],
SequenceEnd: &self.columns[858],
},
StoryListenerElement {Listener: &self.columns[859],
SequenceBegin: &self.columns[860],
SequenceEnd: &self.columns[861],
},
StoryListenerElement {Listener: &self.columns[862],
SequenceBegin: &self.columns[863],
SequenceEnd: &self.columns[864],
},
StoryListenerElement {Listener: &self.columns[865],
SequenceBegin: &self.columns[866],
SequenceEnd: &self.columns[867],
},
StoryListenerElement {Listener: &self.columns[868],
SequenceBegin: &self.columns[869],
SequenceEnd: &self.columns[870],
},
StoryListenerElement {Listener: &self.columns[871],
SequenceBegin: &self.columns[872],
SequenceEnd: &self.columns[873],
},
StoryListenerElement {Listener: &self.columns[874],
SequenceBegin: &self.columns[875],
SequenceEnd: &self.columns[876],
},
StoryListenerElement {Listener: &self.columns[877],
SequenceBegin: &self.columns[878],
SequenceEnd: &self.columns[879],
},
StoryListenerElement {Listener: &self.columns[880],
SequenceBegin: &self.columns[881],
SequenceEnd: &self.columns[882],
},
StoryListenerElement {Listener: &self.columns[883],
SequenceBegin: &self.columns[884],
SequenceEnd: &self.columns[885],
},
StoryListenerElement {Listener: &self.columns[886],
SequenceBegin: &self.columns[887],
SequenceEnd: &self.columns[888],
},
StoryListenerElement {Listener: &self.columns[889],
SequenceBegin: &self.columns[890],
SequenceEnd: &self.columns[891],
},
StoryListenerElement {Listener: &self.columns[892],
SequenceBegin: &self.columns[893],
SequenceEnd: &self.columns[894],
},
StoryListenerElement {Listener: &self.columns[895],
SequenceBegin: &self.columns[896],
SequenceEnd: &self.columns[897],
},
StoryListenerElement {Listener: &self.columns[898],
SequenceBegin: &self.columns[899],
SequenceEnd: &self.columns[900],
},
StoryListenerElement {Listener: &self.columns[901],
SequenceBegin: &self.columns[902],
SequenceEnd: &self.columns[903],
},
StoryListenerElement {Listener: &self.columns[904],
SequenceBegin: &self.columns[905],
SequenceEnd: &self.columns[906],
},
StoryListenerElement {Listener: &self.columns[907],
SequenceBegin: &self.columns[908],
SequenceEnd: &self.columns[909],
},
StoryListenerElement {Listener: &self.columns[910],
SequenceBegin: &self.columns[911],
SequenceEnd: &self.columns[912],
},
StoryListenerElement {Listener: &self.columns[913],
SequenceBegin: &self.columns[914],
SequenceEnd: &self.columns[915],
},
StoryListenerElement {Listener: &self.columns[916],
SequenceBegin: &self.columns[917],
SequenceEnd: &self.columns[918],
},
StoryListenerElement {Listener: &self.columns[919],
SequenceBegin: &self.columns[920],
SequenceEnd: &self.columns[921],
},
StoryListenerElement {Listener: &self.columns[922],
SequenceBegin: &self.columns[923],
SequenceEnd: &self.columns[924],
},
StoryListenerElement {Listener: &self.columns[925],
SequenceBegin: &self.columns[926],
SequenceEnd: &self.columns[927],
},
StoryListenerElement {Listener: &self.columns[928],
SequenceBegin: &self.columns[929],
SequenceEnd: &self.columns[930],
},
StoryListenerElement {Listener: &self.columns[931],
SequenceBegin: &self.columns[932],
SequenceEnd: &self.columns[933],
},
StoryListenerElement {Listener: &self.columns[934],
SequenceBegin: &self.columns[935],
SequenceEnd: &self.columns[936],
},
StoryListenerElement {Listener: &self.columns[937],
SequenceBegin: &self.columns[938],
SequenceEnd: &self.columns[939],
},
StoryListenerElement {Listener: &self.columns[940],
SequenceBegin: &self.columns[941],
SequenceEnd: &self.columns[942],
},
StoryListenerElement {Listener: &self.columns[943],
SequenceBegin: &self.columns[944],
SequenceEnd: &self.columns[945],
},
StoryListenerElement {Listener: &self.columns[946],
SequenceBegin: &self.columns[947],
SequenceEnd: &self.columns[948],
},
StoryListenerElement {Listener: &self.columns[949],
SequenceBegin: &self.columns[950],
SequenceEnd: &self.columns[951],
},
StoryListenerElement {Listener: &self.columns[952],
SequenceBegin: &self.columns[953],
SequenceEnd: &self.columns[954],
},
StoryListenerElement {Listener: &self.columns[955],
SequenceBegin: &self.columns[956],
SequenceEnd: &self.columns[957],
},
StoryListenerElement {Listener: &self.columns[958],
SequenceBegin: &self.columns[959],
SequenceEnd: &self.columns[960],
},
StoryListenerElement {Listener: &self.columns[961],
SequenceBegin: &self.columns[962],
SequenceEnd: &self.columns[963],
},
StoryListenerElement {Listener: &self.columns[964],
SequenceBegin: &self.columns[965],
SequenceEnd: &self.columns[966],
},
StoryListenerElement {Listener: &self.columns[967],
SequenceBegin: &self.columns[968],
SequenceEnd: &self.columns[969],
},
StoryListenerElement {Listener: &self.columns[970],
SequenceBegin: &self.columns[971],
SequenceEnd: &self.columns[972],
},
StoryListenerElement {Listener: &self.columns[973],
SequenceBegin: &self.columns[974],
SequenceEnd: &self.columns[975],
},
StoryListenerElement {Listener: &self.columns[976],
SequenceBegin: &self.columns[977],
SequenceEnd: &self.columns[978],
},
StoryListenerElement {Listener: &self.columns[979],
SequenceBegin: &self.columns[980],
SequenceEnd: &self.columns[981],
},
StoryListenerElement {Listener: &self.columns[982],
SequenceBegin: &self.columns[983],
SequenceEnd: &self.columns[984],
},
StoryListenerElement {Listener: &self.columns[985],
SequenceBegin: &self.columns[986],
SequenceEnd: &self.columns[987],
},
StoryListenerElement {Listener: &self.columns[988],
SequenceBegin: &self.columns[989],
SequenceEnd: &self.columns[990],
},
StoryListenerElement {Listener: &self.columns[991],
SequenceBegin: &self.columns[992],
SequenceEnd: &self.columns[993],
},
StoryListenerElement {Listener: &self.columns[994],
SequenceBegin: &self.columns[995],
SequenceEnd: &self.columns[996],
},
StoryListenerElement {Listener: &self.columns[997],
SequenceBegin: &self.columns[998],
SequenceEnd: &self.columns[999],
},
StoryListenerElement {Listener: &self.columns[1000],
SequenceBegin: &self.columns[1001],
SequenceEnd: &self.columns[1002],
},
StoryListenerElement {Listener: &self.columns[1003],
SequenceBegin: &self.columns[1004],
SequenceEnd: &self.columns[1005],
},
StoryListenerElement {Listener: &self.columns[1006],
SequenceBegin: &self.columns[1007],
SequenceEnd: &self.columns[1008],
},
StoryListenerElement {Listener: &self.columns[1009],
SequenceBegin: &self.columns[1010],
SequenceEnd: &self.columns[1011],
},
StoryListenerElement {Listener: &self.columns[1012],
SequenceBegin: &self.columns[1013],
SequenceEnd: &self.columns[1014],
},
StoryListenerElement {Listener: &self.columns[1015],
SequenceBegin: &self.columns[1016],
SequenceEnd: &self.columns[1017],
},
StoryListenerElement {Listener: &self.columns[1018],
SequenceBegin: &self.columns[1019],
SequenceEnd: &self.columns[1020],
},
StoryListenerElement {Listener: &self.columns[1021],
SequenceBegin: &self.columns[1022],
SequenceEnd: &self.columns[1023],
},
StoryListenerElement {Listener: &self.columns[1024],
SequenceBegin: &self.columns[1025],
SequenceEnd: &self.columns[1026],
},
StoryListenerElement {Listener: &self.columns[1027],
SequenceBegin: &self.columns[1028],
SequenceEnd: &self.columns[1029],
},
StoryListenerElement {Listener: &self.columns[1030],
SequenceBegin: &self.columns[1031],
SequenceEnd: &self.columns[1032],
},
StoryListenerElement {Listener: &self.columns[1033],
SequenceBegin: &self.columns[1034],
SequenceEnd: &self.columns[1035],
},
StoryListenerElement {Listener: &self.columns[1036],
SequenceBegin: &self.columns[1037],
SequenceEnd: &self.columns[1038],
},
StoryListenerElement {Listener: &self.columns[1039],
SequenceBegin: &self.columns[1040],
SequenceEnd: &self.columns[1041],
},
StoryListenerElement {Listener: &self.columns[1042],
SequenceBegin: &self.columns[1043],
SequenceEnd: &self.columns[1044],
},
StoryListenerElement {Listener: &self.columns[1045],
SequenceBegin: &self.columns[1046],
SequenceEnd: &self.columns[1047],
},
StoryListenerElement {Listener: &self.columns[1048],
SequenceBegin: &self.columns[1049],
SequenceEnd: &self.columns[1050],
},
StoryListenerElement {Listener: &self.columns[1051],
SequenceBegin: &self.columns[1052],
SequenceEnd: &self.columns[1053],
},
StoryListenerElement {Listener: &self.columns[1054],
SequenceBegin: &self.columns[1055],
SequenceEnd: &self.columns[1056],
},
StoryListenerElement {Listener: &self.columns[1057],
SequenceBegin: &self.columns[1058],
SequenceEnd: &self.columns[1059],
},
StoryListenerElement {Listener: &self.columns[1060],
SequenceBegin: &self.columns[1061],
SequenceEnd: &self.columns[1062],
},
StoryListenerElement {Listener: &self.columns[1063],
SequenceBegin: &self.columns[1064],
SequenceEnd: &self.columns[1065],
},
StoryListenerElement {Listener: &self.columns[1066],
SequenceBegin: &self.columns[1067],
SequenceEnd: &self.columns[1068],
},
StoryListenerElement {Listener: &self.columns[1069],
SequenceBegin: &self.columns[1070],
SequenceEnd: &self.columns[1071],
},
StoryListenerElement {Listener: &self.columns[1072],
SequenceBegin: &self.columns[1073],
SequenceEnd: &self.columns[1074],
},
StoryListenerElement {Listener: &self.columns[1075],
SequenceBegin: &self.columns[1076],
SequenceEnd: &self.columns[1077],
},
StoryListenerElement {Listener: &self.columns[1078],
SequenceBegin: &self.columns[1079],
SequenceEnd: &self.columns[1080],
},
StoryListenerElement {Listener: &self.columns[1081],
SequenceBegin: &self.columns[1082],
SequenceEnd: &self.columns[1083],
},
StoryListenerElement {Listener: &self.columns[1084],
SequenceBegin: &self.columns[1085],
SequenceEnd: &self.columns[1086],
},
StoryListenerElement {Listener: &self.columns[1087],
SequenceBegin: &self.columns[1088],
SequenceEnd: &self.columns[1089],
},
]
}
pub fn Script(&self) -> &ColumnData {
&self.columns[1090]
}
pub fn LayerSetTerritoryType(&self) -> [&ColumnData; 2] {
[&self.columns[1091],&self.columns[1092],]
}
}
